### ISSUE TITLE
libnetconf ERROR: Authentication failed (Invalid signature for supplied public key, or bad username/public key combination)

### ISSUE THREAD

**Issue by niyaz000** [CESNET/netopeer#103]
I am able to connect it through sugue soft client in windows machine  but it is throwing error with netopeer client in linux machine.

**Comment by michalvasko** [comment]
Hi,
firstly, please include a short description of the problem in the name and a longer description in the body of an issue.

Secondly, the longer description (body) should also include what version of libnetconf and netopeer you are using and depending on the issue also a description of what you were doing, what your configuration is, or anything that may be relevant.

Next, based on the error it seems you are using an old version of libnetconf and netopeer, update them both to master branches. We do not provide support for older versions.

Lastly, my guess is that you try to use a public key that netopeer does not consider authorized or with the wrong username, so the authentication fails.

Regards,
Michal
