### ISSUE TITLE
How to specify Netconf TLS certificates on the server side

### ISSUE THREAD

**Issue by mukundanaresh** [CESNET/netopeer#104]
Hi All,
I have generated and installed certificates under /etc/ssl/certs/ directory in Linux
root@virtualbox certs]# pwd
/etc/ssl/certs
[root@virtualbox certs]# ls
ca.crt ca.key ca.pem client.crt client.csr client.key server.crt server.csr server.key

I understand something this XML netopeer/build/server/config/datastore.xml file is used for TLS certificate information.
1. Is this XML file auto generated or manually updated with cert info and maps?
2. Getting failure at cert_to_name mapping When trying to connect NC Server wih Netopeer cli with below error.

CL08150:Apr 6 16:30:56 virtualbox netopeer-cli: NETCONF[] [mdc@644 class="tls.c:nc_tls_init:192" level="DEB " number="0" thread="32076" time="99755.495" addinfo="misc-d"] - TLS subsystem reinitiation. Resetting certificates settings
CL08150:Apr 6 16:30:56 virtualbox netopeer-server[302]: Cert verify: depth 1
CL08150:Apr 6 16:30:56 virtualbox netopeer-server[302]: Cert verify: subject: /C=XX/L=Default City/O=Default Company Ltd/CN=rootca
CL08150:Apr 6 16:30:56 virtualbox netopeer-server[302]: Cert verify: issuer: /C=XX/L=Default City/O=Default Company Ltd/CN=rootca
CL08150:Apr 6 16:30:56 virtualbox netopeer-server[302]: tls_cert_to_name: unknown fingerprint algorithm used (9a:cc:f6:94:90:04:e9:23:a0:32:39:ce:2c:f4:e2:5f:93:b7:db:da), skipping
CL08150:Apr 6 16:30:56 virtualbox netopeer-server[302]: tls_cert_to_name: unknown fingerprint algorithm used (43:61:c9:fa:ee:68:ca:1a:11:7f:73:2c:ea:83:60:42:ae:1b:c2:8a), skipping
CL08150:Apr 6 16:30:56 virtualbox netopeer-server[302]: Cert verify CTN: cert fail: cert-to-name will continue on the next cert in chain
CL08150:Apr 6 16:30:56 virtualbox netopeer-server[302]: Cert verify: depth 0
CL08150:Apr 6 16:30:56 virtualbox netopeer-server[302]: Cert verify: subject: /C=XX/L=Default City/O=Default Company Ltd/CN=client
CL08150:Apr 6 16:30:56 virtualbox netopeer-server[302]: Cert verify: issuer: /C=XX/L=Default City/O=Default Company Ltd/CN=rootca
CL08150:Apr 6 16:30:56 virtualbox netopeer-server[302]: tls_cert_to_name: unknown fingerprint algorithm used (9a:cc:f6:94:90:04:e9:23:a0:32:39:ce:2c:f4:e2:5f:93:b7:db:da), skipping
CL08150:Apr 6 16:30:56 virtualbox netopeer-server[302]: tls_cert_to_name: unknown fingerprint algorithm used (43:61:c9:fa:ee:68:ca:1a:11:7f:73:2c:ea:83:60:42:ae:1b:c2:8a), skipping
CL08150:Apr 6 16:30:56 virtualbox netopeer-server[302]: Cert-to-name unsuccessful, dropping the new client.
CL08150:Apr 6 16:30:56 virtualbox netopeer-server[302]: TLS accept failed (no certificate returned).
CL08150:Apr 6 16:30:56 virtualbox netopeer-cli: NETCONF[] [mdc@644 class="tls.c:nc_session_connect_tls_socket:342" level="ERR " number="0" thread="32076" time="99755.526"] - Connecting over TLS failed (sslv3 alert handshake failure).

Please find the attachment.
[datastore.zip](https://github.com/CESNET/netopeer/files/207720/datastore.zip)
[certs.zip](https://github.com/CESNET/netopeer/files/207721/certs.zip)

Regards
mukund

**Comment by michalvasko** [comment]
Hi Mukund,
you have gotten quite far and it seems your certificates and netopeer configuration are almost correct. But you are missing an exact understanding of how *cert-to-name* works, the entries there are wrong.

So, firstly, connected to the error netopeer is showing about unknown fingerprint algorithms, you need to look [here](https://tools.ietf.org/html/rfc7407#page-16)(the *tls-fingerprint* typedef) and then [here](https://tools.ietf.org/html/rfc5246#page-72)(the *HashAlgorithm* enum). In short, every fingerprint must begin with the idetification of the algorithm. You used SHA-1s in the **datastore.xml**, so you need to prefix both fingerprints with `02:` and they will be recognized.

Secondly, in the *cert-to-name* configuration in the **datastore.xml** you used entries with `name` set. That name value is used only in the `map-type` *specified*. I suggest you read at least [this](https://tools.ietf.org/html/rfc7589#section-7). To apply it all to your specific case, there are basically 2 right approaches you can choose from.

Generally speaking, the better approach would be to keep only the entry with the *ca.pem*. As I have already mentioned, remove the name value, it does not have any effect anyway. If you keep `map-type` of *subjectAltName*, what it means for the authentication is this: if any certificate in the client certificate chain (I hope you know what that is), going from the root CA to the peer certificate (in your case *ca.pem* is considered, then *client.crt*), is signed by *ca.pem* (this fingerprint is set in the CTN entry), then the username used for the NETCONF session will be the *Subject Alternative Name* of the certificate presented by the client (the one signed by *ca.pem*). I do not think *client.crt* has this extension value filled, so you should receive an error saying this.

Another approach is the simplest one, which is also used as an example, right after you install *netopeer* with TLS. You keep only the CTN entry with *client.crt* fingerprint, you set `map-type` to *specified* (with module prefix), and keep the `name` *client*. This will result in every client that have *client.crt* in their certificate chain to be identified as *client* (that wil be the username assigned to them).

This explanation is hardly exhaustive, but you should be able to understand what you did wrong and how to fix it. Also, the `id` of CTN entries represent their priority (order, in which they are considered), you should not use the same value for more entries.

Regards,
Michal

**Comment by mukundanaresh** [comment]
Thanks Michel for the right direction.It is working like a bullet train.
