### ISSUE TITLE
Netopeer starter: facing basic operation issues

### ISSUE THREAD

**Issue by xavierjosephh** [CESNET/netopeer#106]
hi, I am completely new to networking and to undertand the same I started with NETCONF and downloaded and installed Netopeet(netopeer-1.0.2.tar.gz). In the folder I do have a netopeer-agent and netopeer-fake-daemon. But apart from <get-config> i am unable to perform any other NETCONF operation using netopeer-cli. Ecah time I get the error: RPCError: the org.liberouter.netopeer is not provided by any .service files. If anyone could help me out it will be a great help. 
Also, as mentioned in some posts, my download has no netopeer-server named file. 
Installation process carried out:
./configure
make
make install

using centOS 5.0

**Comment by michalvasko** [comment]
Hi,
last packages we made was quite a long time ago, the one you downloaded is really old. Best would be to remove anything you installed from a package (netopeer, netopeer-cli, and libnetconf) and install all of it from master branches here on github (repositories *libnetconf* and *netopeer*).

Regards,
Michal

**Comment by sangeethakmw** [comment]
hi,
    I am trying to understand NETCONF protocol. I have installed netopeer successfully(as i believe). Bt I am having trouble connecting netopeer-cli with netopeer-server. The server however has started( i have made no changes in the /etc/ssh/sshd_config : multi-level server). Cud you give me the procedure to start the cli and connect it to server for further usage.

**Comment by rkrejci** [comment]
Hi, current netopeer does not follow the multi-level server architecture and `/etc/ssh/sshd_config` has nothing to do with netopeer.

Information about using cli can be found in its man page (being installed together with the cli or available in `doc` subdirectory) - your question is so generic that it's impossible to answer.
