### ISSUE TITLE
No device/data : Error

### ISSUE THREAD

**Issue by sangeethakmw** [CESNET/netopeer#108]
I am getting the following error whenever trying to do <edit-config> :
   <rpc-error>
         <error-type>application</error-type>
         <error-tag>operation-failed</error-tag>
         <error-severity>error</error-severity>
         <error-message>There is no device/data that could be effected</error-message>
    </rpc-error>
I checkd another post with the same error and tried as you suggested: netopeer-manager list
it showed : no module installed.

**Comment by rkrejci** [comment]
First, read how to format text on github. Second, your problem description is absolutely insufficient - what is the content of your edit-config? Probably you answered yourself - there is no module installed, so you will be able to modify only the internal data (NACM).
