### ISSUE TITLE
Unable to start the netopeer-server

### ISSUE THREAD

**Issue by xavierjosephh** [CESNET/netopeer#109]
I am unable to start the netopeer-server. When I give the command: netopeer-server -v 3 to check if it is initialized, I'm getting the below error:
 
netopeer-server[2988]: Datastore file /usr/local/etc/netopeer/modules.conf.d cannot be opened (Is a directory).
netopeer-server[2988]: Unable to set path to datastore of the 'turing-machine' transAPI module.
netopeer-server[2988]: Callback for path /A:netopeer/A:modules/A:module/A:enabled failed (1).
netopeer-server[2988]: Transapi calling callback /A:netopeer/A:modules/A:module/A:enabled with op REM.
netopeer-server[2988]: Updating XML tree after TransAPI callbacks
netopeer-server[2988]: Failed perform initial copy of startup to running.
netopeer-server[2988]: Device initialization of module Netopeer failed.
netopeer-server[2988]: Netopeer SSH cleanup.
netopeer-server[2988]: Netopeer cleanup.
netopeer-server[2988]: Starting necessary Netopeer plugin failed!
netopeer-server[2988]: NETCONF Call Home cleanup.

Can anyone please help me out? Thanks in advance.

**Comment by michalvasko** [comment]
Hi,
if you look at the first error, it is quite clear. You need to set the path to a module datastore file (in this case the module is *turing-machine* and its settings are in `/usr/local/etc/netopeer/modules.conf.d/turing-machine.xml`). Just point `repo/path` to a non-existing file, it will be created and *turing-machine* datastore contents stored there. You must have changed the path manually, because if you just `make install` the turing module from netopeer repository, it sets the path correctly.

Regards,
Michal

**Comment by keshava88** [comment]
@michalvasko  I am getting the same error even with a docker container
I am getting the below errors.

kbhatk@kbhatk-VirtualBox:~/tools/netopeer$ docker run -it --rm -p 8300:830 --name netopeer lpenz/netopeer
netopeer-server[1]: ncds_features_parse: no feature definitions found in data model ietf-inet-types.
netopeer-server[1]: ncds_features_parse: no feature definitions found in data model ietf-yang-types.
netopeer-server[1]: ncds_features_parse: no feature definitions found in data model ietf-netconf-monitoring.
netopeer-server[1]: ncds_features_parse: no feature definitions found in data model ietf-netconf-notifications.
netopeer-server[1]: ncds_features_parse: no feature definitions found in data model nc-notifications.
netopeer-server[1]: ncds_features_parse: no feature definitions found in data model notifications.
netopeer-server[1]: ncds_features_parse: no feature definitions found in data model ietf-netconf-with-defaults.
netopeer-server[1]: ncds_features_parse: no feature definitions found in data model ietf-netconf-acm.
netopeer-server[1]: Datastore ietf-netconf-acm initiated with ID 8.
netopeer-server[1]: Checking the default Events stream path //var/lib/libnetconf//streams/.
netopeer-server[1]: Adding augment model "/usr/etc/netopeer/cfgnetopeer/ietf-x509-cert-to-name.yin"
netopeer-server[1]: ncds_features_parse: no feature definitions found in data model ietf-x509-cert-to-name.
netopeer-server[1]: Adding static transapi "/usr/etc/netopeer/cfgnetopeer/ietf-netconf-server.yin"
netopeer-server[1]: "ssh" features in "ietf-netconf-server" module enabled.
netopeer-server[1]: "inbound-ssh" features in "ietf-netconf-server" module enabled.
netopeer-server[1]: "outbound-ssh" features in "ietf-netconf-server" module enabled.
netopeer-server[1]: Datastore file /usr/etc/netopeer/cfgnetopeer/datastore-server.xml does not exist, creating it.
netopeer-server[1]: Datastore file /usr/etc/netopeer/cfgnetopeer/datastore-server.xml was created.
netopeer-server[1]: Failed to parse the datastore (/usr/etc/netopeer/cfgnetopeer/datastore-server.xml).
netopeer-server[1]: File /usr/etc/netopeer/cfgnetopeer/datastore-server.xml was empty. Basic structure created.
netopeer-server[1]: Datastore ietf-netconf-server initiated with ID 1804289384.
netopeer-server[1]: Setting the default SSH configuration for the ietf-netconf-server module...
netopeer-server[1]: callback_srv_netconf_srv_listen_srv_port: SSH listening on the port 830
netopeer-server[1]: Adding static transapi "/usr/etc/netopeer/cfgnetopeer/netopeer-cfgnetopeer.yin"
netopeer-server[1]: "dynamic-modules" features in "netopeer-cfgnetopeer" module enabled.
netopeer-server[1]: "ssh" features in "netopeer-cfgnetopeer" module enabled.
netopeer-server[1]: Datastore netopeer-cfgnetopeer initiated with ID 846930887.
netopeer-server[1]: Setting the default configuration for the cfgnetopeer module...
netopeer-server[1]: Setting the default configuration for the cfgnetopeer module SSH...
netopeer-server[1]: Adding transapi "/usr/etc/netopeer/ietf-system/ietf-system.yin"
netopeer-server[1]: "timezone-name" features in "ietf-system" module enabled.
netopeer-server[1]: "authentication" features in "ietf-system" module enabled.
netopeer-server[1]: "local-users" features in "ietf-system" module enabled.
netopeer-server[1]: Datastore ietf-system initiated with ID 1681692778.
netopeer-server[1]: Saving configuration failed (No error)
netopeer-server[1]: Callback for path /A:system/A:dns-resolver failed (1).
netopeer-server[1]: Failed to set the hostname (Operation not permitted).
netopeer-server[1]: Reverting configuration changes via transAPI failed, configuration may be inconsistent.
netopeer-server[1]: Failed perform initial copy of startup to running.
netopeer-server[1]: Device initialization of module ietf-system failed.
netopeer-server[1]: Callback for path /A:netopeer/A:modules/A:module/A:enabled failed (1).
netopeer-server[1]: Failed perform initial copy of startup to running.
netopeer-server[1]: Device initialization of module Netopeer failed.
netopeer-server[1]: Netopeer SSH cleanup.
netopeer-server[1]: Netopeer cleanup.
netopeer-server[1]: Starting necessary Netopeer plugin failed!
netopeer-server[1]: NETCONF Call Home cleanup.

**Comment by michalvasko** [comment]
Hi,
please use [netopeer2](https://github.com/cesnet/netopeer2) instead of *netopeer*. We ended our support for this project so I will not investigate what exactly may have gone wrong in your case.

Regards,
Michal
