### ISSUE TITLE
First time user

### ISSUE THREAD

**Issue by sangeethakmw** [CESNET/netopeer#110]
Hi,
I am completely new to netopeer  and need a little guidance. I have installed netopeer in my VM  (fedora 20). and as client part I have NETCONFc. The problems I have are: 
-As root when i give the command-netopeer-server, my server starts and i am able to connect to it using NETCONFc, but I don't know how should I use or start the netopeer-cli.
-When I use NETCONF operations (get,get-config, etc) in the output i dont get any data as no module is installed (netopeer-manager list- no module installed). We have turing-machine in netopeer but I am unable to add this module. I tried using netopeer-manager add (seeing an example to add module) but when I do that my server doesn't start and instead throws me an error 
( cannot open /usr/local/etc/netopeer/modules.conf.d/turing-machine.xml (is a directory)). I know my way of adding this module has something wrong in it. 
It will be really helpful if anyone could guide me.

**Comment by michalvasko** [comment]
Hi,
netopeer-cli is a NETCONF client, just like NETCONFc, you can use it to connect to netopeer-server. The simples way of installing the turing-machine module is by calling `make install`, it will do everything for you. Nevertheless, you should always get some data, definitely as a reply to get. I don't know NETCONFc, so there may be some problem with it (you can easily check this if you start netopeer-server like `netopeer-server -v 3`, it will print all the messages it is sending. Still, we can help you only with problems with our software, netopeer-server or netopeer-cli.

Regards,
Michal

**Comment by sangeethakmw** [comment]
is there any sprcific command (like for server : netopeer-server) to start netopeer-cli?

**Comment by sangeethakmw** [comment]
And, I did as you said and have installed the turing-machine. Now when i do <get-config> i get an rpc reply but just with the tag (... <modules>  </modules>....) but no details in the turing-machine.

**Comment by michalvasko** [comment]
For your first question, what do you mean a specific command? If you install the CLI and have a correct PATH, you can start it the same way as netopeer-server (basic Linux knowledge).

It's impossible for me to help you with the second question... Did you start netopeer-server with `-v 3`? If you did not, then do it an then look at the output, did it advertise the `turing-machine` model? Does the `<rpc-reply>` match what your client printed out? Are you using netopeer-cli or NETCONFc?

I am sorry, but we don't really have time to teach you all the basics, you will have to learn most of it yourself.

Regards,
Michal

**Comment by sangeethakmw** [comment]
Thank you
