### ISSUE TITLE
Getting error "Failed user 'root' authentication attempt (#1)" from Netopeer

### ISSUE THREAD

**Issue by pnkjtr** [CESNET/netopeer#112]
Hi ,
I am running netopeer (latest version). I am able to build libnetconf and netopeer-server successfully.
i ran netopeer-server  and trying to connect to this server from netopeer-cli .

i am getting following error on netopeer-server:

etopeer-server[9512]: Received an SSH message "request-service" of subtype "ssh-userauth".
netopeer-server[9512]: Received an SSH message "request-auth" of subtype "none".
netopeer-server[9512]: Received an SSH message "request-auth" of subtype "password".
netopeer-server[9512]: User 'root' is not allowed to authenticate using a password.
netopeer-server[9512]: Failed user 'root' authentication attempt (#1).
netopeer-server[9512]: Received an SSH message "request-auth" of subtype "interactive".
netopeer-server[9512]: Failed to authenticate for too long, dropping client 'root'.

can some help me to understand, what I am missing here ?

thanks.
Pankaj

**Comment by michalvasko** [comment]
Hi Pankaj,
the error you see should be caused by your system user configuration. Try to use a different user that can actually be used for standard login or modify your user "root" that way.

Regards,
Michal

**Comment by elmiomar** [comment]
Hi,
I am having the same issue.
What do you mean by **system user configuration**? Should I create a user somewhere?

Thanks,
Omar

**Comment by chanfansang** [comment]
Hi,
I am having the same issue,too.
I worked the "docker run.." with the "root" 
What should I do for that?

Thx,
chanfan

**Comment by michalvasko** [comment]
Hi,
if you see exactly the same message then it is self-explaining, your system user `root` is configured to not allow logging with password. How to change it is a Linux issue, not *netopeer* one. Anyway, I suggest you stop using this old server, use [netopeer2](https://github.com/cesnet/netopeer2).

Regards,
Michal
