### ISSUE TITLE
configurate server but not work...

### ISSUE THREAD

**Issue by DuncanJr** [CESNET/netopeer#115]
Hi ,
    I already build libnetconf success, but when I configure netopeer-server something wrong .
Log as following :
# netopeer-master/server: ./configurate 
.....
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... no
configure: generating validation files...
/home/temp/netopeer-master/server/config/ietf-netconf-server.yang:335: error: bad value "inbound-ssh" (should be if-feature-expr)
/home/temp/netopeer-master/server/config/ietf-netconf-server.yang:350: error: bad value "outbound-ssh" (should be if-feature-expr)
/home/temp/netopeer-master/server/config/ietf-netconf-server.yang:387: error: bad value "inbound-tls" (should be if-feature-expr)
/home/temp/netopeer-master/server/config/ietf-netconf-server.yang:402: error: bad value "outbound-tls" (should be if-feature-expr)
/home/temp/netopeer-master/server/config/ietf-netconf-server.yang:410: error: bad value "tls-map-certificates" (should be if-feature-expr)
/home/temp/netopeer-master/server/config/ietf-netconf-server.yang:422: error: bad value "tls-map-pre-shared-keys" (should be if-feature-expr)
/home/temp/netopeer-master/server/config/ietf-netconf-server.yang:487: error: bad value "ssh" (should be if-feature-expr)
/home/temp/netopeer-master/server/config/ietf-netconf-server.yang:491: error: bad value "tls" (should be if-feature-expr)
Command 'pyang -p /home/temp/netopeer-master/server/config/ -f yin /home/netopeer-master/server/config/ietf-netconf-server.yang' failed (1)
configure: error: Generating validation files for ietf-netconf-server failed.

I try to configurate with --disable-ssh , but it seem like not going .... 
my OS: ubuntu 11.04 ,python version 1.6

Thank you for your reply.

**Comment by michalvasko** [comment]
Hi,
I have not seen this before, what is the version of your pyang (`pyang -v`)?

Regards,
Michal

**Comment by DuncanJr** [comment]
Hi Michal ,
    my pyang version is pyang 1.6

thanks

**Comment by michalvasko** [comment]
I cannot reproduce this on OpenSUSE, but I tried it with the latest pyang from its master branch, please try to update your pyang to the latest version. If it still does not work I will try it on Ubuntu, but your version is quite old, that may ultimately be the problem.

Regards,
Michal

**Comment by DuncanJr** [comment]
Hi Michal,
   OK ,but I sure 1.6 is latest version of pyang .  I will try other ubuntu os for newest .

Thank you.

**Comment by DuncanJr** [comment]
Hi Michal,
    I use ubuntu 15.10 , then it's work.  

Thank you
