### ISSUE TITLE
netopeer-server doesn't startup..

### ISSUE THREAD

**Issue by DuncanJr** [CESNET/netopeer#116]
Hi ,
     I run the netopeer-server . but it seem like no sock_listen , is my compile wrong?
Log as following : 
       # netoperr/server/ sudo ./netopeer-server -v 3 
        ......
      netopeer-server[1492]: Datastore netopeer-cfgnetopeer initiated with ID 846930887.
      netopeer-server[1492]: Setting the default configuration for the cfgnetopeer module...
      netopeer-server[1492]: Setting the default configuration for the cfgnetopeer module SSH...
      netopeer-server[1492]: Netopeer server successfully initialized.
      netopeer-server[1492]: sock_listen: could not bind "::0" port 830 (Address already in use)
      netopeer-server[1492]: Server is not listening on any address!

and I use # netopeer-master/cli$ ./netopeer-cli 

      netconf> connect 
      Hostname to connect to: localhost
      libnetconf ERROR: Starting the SSH session failed (Socket error: disconnected)
      connect: connecting to the localhost:830 as user "(null)" failed

Thank you for your reply

**Comment by michalvasko** [comment]
Hi,
the error is quite clear, you have another application (could be another instance of netopeer-server) that is listening on all interfaces on port 830. Quit that application or change its configuration to listen on another interface/port and netopeer-server will start properly.

Regards,
Michal
