### ISSUE TITLE
netopeer-cli can't edit/copy/delete-config

### ISSUE THREAD

**Issue by DuncanJr** [CESNET/netopeer#117]
Hi ,  
    When I connect to netopeer server , most of command I can use  but the edit/copy/delete-config has something.
Log as following: 
netconf> edit-config running 
readinput: Exec failed (No such file or directory).
libnetconf ERROR: Invalid configuration data for <edit-config> operation
edit-config: creating rpc request failed.

thank you for your reply

**Comment by rkrejci** [comment]
`netopeer-cli` is supposed to open editor for you to create `edit-config`'s data. Please try to use `editor` command to check what editor is currently set, eventually to set the editor you want to use. Alternatively, you can use `edit-config`'s `--config` option to specify file with the `edit-config`'s data.

**Comment by DuncanJr** [comment]
Hi rkrejci,
     I use editor and running-config are current using .  But I edit-config --config running , but it said 
edit-config: cannot access the file (No such file or directory) .  

    It needs to create the config before I run cli or server ? thanks for your reply

**Comment by rkrejci** [comment]
When you use the `--config` option, you are supposed to provide path to the file containing data for edit-config. Following command:
```
> edit-config --config running
```
is wrong, because cli is searching for a file named `running`.

**Comment by DuncanJr** [comment]
Hi rkrejci,
    Mmm... I don't know where is the config path .  Where is the default config path ? 

Thanks

**Comment by michalvasko** [comment]
Hi,
please just use `> edit-config -h`, you can see all the options there and how to use them. There is no default config path, I do not understand what you man by that, you can only specify a particular file with the <edit-config> configuration to be applied.

Regards,
Michal
