### ISSUE TITLE
Missing Netopeer configuration datastore (/etc/netopeer/cfgnetopeer/datastore.xml)

### ISSUE THREAD

**Issue by pradyp11** [CESNET/netopeer#118]
Hi,
  I'm new to netopeer . When i try to run 'make install' for Netopeer/TransAPI/Cfgsystem , it gives Missing Netopeer configuration datastore (/etc/netopeer/cfgnetopeer/datastore.xml). Is this any error and how can i rectify it.

**Comment by michalvasko** [comment]
Hi,
it cannot find the netopeer-server datastore, so my guess it you did not install it or something went wrong. cfgsystem is just a [transAPI](https://rawgit.com/CESNET/libnetconf/master/doc/doxygen/html/d9/d25/transapi.html) module for netopeer-server, it cannot be used separately.

**Comment by pradyp11** [comment]
Thank you. I reinstalled it now it does not show any statement missing
netopeer configurator datastore. But i don't see datastore file in
etc/Netopeer/cfgnetopeer.

**Comment by michalvasko** [comment]
Hi,
the datastore path will include any prefix you used when installing netopeer-server. If you did not modify it, it will be `/usr/local/etc/netopeer/cfgnetopeer/datastore.xml`. As long as you managed to install cfgsystem, it should all be correct.

Regards,
Michal

**Comment by pradyp11** [comment]
Thank you Michal.
