### ISSUE TITLE
datastore file fd corruption.

### ISSUE THREAD

**Issue by BanuPrakashReddy** [CESNET/netopeer#121]
Hi,

Randomly netopeer-server is hitting this problem, where edit-config on some datastore is failing wit the followin error:
           ERROR ("%s: truncate() of file %s failed (%s)", __func__, file_ds->path, strerror(errno));

When I tried to debug further, the file pointer which is present with the  "file" variable in "ncds_ds_file" structure is matching with some sockets fd.

I dont know how to reproduce this, randomly while running some regression with different rpcs, I am facing this problem.

On my client I have subscribed for notifications. I will doing continuous edit-config, close-session, connection establishment, so config-change notifications will always be flowing to client.

Does some one have suggestions about where the corruption could be happening.

Above error log is present in  file_sync(struct ncds_ds_file* file_ds) function in datastore_file.c of libnetconf.

Thanks,
Banu Prakash

**Comment by michalvasko** [comment]
Hi Banu,
I don't think we can help you based on this information, it is too general. Best would be if you could reproduce it or at least provide the actual error message.

Regards,
Michal

**Comment by BanuPrakashReddy** [comment]
Thanks Michal for quick reply.

I could not reproduce the issue. 

 I get the below error and edit-config fails:

"file_sync: truncate() of file /etc/netopeer/resources/resources_datastore.xml failed (Invalid argument)"

As far as I know,  the fd on which the file operation is happening, now belongs to some socket, that is why the truncate operation if failing.

-Banu Prakash

**Comment by michalvasko** [comment]
Hi Banu,
the problem is that the file descriptor is retrieved from the stored `FILE *` structure, which would imply there is something wrong with that file and without a use-case I cannot examine it. Maybe you can try that.

Regards,
Michal

**Comment by BanuPrakashReddy** [comment]
Hi Michal,

Found some leads which is resulting to the problem. 
Hope, my explanation is understandable :). 

Below are the details:

When netconf connection times out or netconf client gets killed abruptly, poll(ssh_channel_poll_timeout  ) throws TIMEDOUT error but before that libssh internally closing the socket.  Again the socket 'fd' is getting closed inside libnetconf at "client_free_ssh" inside client_main_thread.

This double closing the socket is causing the problem.

Here is the scenario when we could  see the error:       "file_sync: truncate() of file /etc/netopeer/resources/resources_datastore.xml failed (Invalid argument)"

Suppose the following happens  serially : 
1) communicating socket towards client is 15.
2) fd pointing to /etc/netopeer/resources/resources_datastore.xml  is 17
3) I have edited datastore /etc/netopeer/resources/resources_datastore.xml 
4) There is network outage b/w client and server

then, we see the error "Input channel error" because ssh_channel poll_timeout times out with error and nc_session_close gets called inside which recently edited file(here /etc/netopeer/resources_datastore.xml) gets reopened. Now because libssh already closed the socket with fd 15, the  reopened fd of the file "/etc/netopeer/resources_datastore.xml" will be 15.

While exiting from client_main_thread again fd=15 is getting closed inside "client_free_ssh ".
But still, fildescriptor inside ncds_ds_file structure corresponding to resources_datastore.xml 
points to 15.

Thanks,
Banu Prakash

**Comment by BanuPrakashReddy** [comment]
May be closing of client->sock inside client_free_ssh is not needed in any case.
Because, ssh_free would have already closed the socket even in normal disconnect case.

**Comment by michalvasko** [comment]
Hi Banu,
it seems you are correct, hope this fixed it for you.

Regards,
Michal

**Comment by BanuPrakashReddy** [comment]
Thanks Michal.
