### ISSUE TITLE
Replay notifications

### ISSUE THREAD

**Issue by alvinooo** [CESNET/netopeer#125]
I'm testing my implementation of a NETCONF client using the netopeer server. Right now I'm trying to change the running configuration of the server in order to replay notifications and print them out on the client. I am sending the following create-subscription message to the server, where I set startTime to a day before I run the program. According to the RFC 5277 that should replay all notifications from the day before the subscription was created.

`<?xml version="1.0" encoding="UTF-8"?>`
`<ns0:create-subscription xmlns:ns0="urn:ietf:params:xml:ns:netconf:notification:1.0">`
`<startTime>2016-08-11T14:14:57.478787Z</startTime>`
`</ns0:create-subscription>`

I create a new user, delete him, and immediately send the subscription from above to the server. I'm not getting any notifications for creating and deleting a user. But when I successfully create and delete a user after creating a subscription I get notifications for those events so I have no issue with generating notifications. I am subscribing to the NETCONF stream, which supports replay so is there a correct way to replay notifications from the netopeer server?

Thanks

Additional info:

I am starting the server on OS X like this:
docker run -it --rm -p 8300:830 --name netopeer netopeer

and connecting to it via user root and private key file netopeer/cli/certs/client.key

**Comment by rkrejci** [comment]
Your XML message seems wrong to me. The `startTime` element is in default namespace, which is none in your case, so the netopeer server does not see it. Then it is reasonable that no replay is performed.

**Comment by alvinooo** [comment]
And what is/where do I find the default namespace?

**Comment by rkrejci** [comment]
Please get familiar with XML - e.g. at [w3schools](http://www.w3schools.com/xml/xml_namespaces.asp).

**Comment by alvinooo** [comment]
Ok I mean what is the correct namespace to add to the startTime tag so netopeer will recognize it?

**Comment by rkrejci** [comment]
check [RFC 5277](https://tools.ietf.org/html/rfc5277#section-4)
