### ISSUE TITLE
Compiling for openwrt

### ISSUE THREAD

**Issue by abh15** [CESNET/netopeer#126]
Hi,
I have cloned the openwrt branch of netopeer, how do I cross compile it for Openwrt Chaos Calmer 15.05. I've already installed libnetconf on the target.

**Comment by petonagy** [comment]
Hi Abhishek!

Netopeer package is not a part of the OpenWrt repository. I'm sending you the Netopeer package for OpenWrt buildroot. You can copy it to the "openwrt/package/admin/netopeer" directory and compile/install the package.

Regards,
Peter
[netopeer.zip](https://github.com/CESNET/netopeer/files/442616/netopeer.zip)

**Comment by rohan-kharade** [comment]
hii Peter 

I followed same.Got error like **ietf-inet-type.yang** and **ietf-yang-types.yang** not found in /openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/netopeer/server/config. Hence I added those files. But getting some file format error.

![screenshot2](https://cloud.githubusercontent.com/assets/21260551/18118459/94a810de-6f72-11e6-8c97-53d7675558c0.png)
[added yang files.zip](https://github.com/CESNET/netopeer/files/446515/added.yang.files.zip)
![screenshot](https://cloud.githubusercontent.com/assets/21260551/18118191/ecb3a0ec-6f70-11e6-9cf1-5df6783418e8.png)

regards
Rohan

**Comment by abh15** [comment]
Make sure the source from which you are compiling is latest version of netopeer(openwrt branch). If you're compiling for chaos calmer branch of openwrt make sure all dependancies of netopeer/libnetconf have latest versions.
