### ISSUE TITLE
Problem regarding to the netopeer-server

### ISSUE THREAD

**Issue by jayganatra** [CESNET/netopeer#128]
Hi,
I am completely new to netopeer and need a little guidance. I am facing following error regarding to the netopeer-server installation.

checking for pkg-config... /usr/bin/pkg-config
checking for roff2html... no
checking for distro... ubuntu
configure: WARNING: Unsupported Linux distro "ubuntu", only RHEL and SUSE are fully supported.
checking pkg-config is at least version 0.9.0... yes
checking for uname... yes
checking for host architecture... x86_64
checking for lnctool... yes
checking python module: os... yes
checking python module: copy... yes
checking python module: curses... yes
checking python module: libxml2... yes
checking python module: subprocess... yes
checking python module: re... yes
checking python module: string... yes
checking python module: argparse... yes
checking python module: xml... yes
checking for rpmbuild... no
checking for clang... no
checking for llvm-gcc... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking for main in -lxml2... yes
checking for xml2-config... yes
checking for library containing ncntf_dispatch_receive... no
configure: error: libnetconf not found or not supporting notifications!

Can anyone guide me to solve this problem that i am facing ?
Thanks in advance.

**Comment by rohan-kharade** [comment]
@jayganatra
You need to install libnetconf first.Following link will help you to install libnetconf and other dependencies. 
https://github.com/CESNET/libnetconf/blob/master/INSTALL

**Comment by jayganatra** [comment]
First Thanks for the reply,
I followed that step but still i am getting the same error that configure: error: libnetconf not found or not supporting notifications!...

**Comment by rkrejci** [comment]
check that the linker is able to find the libnetconf in the path where you have installed it. If you have used the default path, it is `/usr/local/lib` - useful info can be found [here](http://stackoverflow.com/questions/4743233/is-usr-local-lib-searched-for-shared-libraries)

**Comment by jayganatra** [comment]
First Thanks for the reply,
When i run this command **ldconfig -p | grep libnetconf** it shows me the following output.
	libnetconf.so.0 (libc6,x86-64) => /usr/local/lib/libnetconf.so.0
	libnetconf.so (libc6,x86-64) => /usr/local/lib/libnetconf.so
I follow that steps that you mentioned but still i am getting this error.

**Comment by rkrejci** [comment]
can you attach the libnetconf's `config.log` file?

**Comment by jayganatra** [comment]
[config.txt](https://github.com/CESNET/netopeer/files/446530/config.txt)

**Comment by rkrejci** [comment]
hmm, it seems fine, could you also provide the config.log from the netopeer server?

**Comment by jayganatra** [comment]
[config.txt](https://github.com/CESNET/netopeer/files/446558/config.txt)

**Comment by rkrejci** [comment]
what is the output of the following command:
```
# ldd /usr/local/lib/libnetconf.so.0
```
From the log it seems that linker is unable to link libcurl (used by libnetconf)

**Comment by jayganatra** [comment]
Here i attached the file that contain the this command output.
[ldd.txt](https://github.com/CESNET/netopeer/files/446627/ldd.txt)

**Comment by rkrejci** [comment]
There's something wrong with your libcurl:
```
/usr/local/lib/libnetconf.so.0: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/local/lib/libnetconf.so.0)
```
as a workaround, you can switch off support for url: capability in libnetconf:
```
$ ./configure --disable-url
```
To solve the issue, try to google what ldd says. Fromt the very first sight, it seems to me that libnetconf was compiled against a different version of libcurl than which is being linked now. But I can be wrong.

**Comment by jayganatra** [comment]
Thanks for the suggestion the issue was related to the libcurl.
so i created make a link between files by this command.
sudo ln -fs /usr/lib/libcurl.so.4 /usr/local/lib/
and then configured without any error.

again thanks for your valuable suggestion.
