### ISSUE TITLE
URL as a source in edit-config operation.

### ISSUE THREAD

**Issue by jayganatra** [CESNET/netopeer#136]
Hi,
when i am performing edit config operation with URL as a source  it gives me error that 
" NETCONF error: operation-failed (application) - There is no device/data that could be affected. "
So, Can you provide some guidance for that error please.?  

Thanks in advance.

**Comment by michalvasko** [comment]
Hi,
it likely means that the edit-config content it downloads is not correct, there are only elements that the server does support (check namespaces).

Regards,
Michal

**Comment by jayganatra** [comment]
Hi, 
i check the edit-config content it seems ok to me this is the file which  i am passing as a url content.
[running.txt](https://github.com/CESNET/netopeer/files/529295/running.txt)

e.g
netconf>edit-config --url file:///PATH_TO_FILE
Select target datastore (running|startup|candidate|url:<dsturl>): running
NETCONF error: operation-failed (application) - There is no device/data that could be affected.

So can you please help me through that problem.
Thanks in advance.

**Comment by michalvasko** [comment]
Hi,
I believe the problem here is the top-level container `config`, netopeer-cli treats it as a part of the edit-config data. So, either remove it or use [netopeer2-cli](https://github.com/cesnet/netopeer2), which can handle this.

Regards,
Michal

**Comment by jayganatra** [comment]
Hi,
Thanks for the reply.I removed the the top level container config from file but i am still getting the same error.

**Comment by michalvasko** [comment]
Hi,
so I found the bug in libnetconf, it should work now, but the top-level `config` element must be present the way you had it.

Regards,
Michal

**Comment by jayganatra** [comment]
Hi,
Thanks for your valuable time and suggestion.It worked....

Regards,
jay
