### ISSUE TITLE
No corrective action (closing socket) at netopeer-cli when netopeer-server abruptly closed

### ISSUE THREAD

**Issue by akshay-raut** [CESNET/netopeer#137]
Hi,

Here I am seeing an issue at netopeer-cli.
In the below scenario:
1. Execute netconf-server
2. Establish Callhome connection between netopeer-server and netopeer-cli
3. Kill the netopeer-server without disconnecting the connection from netopeer-cli
4. Start netconf-server again
5. Try executing commands form netopeer-cli

With this scenario, netopeer-cli is unaware of closing of socket from netopeer-server side.
When tried executing commands from netopeer-cli, it realizes something wrong with the connection but still does not take corrective action (closing the socket).

netopeer-cli:
----------------------------------------------------------------------
netconf> get-config running
get-config: Unknown error occurred.
netconf> listen --login administrator
listen: already connected to 127.0.0.1.
netconf> disconnect
netconf> listen --login administrator
        Waiting 1 minute for call home on port 6666...
libnetconf ERROR: Authentication failed (Socket error: disconnected).
listen: receiving call Home failed.

Whereas, netopeer-server entered into a continuous loop.
netopeer-server logs:
--------------------------------------------------
netopeer-server[638]: Netopeer server successfully initialized.
netopeer-server[638]: SSH log: ssh_socket_pollcallback: Received POLLOUT in connecting state
netopeer-server[638]: SSH log: ssh_socket_unbuffered_write: Enabling POLLOUT for socket
netopeer-server[638]: SSH log: ssh_handle_key_exchange: ssh_handle_key_exchange: current state : 2
netopeer-server[638]: SSH log: ssh_handle_key_exchange: ssh_handle_key_exchange: current state : 2
netopeer-server[638]: SSH log: ssh_handle_key_exchange: ssh_handle_key_exchange: current state : 2
netopeer-server[638]: SSH log: ssh_handle_key_exchange: ssh_handle_key_exchange: current state : 2
netopeer-server[638]: SSH log: ssh_handle_key_exchange: ssh_handle_key_exchange: current state : 2

Thanks and Regards
AKSHAY RAUT

**Comment by michalvasko** [comment]
Hi Akshay,
server actually continues to work. The whole problem here is that even though the socket is closed it remains in the system for some additional time. During this time the socket is basically in a broken state and therefore cli and server are unable to communicate through it. If you restart cli, you can connect again and server retries its call home connection attempts on its own. Anyway, server suddenly disconnecting should be a rare situation.

Regards,
Michal

**Comment by tamilarasub** [comment]
Hello Michal,

netopeer-cli session is not getting terminated/closed when this client session is killed by server as a result of "kill-session" RPC operation from another client session. In this test OpenYuma's NETCONF server is used. Hope this behaviour is aligned with actual design.
It would be nice to disconnect the client session, to let user know about this server disconnect/session closure. Here is the log captured when user performs "get-config" RPC operation on the killed client session. 

netconf> get-config
Select target datastore (running|startup|candidate): running
get-config: Unknown error occurred.

Regards,
Tamilarasu.

**Comment by michalvasko** [comment]
Hi Tamilarasu,
you should have created a new issue as this one is one year old. In short, this is how *netopeer-cli* behaves and it will not be changed, *netopeer* support and development is discontinued. If you want a better behavior, use [netopeer2-cli](https://github.com/cesnet/netopeer2). Nevertheless, no specific message can be printed because there is no mechanism of sending it from a NETCONF server to a NETCONF client on a `kill-session`.

Regards,
Michal

**Comment by tamilarasub** [comment]
Thanks a lot for your quick response, and I am sorry for writing on the old ticket. Did this just to avoid  duplicate threads for the same/similar issue.
