### ISSUE TITLE
cannot execute lock/unlock from netopeer-cli

### ISSUE THREAD

**Issue by hsy68920** [CESNET/netopeer#138]
Before  executing "lock running", datastore.xml file was as below:
```
<?xml version="1.0"?>
<datastores xmlns="urn:cesnet:tmc:datastores:file">
  <running lock="" locktime="">
```

when executing "lock running", it reported error as below:
```
netconf> lock running
NETCONF error: lock-denied (protocol) - Access to the requested lock is denied because the lock is currently held by another entity. (session ID 3)
```
But the datastore.xml file was as below:
```
<?xml version="1.0"?>
<datastores xmlns="urn:cesnet:tmc:datastores:file">
  <running lock="3" locktime="2016-10-17T03:39:29Z">
```

Then I tried to execute "unlocking running", it reported error as below:
```
netconf> unlock running
NETCONF error: operation-failed (application) - Target datastore is not locked.
```
And the datastore.xml file was as below:
```
<?xml version="1.0"?>
<datastores xmlns="urn:cesnet:tmc:datastores:file">
  <running lock="" locktime="">
```

**Comment by michalvasko** [comment]
Hi,
I cannot really help you because you must have done something else that caused this error, because it works fine for me. What did you exactly do after server start? How many sessions did you establish, what commands did you execute on them, in what order?

Regards,
Michal

**Comment by hsy68920** [comment]
Hi, Michal,

Thanks for your reply!

After the server started, I just started the client and tried the lock/unlock function. Then I got the message. In fact, the lock/unlock commands did lock/unlock the datastore, but the error message is not expected.

Thanks
Shengyong

**Comment by michalvasko** [comment]
Hi Shengyong,
please try to stop the server (always with `Ctrl + C` (SIGINT), never send SIGKILL!), remove the datastore file manually, then start the server and try again, it should work.

Regards,
Michal

**Comment by hsy68920** [comment]
Hi, Michal,

I followed your suggestion and tried again. Seems it still did not work:

netconf> lock
main: command: lock
main: command start: lock

  Select target datastore (running|startup|candidate|url:<dsturl>): candidate
NETCONF error: lock-denied (protocol) - Candidate datastore not locked but already modified.

</rpc>

in datastore.xml:
  <candidate modified="false" lock="1" locktime="2016-10-18T07:29:36Z"/>

Thanks
Shengyong

**Comment by rkrejci** [comment]
try to call `discard-changes` command first, to fix the state of the candidate.

**Comment by hsy68920** [comment]
It woks.

Thanks
Shengyong
