### ISSUE TITLE
Unable to connect localhost using another account using publickey

### ISSUE THREAD

**Issue by miaofenk** [CESNET/netopeer#140]
Hi,

I have two accounts on one node, root and netconf. I have set the public keys of the two accounts into datastore.xml and they are showed on netopeer-configurator.
The auth key part in datastore.xml

> ```
>  <ssh>
>     <client-auth-keys>
>       <client-auth-key>
>         <path>/root/.ssh/id_rsa.pub</path>
>         <username>root</username>
>       </client-auth-key>
>       <client-auth-key>
>         <path>/home/netconf/.ssh/id_rsa.pub</path>
>         <username>netconf</username>
>       </client-auth-key>
>     </client-auth-keys>
>   </ssh>
> ```

However when I tried to connect localhost using netconf account, authentication always fails and has to enter password of netconf account. I have add auth key of netconf account into netopeer-cli config.

.netopeer/config.xml

```
  <authentication>
    <keys>
      <key-path>/home/netconf/.ssh/id_rsa</key-path>
    </keys>
  </authentication>
```

The netopeer-server log is as follow:

> netopeer-server[6170]: SSH log: ssh_server_curve25519_init: SSH_MSG_NEWKEYS sent
> netopeer-server[6170]: SSH log: ssh_socket_unbuffered_write: Enabling POLLOUT for socket
> netopeer-server[6170]: SSH log: ssh_packet_socket_callback: packet: read type 21 [len=12,padding=10,comp=1,payload=1]
> netopeer-server[6170]: SSH log: ssh_packet_process: Dispatching handler for packet type 21
> netopeer-server[6170]: SSH log: ssh_packet_newkeys: Received SSH_MSG_NEWKEYS
> netopeer-server[6170]: SSH log: ssh_packet_socket_callback: Processing 64 bytes left in socket buffer
> netopeer-server[6170]: SSH log: ssh_packet_socket_callback: packet: read type 5 [len=28,padding=10,comp=17,payload=17]
> netopeer-server[6170]: SSH log: ssh_packet_process: Dispatching handler for packet type 5
> netopeer-server[6170]: SSH log: ssh_packet_service_request: Received a SERVICE_REQUEST for service ssh-userauth
> netopeer-server[6170]: Received an SSH message "request-service" of subtype "ssh-userauth".
> netopeer-server[6170]: sshcb_msg: internal error (src/ssh/server_ssh.c:886)
> netopeer-server[6170]: SSH log: ssh_message_service_reply_success: Sending a SERVICE_ACCEPT for service ssh-userauth
> netopeer-server[6170]: SSH log: ssh_socket_unbuffered_write: Enabling POLLOUT for socket
> netopeer-server[6170]: SSH log: packet_send2: packet: wrote [len=28,padding=10,comp=17,payload=17]
> netopeer-server[6170]: SSH log: ssh_handle_key_exchange: ssh_handle_key_exchange: current state : 7
> netopeer-server[6170]: Received an SSH message "request-auth" of subtype "none".
> netopeer-server[6170]: Received an SSH message "request-auth" of subtype "publickey".
> netopeer-server[6170]: User 'netconf' tried to use an unknown (unauthorized) public key.
> netopeer-server[6170]: Failed user 'netconf' authentication attempt (#1).
> netopeer-server[6170]: Received an SSH message "request-auth" of subtype "password".
> netopeer-server[6170]: User 'netconf' authenticated.
> netopeer-server[6170]: Received an SSH message "request-channel-open" of subtype "session".
> netopeer-server[6170]: Received an SSH message "request-channel" of subtype "subsystem".
> netopeer-server[6170]: Writing message (session 1): <?xml version="1.0" encoding="UTF-8"?>

But, everything is ok when I use root account to connect.

> netopeer-server[6170]: SSH log: ssh_server_curve25519_init: SSH_MSG_KEX_ECDH_REPLY sent
> netopeer-server[6170]: SSH log: ssh_socket_unbuffered_write: Enabling POLLOUT for socket
> netopeer-server[6170]: SSH log: packet_send2: packet: wrote [len=604,padding=8,comp=595,payload=595]
> netopeer-server[6170]: SSH log: packet_send2: packet: wrote [len=12,padding=10,comp=1,payload=1]
> netopeer-server[6170]: SSH log: ssh_server_curve25519_init: SSH_MSG_NEWKEYS sent
> netopeer-server[6170]: SSH log: ssh_socket_unbuffered_write: Enabling POLLOUT for socket
> netopeer-server[6170]: SSH log: ssh_packet_socket_callback: packet: read type 21 [len=12,padding=10,comp=1,payload=1]
> netopeer-server[6170]: SSH log: ssh_packet_process: Dispatching handler for packet type 21
> netopeer-server[6170]: SSH log: ssh_packet_newkeys: Received SSH_MSG_NEWKEYS
> netopeer-server[6170]: SSH log: ssh_handle_key_exchange: ssh_handle_key_exchange: current state : 7
> netopeer-server[6170]: Received an SSH message "request-service" of subtype "ssh-userauth".
> netopeer-server[6170]: Received an SSH message "request-auth" of subtype "none".
> netopeer-server[6170]: Received an SSH message "request-auth" of subtype "publickey".
> netopeer-server[6170]: Received an SSH message "request-auth" of subtype "publickey".
> netopeer-server[6170]: User 'root' authenticated.
> netopeer-server[6170]: Received an SSH message "request-channel-open" of subtype "session".
> netopeer-server[6170]: Received an SSH message "request-channel" of subtype "subsystem".
> netopeer-server[6170]: Writing message (session 2): <?xml version="1.0" encoding="UTF-8"?>

Could you help to let me know what I did wrong that the authentication fails?

Thank you!

**Comment by miaofenk** [comment]
Hi michalvasko,

I have tested based on the latest master branch. The issue still exists but the role has exchanged. User "netconf" can connect without password but user "root" cannot.

The log when user "root" request-auth is posted:

> netopeer-server[12843]: Received an SSH message "request-service" of subtype "ssh-userauth".
> netopeer-server[12843]: sshcb_msg: internal error (src/ssh/server_ssh.c:886)
> netopeer-server[12843]: SSH log: ssh_message_service_reply_success: Sending a SERVICE_ACCEPT for service ssh-userauth
> netopeer-server[12843]: SSH log: ssh_socket_unbuffered_write: Enabling POLLOUT for socket
> netopeer-server[12843]: SSH log: packet_send2: packet: wrote [len=28,padding=10,comp=17,payload=17]
> netopeer-server[12843]: SSH log: ssh_handle_key_exchange: ssh_handle_key_exchange: current state : 7
> netopeer-server[12843]: Received an SSH message "request-auth" of subtype "none".
> netopeer-server[12843]: Received an SSH message "request-auth" of subtype "publickey".
> netopeer-server[12843]: auth_pubkey_compare_key: failed to import the public key "(null)" (Bad address)
> netopeer-server[12843]: User 'root' tried to use an unknown (unauthorized) public key.
> netopeer-server[12843]: Failed user 'root' authentication attempt (#1).
> netopeer-server[12843]: Received an SSH message "request-auth" of subtype "publickey".
> netopeer-server[12843]: User 'root' is not the username identified with the presented public key.
> netopeer-server[12843]: Failed user 'root' authentication attempt (#2).
> netopeer-server[12843]: Received an SSH message "request-auth" of subtype "password".
> netopeer-server[12843]: User 'root' authenticated.
> netopeer-server[12843]: Received an SSH message "request-channel-open" of subtype "session".
> netopeer-server[12843]: Received an SSH message "request-channel" of subtype "subsystem".
> netopeer-server[12843]: Writing message (session 3): <?xml version="1.0" encoding="UTF-8"?>

**Comment by michalvasko** [comment]
Hi,
I am sorry, the original code was more broken than I thought, but it should finally work now.

Regards,
Michal

**Comment by miaofenk** [comment]
Hi Michal,

Thanks for your time. The fix works this time!

Best Regards,
Miaofeng
