### ISSUE TITLE
validate with config option

### ISSUE THREAD

**Issue by jayganatra** [CESNET/netopeer#141]
Hi,
When i am performing validate operation with config option as a source it gives me error.
NETCONF error: operation-failed (application) - Datastore fails to validate (Expecting an element , got nothing)

Here in below the requested data on which i am performing validate operation,
```
<system xmlns="urn:ietf:params:xml:ns:yang:ietf-system">
   <hostname>ahcpu</hostname>
</system>
```

So, Can you provide some guidance for that error please.?

Thanks in advance.

**Comment by michalvasko** [comment]
Hi,
what does `status` command in the CLI shows? Is there a capability with `ietf-system` module?

Regards,
Michal

**Comment by jayganatra** [comment]
Hi Michal,
Yes, there is a capability with ietf-system module shown as a output of the status command.
The output of the status command shown in below attachment.
![capability](https://cloud.githubusercontent.com/assets/21236091/20551864/fe1a4fde-b16a-11e6-814c-ff0944c947b3.png)

**Comment by michalvasko** [comment]
Hi,
how did you install `ietf-system` module? Is it our transAPI `cfgsystem`? It seems like there are validation files missing, could you reinstall the module and paste the output here?

Regards,
Michal

**Comment by jayganatra** [comment]
Hi Michal,
Yes, it's the your transAPI cfgsystem module. As per your advice i reinstall the module and when i am validating the same data, I am getting the same error. Here, in below shown the output of the error message which i am getting at client side.

NETCONF error: operation-failed (application) - Datastore fails to validate (Expecting an element , got nothing)

And Here in below shown the output of error message i am getting at the server side.
![validate](https://cloud.githubusercontent.com/assets/21236091/20592178/21c53ccc-b252-11e6-8950-f9b58d2f2d42.png)
 
I run the server in verbose mode here it's output shown in below.
[netopeer-server_log.txt](https://github.com/CESNET/netopeer/files/610862/netopeer-server_log.txt)

In server-side error message validation failed at subdatastore 9. And when i run the server in verbose mode i saw the message that " Datastore ietf-netconf-acm initiated with ID 9 " . So is there any issue with NACM or requested data which i am validating ?

Thanks in advance for your valuable time and advice.

Regards,
Jay
