### ISSUE TITLE
The hex value can't be supported?

### ISSUE THREAD

**Issue by okmine123** [CESNET/netopeer#146]
In the YANG model, set the leaf type to be string, the netopeer-cli edit-config data "0xff" return ok.
But when set leaf type to be int64, uint32 etc. The netopeer-cli edit-config data "0xff" return failure. Shows:
"Datastore fails to validate (Extra element xxxx in interleav) "

But if change the value with decimal value with no "0x" header. config ok. 

I check the rfc6020-yang.pdf file. It says:

"Note that if a default value in a YANG module has a leading zero ("0"), it is interpreted as an octal number."

But the hex value should supported as example in the standard. Is that bug in the libnetconf?

**Comment by rkrejci** [comment]
it is not a bug - note that the RFC talks about the default value in YANG module. Values in XML documents (like edit-config request) are always interpreted as decimal numbers.

**Comment by okmine123** [comment]
Thank you very much rkrejci.
