### ISSUE TITLE
Multiple module yang in the same netopeer proyect

### ISSUE THREAD

**Issue by IgMart** [CESNET/netopeer#147]
Hello,

I'm trying to module my yang file in various modules (differents files), and I don't know exactly how to.
First of all, I import "import module1 { prefix prefixmodule1; }".
Then, I call a grouping of module1 with the directive "uses prefixmodule1:groupingmodule1"

It doesn't work. Is there any method to do it? or to use a container and not a grouping?
I also have seen that is possible to module it with includes, but I haven't found a guide.
Thanks everyone

**Comment by rkrejci** [comment]
Hi,
submodules (`include` statement) are not supported in libnetconf, but you can try [libyang](https://github.com/CESNET/libyang) and [libnetconf2](https://github.com/CESNET/libnetconf2) if you will need them. From your description it is not clear what you want to do, but reading [RFC 7950](https://tools.ietf.org/html/rfc7950) should help you. I can also recommend tutorials [at pyang docs](https://github.com/mbj4668/pyang/wiki/Documentation).
