### ISSUE TITLE
Best way to add custom function call to standard operation handlers e.g. <get-config>

### ISSUE THREAD

**Issue by kpeletidis** [CESNET/netopeer#149]
Hi,
I want to call my own code when netopeer-server receives e.g. a <get/> or <get-config> operation request from the client so that I can communicate with another piece of software when these operations occur.

My understanding so far is that I should add my call in np_ssh_client_netconf_rpc() in netopeer/server/src/ssh/server_ssh.c as separate cases for NC_OP_GET and NC_OP_GETCONFIG.

Is there a better way of doing this? For example, can I somehow avoid modifying the server code by having a netopeer module that gets notified when NC_OP_GET is received? Thank you.

Regards,
Kostas

**Comment by kpeletidis** [comment]
Any updates on this?

**Comment by michalvasko** [comment]
Hi Kostas,
your request will definitely not be implemented in *netopeer-server*, we only try to provide some basic support now (even that is being abandoned). If you migrate to *libnetconf2* and [*netopeer2-server*](https://github.com/cesnet/netopeer2), we may discuss an enhancement to enable this.

Regards,
Michal
