### ISSUE TITLE
Error while trying to run netopeer-server

### ISSUE THREAD

**Issue by icuetara** [CESNET/netopeer#154]
Hi all,

I have installed netconf following the steps in https://github.com/OpenOverlayRouter/oor/tree/master/netconf . Now I am trying to run the server but when I type "netopeer-server -v 3" I get all of this:

netopeer-server[21773]: Shared memory key: -4
netopeer-server[21773]: Shared memory ID: 1376267
netopeer-server[21773]: ncds_features_parse: no feature definitions found in data model ietf-inet-types.
netopeer-server[21773]: ncds_features_parse: no feature definitions found in data model ietf-yang-types.
netopeer-server[21773]: ncds_features_parse: no feature definitions found in data model ietf-netconf-monitoring.
netopeer-server[21773]: ncds_features_parse: no feature definitions found in data model ietf-netconf-notifications.
netopeer-server[21773]: ncds_features_parse: no feature definitions found in data model nc-notifications.
netopeer-server[21773]: ncds_features_parse: no feature definitions found in data model notifications.
netopeer-server[21773]: ncds_features_parse: no feature definitions found in data model ietf-netconf-with-defaults.
netopeer-server[21773]: ncds_features_parse: no feature definitions found in data model ietf-netconf-acm.
netopeer-server[21773]: ncds_set_validation: Relax NG validator set (//var/lib/libnetconf//ietf-netconf-acm-data.rng)
netopeer-server[21773]: ncds_set_validation: Schematron validator set (//var/lib/libnetconf//ietf-netconf-acm-schematron.xsl)
netopeer-server[21773]: Datastore ietf-netconf-acm initiated with ID 8.
netopeer-server[21773]: Checking the default Events stream path //var/lib/libnetconf//streams/.
netopeer-server[21773]: Adding augment model "/usr/local/etc/netopeer/cfgnetopeer/ietf-x509-cert-to-name.yin"
netopeer-server[21773]: ncds_features_parse: no feature definitions found in data model ietf-x509-cert-to-name.
netopeer-server[21773]: Adding static transapi "/usr/local/etc/netopeer/cfgnetopeer/ietf-netconf-server.yin"
netopeer-server[21773]: ncds_new_internal: Relax NG validator set (/usr/local/etc/netopeer/cfgnetopeer/ietf-netconf-server-data.rng)
netopeer-server[21773]: ncds_new_internal: Schematron validator set (/usr/local/etc/netopeer/cfgnetopeer/ietf-netconf-server-schematron.xsl)
netopeer-server[21773]: Datastore ietf-netconf-server initiated with ID 1804289384.
netopeer-server[21773]: Setting default configuration for ietf-netconf-server module
netopeer-server[21773]: callback_srv_netconf_srv_ssh_srv_listen_oneport: port 830
netopeer-server[21773]: callback_srv_netconf_srv_ssh_srv_listen: started sshd (PID 21774)
netopeer-server[21773]: Adding static transapi "/usr/local/etc/netopeer/cfgnetopeer/netopeer-cfgnetopeer.yin"
netopeer-server[21773]: ncds_features_parse: no feature definitions found in data model netopeer-cfgnetopeer.
netopeer-server[21773]: ncds_new_internal: Relax NG validator set (/usr/local/etc/netopeer/cfgnetopeer/netopeer-cfgnetopeer-data.rng)
netopeer-server[21773]: ncds_new_internal: Schematron validator set (/usr/local/etc/netopeer/cfgnetopeer/netopeer-cfgnetopeer-schematron.xsl)
netopeer-server[21773]: Datastore netopeer-cfgnetopeer initiated with ID 846930887.
netopeer-server[21773]: Transapi calling callback /A:netopeer/A:modules/A:module/A:enabled with op ADD.
netopeer-server[21773]: Transapi calling callback /A:netopeer/A:modules/A:module with op CHAIN | ADD.
netopeer-server[21773]: Adding augment model "/home/COTS/oor-1.1.1/netconf/iana-afn-safi.yin"
netopeer-server[21773]: ncds_features_parse: no feature definitions found in data model iana-afn-safi.
netopeer-server[21773]: Adding transapi "/home/maar/COTS/oor-1.1.1/netconf/lispsimple.yin"
netopeer-server[21773]: Unable to load shared library (/usr/local/lib/lispsimple.so: undefined symbol: lisp_addr_ip_afi).
netopeer-server[21773]: ncds_new_transapi: Failed to prepare transAPI structures.
netopeer-server[21773]: Invalid datastore.
netopeer-server[21773]: Unable to set path to datastore of the 'lispsimple' transAPI module.
netopeer-server[21773]: Callback for path /A:netopeer/A:modules/A:module failed (1).
netopeer-server[21773]: Transapi calling callback /A:netopeer/A:modules/A:module/A:enabled with op REM.
netopeer-server[21773]: Reverting configuration changes via transAPI failed, configuration may be inconsistent.
netopeer-server[21773]: Unable to revert executed changes: previous subtree version not found.
netopeer-server[21773]: Updating XML tree after TransAPI callbacks
netopeer-server[21773]: Failed perform initial copy of startup to running.
netopeer-server[21773]: Device initialization of module Netopeer failed.
netopeer-server[21773]: Netopeer module cleanup.
netopeer-server[21773]: Starting necessary Netopeer plugin failed!

Can anybody help me? Thanks in advance :)

**Comment by rkrejci** [comment]
The problem seems to be caused by `lispsimple.so`:
```
netopeer-server[21773]: Unable to load shared library (/usr/local/lib/lispsimple.so: undefined symbol: lisp_addr_ip_afi).
```
so you should probably consult the issue with the authors of the transAPI module.

**Comment by icuetara** [comment]
Thank you for your answer. Now I have other problem that seems to be because of the configuration permissions but I don't know how to fix it. Could you help me? The output when typing "netopeer-server -v 3" is the following:

netopeer-server[6501]: Shared memory key: -4
netopeer-server[6501]: Shared memory ID: 851977
netopeer-server[6501]: ncds_features_parse: no feature definitions found in data model ietf-inet-types.
netopeer-server[6501]: ncds_features_parse: no feature definitions found in data model ietf-yang-types.
netopeer-server[6501]: ncds_features_parse: no feature definitions found in data model ietf-netconf-monitoring.
netopeer-server[6501]: ncds_features_parse: no feature definitions found in data model ietf-netconf-notifications.
netopeer-server[6501]: ncds_features_parse: no feature definitions found in data model nc-notifications.
netopeer-server[6501]: ncds_features_parse: no feature definitions found in data model notifications.
netopeer-server[6501]: ncds_features_parse: no feature definitions found in data model ietf-netconf-with-defaults.
netopeer-server[6501]: ncds_features_parse: no feature definitions found in data model ietf-netconf-acm.
netopeer-server[6501]: ncds_set_validation: Relax NG validator set (//var/lib/libnetconf//ietf-netconf-acm-data.rng)
netopeer-server[6501]: ncds_set_validation: Schematron validator set (//var/lib/libnetconf//ietf-netconf-acm-schematron.xsl)
netopeer-server[6501]: Datastore ietf-netconf-acm initiated with ID 8.
netopeer-server[6501]: Checking the default Events stream path //var/lib/libnetconf//streams/.
netopeer-server[6501]: Unable to became primary owner of the org.liberouter.netopeer.server
netopeer-server[6501]: Communication subsystem not initiated.


Thanks in advance

**Comment by rkrejci** [comment]
I'm not going to answer two different issues in one thread. Please open a new issue with the descriptive name. Inserting multiple issues into a single thread makes it unreadable/unsearchable for others.

**Comment by iraponomareva** [comment]
excuse me, did you get an answer to your question?
Thank you for your answer. Now I have other problem that seems to be because of the configuration permissions but I don't know how to fix it. Could you help me? The output when typing "netopeer-server -v 3" is the following:

netopeer-server[6501]: Shared memory key: -4
netopeer-server[6501]: Shared memory ID: 851977
netopeer-server[6501]: ncds_features_parse: no feature definitions found in data model ietf-inet-types.
netopeer-server[6501]: ncds_features_parse: no feature definitions found in data model ietf-yang-types.
netopeer-server[6501]: ncds_features_parse: no feature definitions found in data model ietf-netconf-monitoring.
netopeer-server[6501]: ncds_features_parse: no feature definitions found in data model ietf-netconf-notifications.
netopeer-server[6501]: ncds_features_parse: no feature definitions found in data model nc-notifications.
netopeer-server[6501]: ncds_features_parse: no feature definitions found in data model notifications.
netopeer-server[6501]: ncds_features_parse: no feature definitions found in data model ietf-netconf-with-defaults.
netopeer-server[6501]: ncds_features_parse: no feature definitions found in data model ietf-netconf-acm.
netopeer-server[6501]: ncds_set_validation: Relax NG validator set (//var/lib/libnetconf//ietf-netconf-acm-data.rng)
netopeer-server[6501]: ncds_set_validation: Schematron validator set (//var/lib/libnetconf//ietf-netconf-acm-schematron.xsl)
netopeer-server[6501]: Datastore ietf-netconf-acm initiated with ID 8.
netopeer-server[6501]: Checking the default Events stream path //var/lib/libnetconf//streams/.
netopeer-server[6501]: Unable to became primary owner of the org.liberouter.netopeer.server
netopeer-server[6501]: Communication subsystem not initiated.

I have the same error with netopeer-server

**Comment by michalvasko** [comment]
Please do not use *netopeer*, it is completely obsolete. There is [*netopeer2*](https://github.com/cesnet/netopeer2) that is current.

**Comment by iraponomareva** [comment]
I am working with the lispsimple module, will there be any problems interacting with netopeer2?

**Comment by michalvasko** [comment]
I have no idea what is `lispsimple` so I cannot answer.
