### ISSUE TITLE
Unable to became primary owner of the org.liberouter.netopeer.server

### ISSUE THREAD

**Issue by icuetara** [CESNET/netopeer#155]
Hi all,

While triying to run netopeer-server I get the following error:

netopeer-server[6501]: Shared memory key: -4
netopeer-server[6501]: Shared memory ID: 851977
netopeer-server[6501]: ncds_features_parse: no feature definitions found in data model ietf-inet-types.
netopeer-server[6501]: ncds_features_parse: no feature definitions found in data model ietf-yang-types.
netopeer-server[6501]: ncds_features_parse: no feature definitions found in data model ietf-netconf-monitoring.
netopeer-server[6501]: ncds_features_parse: no feature definitions found in data model ietf-netconf-notifications.
netopeer-server[6501]: ncds_features_parse: no feature definitions found in data model nc-notifications.
netopeer-server[6501]: ncds_features_parse: no feature definitions found in data model notifications.
netopeer-server[6501]: ncds_features_parse: no feature definitions found in data model ietf-netconf-with-defaults.
netopeer-server[6501]: ncds_features_parse: no feature definitions found in data model ietf-netconf-acm.
netopeer-server[6501]: ncds_set_validation: Relax NG validator set (//var/lib/libnetconf//ietf-netconf-acm-data.rng)
netopeer-server[6501]: ncds_set_validation: Schematron validator set (//var/lib/libnetconf//ietf-netconf-acm-schematron.xsl)
netopeer-server[6501]: Datastore ietf-netconf-acm initiated with ID 8.
netopeer-server[6501]: Checking the default Events stream path //var/lib/libnetconf//streams/.
netopeer-server[6501]: Unable to became primary owner of the org.liberouter.netopeer.server
netopeer-server[6501]: Communication subsystem not initiated.

Could anybody help me?? Thanks in advance :)

**Comment by rkrejci** [comment]
Next time, please also provide information that you are not on master branch. The issue is connected with D-Bus communication (present in 0.9.x branch). There are 2 possible reasons:
1. you already have running netopeer-server instance, only one instance of the server is allowed
2. you don't have a permission to run it, check the D-Bus section in the server's [README](https://github.com/CESNET/netopeer/blob/libnetconf-0.9.x/server/README)
