### ISSUE TITLE
Mininet cooperation

### ISSUE THREAD

**Issue by aljer-priv** [CESNET/netopeer#157]
Hi all,
I am working on a project in which I have to use NETCONF server to collect data about network emulted in mininet environment. I have to use specific YANG data model (te-topology). I know how to implement custom model on Netopeer server, but I don't know if there is any possibility to connect Netopeer with mininet... Could you give me any advices for this issue? Is there any possibility to do that?

I would be extremaly grateful for any advice.
Best regards, 
Ola

**Comment by michalvasko** [comment]
Hi Ola,
I have zero experience with *mininet* so I cannot really help you. I presume the virtual network can be connected to using an interface on the host machine so I guess that is your entry point (what exactly do you mean by *connect Netopeer with mininet*?). However, we do not support *netopeer-server* anymore, so please use [netopeer2](https://github.com/cesnet/netopeer2) if you can.

Regards,
Michal

**Comment by aljer-priv** [comment]
Hi Michal,
I mean if it is possible to collect data from switches running in emulated network. 
Could you maybe give me some outline, how the Netopeer server can impact on other devices? How it works that making changes in database cause changes in devices working?

Regards, 
Ola

**Comment by michalvasko** [comment]
*netopeer* is simply a NETCONF server implementation, so it will not collect any data, strictly speaking. What it does is remote configuration of devices using transAPI modules. I am not sure what you are asking, but that is the way netopeer *impacts other devices*, you must write a transAPI module for them and then, based on the NETCONF configuration datastore changes the device will change its behavior (it is up to you to define exactly how).

Regards,
Michal

**Comment by aljer-priv** [comment]
Thanks for the explanation. I have one more question: where this transAPI modules have to be implemented? On the server or in a device which we want to control?

Regards,
Ola

**Comment by michalvasko** [comment]
Hi Ola,
they have to be implemented as a shared library for the **server** (basics [here](https://rawgit.com/CESNET/libnetconf/master/doc/doxygen/html/d9/d25/transapi.html)) and they should communicate somehow with the **device** to make it change its configuration and behavior.

Regards,
Michal

**Comment by aljer-priv** [comment]
OK, thanks for all answears. They are very helpful for me.

Regards,
Ola
