### ISSUE TITLE
problems when start multiple netopeer servers daemon instances on one linux machine

### ISSUE THREAD

**Issue by LilyCuili** [CESNET/netopeer#158]
Hello,
reference issue49,I  install multi netopeer server instances.
I met with a problem when  install multi netopeer server instances.
under path ../netopeer/server
first I install one netopeer server as below:
./configure --sysconfdir=/etc/netopeer_1 --prefix=/usr/local/netopeer_1
make
make install

and then I install another one:
./configure --sysconfdir=/etc/netopeer_2 --prefix=/usr/local/netopeer_2
make
make install

now I the issue is that when I start /usr/local/netopeer_2/bin/netopeer-server -d
when I start netconf client by ssh command,it will read datastore-server.xml under path :
/etc/netopeer_1/netopeer/cfgnetopeer
not /etc/netopeer_2/netopeer/cfgnetopeer

**Comment by LilyCuili** [comment]
I attached the netopeer server's log when start /usr/local/netopeer_2/bin/netopeer-server -d
from the log can see it find some files under
/etc/netopeer_1/netopeer/cfgnetopeer
I can't find the reason

**Comment by LilyCuili** [comment]
cuili@cuili-H81M-DS2-D:/usr/local/netopeer_3/bin$ sudo ./netopeer-server -v3
netopeer-server[2641]: Shared memory location: /dev/shm/libnetconfshm
netopeer-server[2641]: Shared memory file libnetconfshm already exists - opening
netopeer-server[2641]: POSIX SHM File Descriptor: 4 (600B).
netopeer-server[2641]: ncds_features_parse: no feature definitions found in data model ietf-inet-types.
netopeer-server[2641]: ncds_features_parse: no feature definitions found in data model ietf-yang-types.
netopeer-server[2641]: ncds_features_parse: no feature definitions found in data model ietf-netconf-monitoring.
netopeer-server[2641]: ncds_features_parse: no feature definitions found in data model ietf-netconf-notifications.
netopeer-server[2641]: ncds_features_parse: no feature definitions found in data model nc-notifications.
netopeer-server[2641]: ncds_features_parse: no feature definitions found in data model notifications.
netopeer-server[2641]: ncds_features_parse: no feature definitions found in data model libnetconf-notifications.
netopeer-server[2641]: ncds_features_parse: no feature definitions found in data model ietf-netconf-with-defaults.
netopeer-server[2641]: ncds_features_parse: no feature definitions found in data model ietf-netconf-acm.
netopeer-server[2641]: ncds_set_validation: Relax NG validator set (//var/lib/libnetconf//ietf-netconf-acm-config.rng)
netopeer-server[2641]: ncds_set_validation: Schematron validator set (//var/lib/libnetconf//ietf-netconf-acm-schematron.xsl)
netopeer-server[2641]: Datastore ietf-netconf-acm initiated with ID 9.
netopeer-server[2641]: Checking the default Events stream path //var/lib/libnetconf//streams/.
netopeer-server[2641]: Reading configuration for NETCONF-server module failed
netopeer-server[2641]: Starting necessary NETCONF server plugin failed!
cuili@cuili-H81M-DS2-D:/usr/local/netopeer_3/bin$ ./netopeer-server -d
cuili@cuili-H81M-DS2-D:/usr/local/netopeer_3/bin$ sudo ./netopeer-server -v3
netopeer-server[2683]: Shared memory location: /dev/shm/libnetconfshm
netopeer-server[2683]: Shared memory file libnetconfshm already exists - opening
netopeer-server[2683]: POSIX SHM File Descriptor: 4 (600B).
netopeer-server[2683]: ncds_features_parse: no feature definitions found in data model ietf-inet-types.
netopeer-server[2683]: ncds_features_parse: no feature definitions found in data model ietf-yang-types.
netopeer-server[2683]: ncds_features_parse: no feature definitions found in data model ietf-netconf-monitoring.
netopeer-server[2683]: ncds_features_parse: no feature definitions found in data model ietf-netconf-notifications.
netopeer-server[2683]: ncds_features_parse: no feature definitions found in data model nc-notifications.
netopeer-server[2683]: ncds_features_parse: no feature definitions found in data model notifications.
netopeer-server[2683]: ncds_features_parse: no feature definitions found in data model libnetconf-notifications.
netopeer-server[2683]: ncds_features_parse: no feature definitions found in data model ietf-netconf-with-defaults.
netopeer-server[2683]: ncds_features_parse: no feature definitions found in data model ietf-netconf-acm.
netopeer-server[2683]: ncds_set_validation: Relax NG validator set (//var/lib/libnetconf//ietf-netconf-acm-config.rng)
netopeer-server[2683]: ncds_set_validation: Schematron validator set (//var/lib/libnetconf//ietf-netconf-acm-schematron.xsl)
netopeer-server[2683]: Datastore ietf-netconf-acm initiated with ID 9.
netopeer-server[2683]: Checking the default Events stream path //var/lib/libnetconf//streams/.
netopeer-server[2683]: Adding augment model "/etc/netopeer_1/netopeer/cfgnetopeer/ietf-x509-cert-to-name.yin"
netopeer-server[2683]: ncds_features_parse: no feature definitions found in data model ietf-x509-cert-to-name.
netopeer-server[2683]: Adding static transapi "/etc/netopeer_1/netopeer/cfgnetopeer/ietf-netconf-server.yin"
netopeer-server[2683]: ncds_new_internal: Relax NG validator set (/etc/netopeer_1/netopeer/cfgnetopeer/ietf-netconf-server-config.rng)
netopeer-server[2683]: ncds_new_internal: Schematron validator set (/etc/netopeer_1/netopeer/cfgnetopeer/ietf-netconf-server-schematron.xsl)
netopeer-server[2683]: "ssh" features in "ietf-netconf-server" module enabled.
netopeer-server[2683]: "inbound-ssh" features in "ietf-netconf-server" module enabled.
netopeer-server[2683]: "outbound-ssh" features in "ietf-netconf-server" module enabled.
netopeer-server[2683]: Datastore ietf-netconf-server initiated with ID 1804289384.
netopeer-server[2683]: Setting the default SSH configuration for the ietf-netconf-server module...
netopeer-server[2683]: callback_srv_netconf_srv_listen_srv_port: SSH listening on the port 830
netopeer-server[2683]: Transapi calling callback /A:netconf/A:ssh/A:listen/A:port with op REM.
netopeer-server[2683]: callback_srv_netconf_srv_listen_srv_port: SSH stopped listening on the port 830
netopeer-server[2683]: Transapi calling callback /A:netconf/A:ssh/A:listen/A:interface with op ADD.
netopeer-server[2683]: callback_srv_netconf_srv_listen_srv_interface: SSH listening on the address 172.16.75.143:831
netopeer-server[2683]: Adding static transapi "/etc/netopeer_1/netopeer/cfgnetopeer/netopeer-cfgnetopeer.yin"
netopeer-server[2683]: ncds_new_internal: Relax NG validator set (/etc/netopeer_1/netopeer/cfgnetopeer/netopeer-cfgnetopeer-config.rng)
netopeer-server[2683]: ncds_new_internal: Schematron validator set (/etc/netopeer_1/netopeer/cfgnetopeer/netopeer-cfgnetopeer-schematron.xsl)
netopeer-server[2683]: "dynamic-modules" features in "netopeer-cfgnetopeer" module enabled.
netopeer-server[2683]: "ssh" features in "netopeer-cfgnetopeer" module enabled.
netopeer-server[2683]: Datastore netopeer-cfgnetopeer initiated with ID 846930887.
netopeer-server[2683]: Setting the default configuration for the cfgnetopeer module...
netopeer-server[2683]: Setting the default configuration for the cfgnetopeer module SSH...
netopeer-server[2683]: Netopeer server successfully initialized.

**Comment by michalvasko** [comment]
Hi,
it seems you installed it correctly, so it should have worked. Still, I have never tried having 2 separate *netopeer-server* instances installed on one machine, so there may be some problem I am not aware of. Also, it is not really the intended use, do you really need to have 2 instances? You can easily configure the server to listen on more interfaces.

Nevertheless, this *netopeer* is not supported anymore, please use [netopeer2](https://github.com/cesnet/netopeer2) if you can.

Regards,
Michal

**Comment by LilyCuili** [comment]
Hi Michal,
thanks for your quick reply.
I have find the root cause.
I 'make clean' but failed,then I ignore it to configure next.
I should 'make clean' before ./configure next netopeer  server.
now it works well.thanks
