### ISSUE TITLE
RESTCONF support

### ISSUE THREAD

**Issue by EIC-JayGanatra** [CESNET/netopeer#159]
Do this project supports has support for RESTCONF protocol?

Best Regards
Jay Ganatra

**Comment by rkrejci** [comment]
Hi, there is an experimental implementation in `restconf-impl` branch. However, it's old and no more supported. The following genration of the project ([Netopeer2](https://github.com/CESNET/Netopeer2)) does not support RESTCONF.

**Comment by EIC-JayGanatra** [comment]
Hi , Thanks for your valuable suggestions. i just want to ask that can i use restconf-impl branch for further RESTCONF development ?. Means Is it has full support of RESTCONF or just the basic functionality of RESTCONF..? 

Best Regards
Jay Ganatra

**Comment by rkrejci** [comment]
Probably just some core functionality and note that because it is quite old (3 years), it does not reflect any of the specification changes after that. I guess that there is quite a lot of work on that and because instead of Netopeer, we work on/supports its second generation, Netopeer2.

**Comment by EIC-JayGanatra** [comment]
Hi Radek,
Thanks for your advice. I just want to ask that when i can expect the RESTCONF support with neopeer2 ?. And Do you have any suggestion for any opensource RESTCONF Implementation available in market for development ? 

Sorry for the trouble i am just new to the RESTCONF .... 

Best Regards
Jay Ganatra

**Comment by rkrejci** [comment]
Currently, we don't have any specific plan regarding RESTCONF in Netopeer2. If you are fine with Python, there is [JetConf](https://github.com/CZ-NIC/jetconf).

**Comment by AmitGondaliya** [comment]
Hello Radek,

does  the branch "restconf-impl"  for RESTCONF is RFC 8040 compliance?

Thanks 
Amit Gondaliya

**Comment by rkrejci** [comment]
It was already answered: 't is quite old (3 years), it does not reflect any of the specification changes after that'
