### ISSUE TITLE
Can netopeer run in CentOS7-64?

### ISSUE THREAD

**Issue by UnknowSelf** [CESNET/netopeer#160]
I use netopeer-server run in centos7-64. ODL connect the netopeer-server success, then I send a edit-config message, the transAPI return success and netopeer-server core-dump.

**Comment by michalvasko** [comment]
Hi,
*netopeer-server* support has finished, please use [netopeer2-server](https://github.com/cesnet/netopeer2) instead.

Regards,
Michal
