### ISSUE TITLE
the branch restconf-impl is RFC compliance

### ISSUE THREAD

**Issue by AmitGondaliya** [CESNET/netopeer#162]
does the branch "restconf-impl" for RESTCONF is RFC 8040 compliance?

Thanks
Amit Gondaliya

**Comment by rkrejci** [comment]
not tested, I suppose it's not compliant

**Comment by AmitGondaliya** [comment]
Hello,

Thanks for the reply, 
If we use the branch "restconf-impl", will NETCONF and RESTCONF work parallel?

thanks
Amit Gondaliya

**Comment by rkrejci** [comment]
not sure (it's too long and I did a lot of other and similar work), but probably yes. Anyway, it was created as a [thesis](https://is.muni.cz/th/374324/fi_m/thesis.pdf), so you can try to read it to get more (background) information about the implementation.
