### ISSUE TITLE
how to build netconf client

### ISSUE THREAD

**Issue by shaqianqing** [CESNET/netopeer#164]
Hi
    I just begin to study netconf,and want to test netconf client and server,I see netopeer is netconf server,and I want to know how to bulid a netconf client,thanks!

**Comment by michalvasko** [comment]
Hi,
a NETCONF client example implementation can be found in `netopeer/cli`. However, please use [netopeer2](https://github.com/cesnet/netopeer2) if you can, this one is not supported anymore.

Regards,
Michal

**Comment by shaqianqing** [comment]
I have found it,thanks very much!
