### ISSUE TITLE
Compilation of sysrepo/examples/ failing

### ISSUE THREAD

**Issue by Ravi-t** [CESNET/netopeer#169]
Hello,
I am trying to build in sysrepo/examples directory but getting below errors, please let me know how to fix these
[root@localhost build]# cd sysrepo/examples/build
[root@localhost build]# cmake ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at plugins/CMakeLists.txt:11 (install):
install TARGETS given no LIBRARY DESTINATION for shared library target
"turing-machine".

CMake Error at CMakeLists.txt:49 (EXEC_AT_INSTALL_TIME):
Unknown CMake command "EXEC_AT_INSTALL_TIME".
Call Stack (most recent call first):
CMakeLists.txt:52 (INSTALL_EXAMPLE_YANG)

CMake Warning (dev) in CMakeLists.txt:
No cmake_minimum_required command is present. A line of code such as

cmake_minimum_required(VERSION 2.8)
should be added at the top of the file. The version specified may be lower
if you wish to support older CMake versions for this project. For more
information run "cmake --help-policy CMP0000".
This warning is for project developers. Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!

Regards,
Ravi

**Comment by michalvasko** [comment]
Hi Ravi,
I have not noticed before but please create issues in the correct projects. This one should have been created in the [sysrepo](https://github.com/sysrepo/sysrepo) project.

Anyway, you are not supposed to  build the examples separately, just build *sysrepo* with `BUILD_EXAMPLES` set to `ON` (is by default) and the examples will be built.

Regards,
Michal

**Comment by Ravi-t** [comment]
Thanks Michal
