### ISSUE TITLE
NETCONF error：operation-failed (application) - Some unspecified error occurred.

### ISSUE THREAD

**Issue by zhangk90** [CESNET/netopeer#170]
hi sir,
When I execute the edit-config  --config to set config on netopeer-cli, return this error
![image](https://user-images.githubusercontent.com/35092659/38673084-c580b07c-3e82-11e8-9b63-134fd79e9403.png)
use netopeer-server -v 3 display this

netopeer-server[5726]: Compacting edit-config operations failed.
netopeer-server[5726]: Writing message (session 1): <?xml version="1.0" encoding="UTF-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="3">
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message>Some unspecified error occurred.</error-message>
  </rpc-error>
</rpc-reply>

xml：
_<?xml_ version="1.0" encoding="UTF-8"?>
<public_ xmlns="urn:public:params:xml:ns:yang:public">
    <bussunits_infos xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
        <bussunits_info xc:operation="add">
            <bussunits_id>110</bussunits_id>
            <bussunits_type>bsu</bussunits_type>
            <bussunits_dbname>bsu1.db</bussunits_dbname>
            <bussunits_ip>192.168.11.11</bussunits_ip>
            <bussunits_port>9876</bussunits_port>
        </bussunits_info>
    </bussunits_infos>
</public>

yang：
module public {
  namespace "urn:public:params:xml:ns:yang:public";
  prefix "public";

  container bussunits_infos {
    list bussuntis_info {
        key bussunits_id;
        leaf bussunits_id{
            type uint16{
                range "1..65534";
                }
        }
        leaf bussunits_type{
            type string{
                length "0..6";
                }
        }
        leaf bussunits_dbname{
            type string{
                length "1..32";
                }
        }
        leaf bussunits_ip{
            type string{
                length "1..16";
                }
        }
        leaf bussunits_port{
            type uint16{
                range "1..65534";
                }
        }
    }
  }
}

Please forgive my English,Any answer would be very much appreciated.
Thanks！

**Comment by rkrejci** [comment]
Hi, edit-config's operation `add` is not defined, your edit-config request is invalid.

Consider using [Netopeer2](https://github.com/CESNET/Netopeer2) which should handle these errors much better. Netopeer is no more supported.

**Comment by zhangk90** [comment]
It woks.

Thanks
