### ISSUE TITLE
Netopeer-server can not work properly

### ISSUE THREAD

**Issue by tonycwwu** [CESNET/netopeer#172]
Hi,

I have this problem with the netopeer-server when I use the netconf client connect to netoserver.
The netopeer-server installed in Ubuntu 16.04-64 bit.
The following output is the message when I execute #sudo netopeer-server -v3 (show "core dumped" finally), please help me to solve this problem, thank you

netopeer-server[62280]: Shared memory location: /dev/shm/libnetconfshm
netopeer-server[62280]: Shared memory file libnetconfshm already exists - opening
netopeer-server[62280]: POSIX SHM File Descriptor: 5 (600B).
netopeer-server[62280]: ncds_features_parse: no feature definitions found in data model ietf-inet-types.
netopeer-server[62280]: ncds_features_parse: no feature definitions found in data model ietf-yang-types.
netopeer-server[62280]: ncds_features_parse: no feature definitions found in data model ietf-netconf-monitoring.
netopeer-server[62280]: ncds_features_parse: no feature definitions found in data model ietf-netconf-notifications.
netopeer-server[62280]: ncds_features_parse: no feature definitions found in data model nc-notifications.
netopeer-server[62280]: ncds_features_parse: no feature definitions found in data model notifications.
netopeer-server[62280]: ncds_features_parse: no feature definitions found in data model libnetconf-notifications.
netopeer-server[62280]: ncds_features_parse: no feature definitions found in data model ietf-netconf-with-defaults.
netopeer-server[62280]: ncds_features_parse: no feature definitions found in data model ietf-netconf-acm.
netopeer-server[62280]: ncds_set_validation: Relax NG validator set (//var/lib/libnetconf//ietf-netconf-acm-config.rng)
netopeer-server[62280]: ncds_set_validation: Schematron validator set (//var/lib/libnetconf//ietf-netconf-acm-schematron.xsl)
netopeer-server[62280]: Datastore ietf-netconf-acm initiated with ID 9.
netopeer-server[62280]: Checking the default Events stream path //var/lib/libnetconf//streams/.
netopeer-server[62280]: Adding augment model "/usr/local/etc/netopeer/cfgnetopeer/ietf-x509-cert-to-name.yin"
netopeer-server[62280]: ncds_features_parse: no feature definitions found in data model ietf-x509-cert-to-name.
netopeer-server[62280]: Adding static transapi "/usr/local/etc/netopeer/cfgnetopeer/ietf-netconf-server.yin"
netopeer-server[62280]: ncds_new_internal: Relax NG validator set (/usr/local/etc/netopeer/cfgnetopeer/ietf-netconf-server-config.rng)
netopeer-server[62280]: ncds_new_internal: Schematron validator set (/usr/local/etc/netopeer/cfgnetopeer/ietf-netconf-server-schematron.xsl)
netopeer-server[62280]: "ssh" features in "ietf-netconf-server" module enabled.
netopeer-server[62280]: "inbound-ssh" features in "ietf-netconf-server" module enabled.
netopeer-server[62280]: "outbound-ssh" features in "ietf-netconf-server" module enabled.
netopeer-server[62280]: Datastore ietf-netconf-server initiated with ID 1804289384.
netopeer-server[62280]: Setting the default SSH configuration for the ietf-netconf-server module...
netopeer-server[62280]: callback_srv_netconf_srv_listen_srv_port: SSH listening on the port 830
netopeer-server[62280]: Adding static transapi "/usr/local/etc/netopeer/cfgnetopeer/netopeer-cfgnetopeer.yin"
netopeer-server[62280]: ncds_new_internal: Relax NG validator set (/usr/local/etc/netopeer/cfgnetopeer/netopeer-cfgnetopeer-config.rng)
netopeer-server[62280]: ncds_new_internal: Schematron validator set (/usr/local/etc/netopeer/cfgnetopeer/netopeer-cfgnetopeer-schematron.xsl)
netopeer-server[62280]: "dynamic-modules" features in "netopeer-cfgnetopeer" module enabled.
netopeer-server[62280]: "ssh" features in "netopeer-cfgnetopeer" module enabled.
netopeer-server[62280]: Datastore netopeer-cfgnetopeer initiated with ID 846930887.
netopeer-server[62280]: Setting the default configuration for the cfgnetopeer module...
netopeer-server[62280]: Setting the default configuration for the cfgnetopeer module SSH...
netopeer-server[62280]: Model "netopeer-cfgnetopeer" transAPI: nothing changed.
netopeer-server[62280]: Netopeer server successfully initialized.
netopeer-server[62280]: SSH log: ssh_pki_import_privkey_base64: Trying to decode privkey passphrase=false
netopeer-server[62280]: SSH log: ssh_socket_pollcallback: Received POLLOUT in connecting state
netopeer-server[62280]: SSH log: callback_receive_banner: Received banner: SSH-2.0-paramiko_1.15.2
netopeer-server[62280]: SSH log: ssh_server_connection_callback: SSH client banner: SSH-2.0-paramiko_1.15.2
netopeer-server[62280]: SSH log: ssh_analyze_banner: Analyzing banner: SSH-2.0-paramiko_1.15.2
netopeer-server[62280]: SSH log: packet_send2: packet: wrote [len=540,padding=4,comp=535,payload=535]
netopeer-server[62280]: SSH log: ssh_socket_unbuffered_write: Enabling POLLOUT for socket
netopeer-server[62280]: SSH log: ssh_packet_socket_callback: packet: read type 20 [len=460,padding=5,comp=454,payload=454]
netopeer-server[62280]: SSH log: ssh_packet_process: Dispatching handler for packet type 20
netopeer-server[62280]: SSH log: crypt_set_algorithms_server: Set output algorithm aes128-ctr
netopeer-server[62280]: SSH log: crypt_set_algorithms_server: Set input algorithm aes128-ctr
netopeer-server[62280]: SSH log: crypt_set_algorithms_server: Set HMAC output algorithm to hmac-sha1
netopeer-server[62280]: SSH log: crypt_set_algorithms_server: Set HMAC input algorithm to hmac-sha1
netopeer-server[62280]: SSH log: ssh_packet_socket_callback: packet: read type 30 [len=268,padding=5,comp=262,payload=262]
netopeer-server[62280]: SSH log: ssh_packet_process: Dispatching handler for packet type 30
netopeer-server[62280]: SSH log: ssh_packet_kexdh_init: Received SSH_MSG_KEXDH_INIT
(core dumped)

**Comment by michalvasko** [comment]
Hi,
that is quite hard to guess so all I can suggest is for you to use [netopeer2](https://github.com/cesnet/netopeer2) instead. We do not provide support for `netopeer` anymore.

Regards,
Michal
