### ISSUE TITLE
netooper client(Agent)

### ISSUE THREAD

**Issue by Rohit2387** [CESNET/netopeer#173]
Hi,
Is there any sample example code avl to check netconf based client part.
IF server is sending edit-config how client will process it.

**Comment by michalvasko** [comment]
Hi,
I am really not sure what you are asking and do not use `netopeer` if you can, use [netopeer2](https://github.com/cesnet/netopeer2) instead. Also, NETCONF server cannot send `edit-config`, the NETCONF client sends it and the server processes it.

Regards,
Michal

**Comment by Rohit2387** [comment]
Hi Thanks for the response.currently I am installing libnetconf2.So to understand how it works.I need sample example code for Server(Device which will listening for request ) and client which will send request(forex get-config/edit-config).netooper2 have both sample code?

**Comment by michalvasko** [comment]
Yes, the NETCONF server is `netopeer2-server` and NETCONF client `netopeer2-cli`, both found in the repository `netopeer2`.

Regards,
Michal

**Comment by Rohit2387** [comment]
Thanks .
I am able to install this library.One question I have even connect is succesfully.I am geting below error in server.
netopeer2-server[19179]: np2srv_sr_event_notif_send failed (sysrepo: Validation of the changes failed).

**Comment by michalvasko** [comment]
Hi,
you should have created a new issue because we are talking about *netopeer2* now. Anyway, there is no real description of the problem you are facing so I am unable to help you. Did you properly install all the libraries and applications? What is the output of `# sysrepoctl -l`?

Regards,
Michal

**Comment by Rohit2387** [comment]
Module Name                   | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
example-module                |            | Installed   | root:root           | 666         |                               |
test-module                   |            | Installed   | root:root           | 666         |                               |
referenced-data               |            | Installed   | root:root           | 666         |                               |
small-module                  |            | Installed   | root:root           | 666         |                               |
info-module                   |            | Installed   |                     |             |                               |
module-a                      | 2016-02-10 | Installed   | root:root           | 666         |  sub-a-one sub-a-two          |
module-b                      | 2016-02-05 | Installed   | root:root           | 666         |                               |
module-a                      | 2016-02-02 | Imported    |                     |             |  sub-a-one sub-a-two          |
ietf-interfaces               | 2014-05-08 | Installed   | root:root           | 666         |                               |
iana-if-type                  | 2014-05-08 | Installed   |                     |             |                               |
ietf-ip                       | 2014-06-16 | Installed   |                     |             |                               |
state-module                  | 2016-07-01 | Installed   | root:root           | 666         |                               |
top-level-mandatory           |            | Installed   | root:root           | 666         |                               |
cross-module                  |            | Installed   | root:root           | 666         |                               |
turing-machine                | 2013-12-27 | Installed   | root:root           | 666         |                               |
ietf-netconf-notifications    | 2012-02-06 | Installed   | root:root           | 666         |                               |
ietf-netconf                  | 2011-06-01 | Imported    |                     |             |                               |
ietf-netconf-acm              | 2012-02-22 | Imported    |                     |             |                               |
nc-notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
notifications                 | 2008-07-14 | Installed   | root:root           | 666         |                               |
servers                       |            | Installed   | root:root           | 666         |                               |
swig-test-cpp-changes         | 2017-03-09 | Installed   | root:root           | 666         |                               |
swig-test-cpp-operations      | 2017-03-09 | Installed   | root:root           | 666         |                               |
