### ISSUE TITLE
Only state data filtering 

### ISSUE THREAD

**Issue by dumagio19** [CESNET/netopeer#175]
In issue https://github.com/CESNET/netopeer/issues/77 in comment https://github.com/CESNET/netopeer/issues/77#issuecomment-164386729 it is said that state data can be retrieved only with filer on container.

Is possible that we filter only the leaf WANDeviceNumberOfEntries (which is state data)?

**Comment by michalvasko** [comment]
Hi,
it naturally is possible because you can simply filter it as any other leaf. How to do that is written [here](https://tools.ietf.org/html/rfc6241#section-6.2.4).

Regards,
Michal

**Comment by dumagio19** [comment]
Thank you for fast response.
It helped me.
Regards.
