### ISSUE TITLE
configure: error: failed to find required module libxml2

### ISSUE THREAD

**Issue by kingsouljz** [CESNET/netopeer#176]
Hello,
When running  "./configure" in the /notepeer/server, I meet the following error
--------------------------------------------------------------------------------------
checking for pkg-config... /usr/bin/pkg-config
checking for roff2html... no
checking for distro... ubuntu
configure: WARNING: Unsupported Linux distro "ubuntu", only RHEL and SUSE are fully supported.
checking pkg-config is at least version 0.9.0... yes
checking for LIBNETCONF... yes
checking for uname... yes
checking for host architecture... x86_64
checking for lnctool... yes
checking python module: os... yes
checking python module: copy... yes
checking python module: curses... yes
checking python module: libxml2... no
configure: error: failed to find required module libxml2
------------------------------------------------------------------------------------------------
Can't find python module: libxml2, but I have installed the newest "libxml2" and  "python-libxml2".

When "./configure" in the /notepeer/cli, it's ok.

Could anybody help me please?

**Comment by michalvasko** [comment]
Hi,
*netopeer-cli* does not require python `libxml2` module. However, if you have installed package `python-libxml2` then I do not know what the problem may be, you can find the specific error in `config.log`.

Regards,
Michal

**Comment by kingsouljz** [comment]
> Hi,
> _netopeer-cli_ does not require python `libxml2` module. However, if you have installed package `python-libxml2` then I do not know what the problem may be, you can find the specific error in `config.log`.
> 
> Regards,
> Michal

Thanks for your replay very much. I have solved this problem by installing the "libxml2" directly with
 "pip install libxml2-python3".
