### ISSUE TITLE
Object with default value missing from running configuration

### ISSUE THREAD

**Issue by maksimvuleta** [CESNET/netopeer#178]
I try to apply the config with netopeer-cli (edit-config operation) and it fails and returns an error. 
After that, I do get-config running, and in the running configuration, there are not shown objects which current values are equal to their default values. 

Is this regular behavior? 
How to prevent this happens?

**Comment by michalvasko** [comment]
Hi,
that is the correct behavior based on your description. You probably want to use some default option, look at `get-config -h` in *netopeer2-cli*, the `defaults` parameter in particular. Detailed explanation of each option can be found [here](https://tools.ietf.org/html/rfc6243).

Regards,
Michal
