### ISSUE TITLE
Monitoring a custom device that is not supporting Netconf

### ISSUE THREAD

**Issue by badr-bzh** [CESNET/netopeer#179]
I want to monitor a custom device that is not supporting Netconf.
How should I proceed ?

Thanks in advance.

Darat

**Comment by michalvasko** [comment]
Hi Darat,
so you want to add NETCONF support by using *netopeer*? Then you are much better off using [netopeer2](https://github.com/cesnet/netopeer2) with [sysrepo](https://github.com/sysrepo/sysrepo).

Regards,
Michal

**Comment by badr-bzh** [comment]
Hi Michal,
Let's say I want to edit some configuration files using Netconf, is there another way without using netopeer2 and sysrepo, per example with the python netconf package Ncclient and netconf server ? It would be much easier for me since I used Ncclient before.

Thanks you.

**Comment by michalvasko** [comment]
Hi,
`ncclient` is only NETCONF client (based on the name). We also have that (`netopeer2-cli`) but you do not have to use it, naturally. But, we also provide NETCONF server `netopeer2-server` (which depends on `sysrepo`) so that is why I referenced it. Without a NETCONF server your `ncclient` is useless.

Regards,
Michal

**Comment by badr-bzh** [comment]
Hi,
Can I use the server mentionned in this link : https://netconf.readthedocs.io/en/master/develop.html#netconf-server
Thank you.

**Comment by michalvasko** [comment]
Hi,
I do not believe the software mentioned on that page is in any way connected to *netopeer* or anything else developed by us. How did you find this page?

Regards,
Michal

**Comment by badr-bzh** [comment]
Hi Michal,

It's the class server in python package for Netconf.

Thank you.

**Comment by badr-bzh** [comment]
Otherwise, If I want to use Netopeer2, what the steps and How should I proceed ?

**Comment by michalvasko** [comment]
Hi,
I have not managed to find any mention of *netopeer* or anything else. What is more, there are also tests and CI script that compiles it and there is still no downloading of *netopeer* (so it should work without it). Anyway, you should first read some basic information in docs (start at `README.md`) about either *netopeer* or *netopeer2*. There you should learn how to install it properly, if you are certain it is required.

Regards,
Michal
