### ISSUE TITLE
Starting netopeer-server with TransAPI ietf-routing

### ISSUE THREAD

**Issue by vggonzalez** [CESNET/netopeer#180]
Hi,

I'm working on a project and I need to start a NETCONF server with the YANG module ietf-routing and the proper code to affect the device's real configuration.
I was working with yuma123 but it wasn't clear to me how to write the C module for the YANG one, so I started looking for a solution and I found this TransAPI of ietf-routing:
https://git-us.netdef.org/projects/OSR/repos/transapi-ietf-routing/browse
It's supposed to work only with netopeer, therefore I need to use this version instead of netopeer2.

It's a little unclear to me how I can start the netopeer-server loading this transAPI properly so I can do the changes I want to through edit-config operations.

Could I get some clarify?

Thank you very much.

**Comment by michalvasko** [comment]
Hi,
what exactly is unclear, the short README in that project says it all. To install *netopeer-server* refer to the README in `netopeer/server`.

Regards,
Michal

**Comment by vggonzalez** [comment]
My bad for not looking at it in depth, sorry.


It's now clear to me that in order to add a new module and it's transAPI I must call netopeer-manager. I then referred to netopeer-manager.1 in order to see how it worked and I can see that the command I need to call is "netopeer-manager add" with the proper parameters to refer to the transAPI model.

However there is a constant reference to an .XML file that should point to the transAPI and I was wondering which .XML file this is?

Also, looking at the Makefile at the transAPI I found (https://git-us.netdef.org/projects/OSR/repos/transapi-ietf-routing/browse/Makefile.in) it seems to me that the commands in order to add the module to netopeer are already there, so after building the module no further action would be required besides restarting netopeer, right?

**Comment by michalvasko** [comment]
Hi,
just stick to what is written in the README of the project you referenced. It says you just need to run `make install` and nothing else, so yes, it is all performed automatically and you do not have to run `netopeer-manager` yourself.

Regards,
Michal

**Comment by vggonzalez** [comment]
Thank you very much Michal, closing the issue.
