### ISSUE TITLE
connect netopeer-server and netopeer2-cli

### ISSUE THREAD

**Issue by seonhee-kim** [CESNET/netopeer#184]
Hi all, 

I have a server using libnetconf and I have a job to create a new client.
Is it ok to develop a client using libnetconf2?
I can't rebuild the server using libnetconf2.
(I have verified the connection between netopeer-server and netopeer2-cli.)

Thanks.

**Comment by michalvasko** [comment]
Hi,
yes, you can create your own client using *libnetconf2* and it will work just fine with *netopeer-server*.

Regards,
Michal

**Comment by seonhee-kim** [comment]
Hi,

_netopeer-server_ is mean my server using _libnetconf_?
I know _netopeer_ is a set of NETCONF tools built on the _libnetconf_ library.
But I ask questions to be sure understanding.

Thanks.

**Comment by michalvasko** [comment]
Hi,
yes, I have misread your post a little, any proper server written using *libnetconf* (a NETCONF server) must be able to communicate with a client written using *libnetconf2* (a NETCONF client).

Regards,
Michal

**Comment by seonhee-kim** [comment]
Thanks for the help.
