### ISSUE TITLE
libnetconf ERROR: Unable to connect to 192.168.3.139:830

### ISSUE THREAD

**Issue by Bijendra0508** [CESNET/netopeer#193]
Hello Team,

I am trying to connect netopeer client to a netopeer server.
I used master branch of following repository to build and run server & client.

git clone https://github.com/CESNET/libnetconf.git
git clone https://github.com/CESNET/netopeer.git

Also i used ubuntu 16.04 platform to run both netopeer server and client and  used libssh-0.7.4

the following commands i used to trigger netopeer server and client:
/usr/local/bin/netopeer-server -v 3
netopeer-cli
netconf> connect --port 830 --login root 192.168.3.139

with above commands client failed to connect with netopeer server. please suggest
what is wrong i am doing.

Client Logs:
netconf> connect --port 830 --login root 192.168.3.139
libnetconf ERROR: Unable to connect to 192.168.3.139:830.

Server Log:
netopeer-server[6931]: Shared memory location: /dev/shm/libnetconfshm
netopeer-server[6931]: POSIX SHM File Descriptor: 5 (600B).
netopeer-server[6931]: ncds_features_parse: no feature definitions found in data model ietf-inet-types.
netopeer-server[6931]: ncds_features_parse: no feature definitions found in data model ietf-yang-types.
netopeer-server[6931]: ncds_features_parse: no feature definitions found in data model ietf-netconf-monitoring.
netopeer-server[6931]: ncds_features_parse: no feature definitions found in data model ietf-netconf-notifications.
netopeer-server[6931]: ncds_features_parse: no feature definitions found in data model nc-notifications.
netopeer-server[6931]: ncds_features_parse: no feature definitions found in data model notifications.
netopeer-server[6931]: ncds_features_parse: no feature definitions found in data model libnetconf-notifications.
netopeer-server[6931]: ncds_features_parse: no feature definitions found in data model ietf-netconf-with-defaults.
netopeer-server[6931]: ncds_features_parse: no feature definitions found in data model ietf-netconf-acm.
netopeer-server[6931]: ncds_set_validation: Relax NG validator set (//var/lib/libnetconf//ietf-netconf-acm-config.rng)
netopeer-server[6931]: ncds_set_validation: Schematron validator set (//var/lib/libnetconf//ietf-netconf-acm-schematron.xsl)
netopeer-server[6931]: Datastore ietf-netconf-acm initiated with ID 9.
netopeer-server[6931]: Checking the default Events stream path //var/lib/libnetconf//streams/.
netopeer-server[6931]: Adding augment model "/usr/local/etc/netopeer/cfgnetopeer/ietf-x509-cert-to-name.yin"
netopeer-server[6931]: ncds_features_parse: no feature definitions found in data model ietf-x509-cert-to-name.
netopeer-server[6931]: Adding static transapi "/usr/local/etc/netopeer/cfgnetopeer/ietf-netconf-server.yin"
netopeer-server[6931]: ncds_new_internal: Relax NG validator set (/usr/local/etc/netopeer/cfgnetopeer/ietf-netconf-server-config.rng)
netopeer-server[6931]: ncds_new_internal: Schematron validator set (/usr/local/etc/netopeer/cfgnetopeer/ietf-netconf-server-schematron.xsl)
netopeer-server[6931]: "ssh" features in "ietf-netconf-server" module enabled.
netopeer-server[6931]: "inbound-ssh" features in "ietf-netconf-server" module enabled.
netopeer-server[6931]: "outbound-ssh" features in "ietf-netconf-server" module enabled.
netopeer-server[6931]: Datastore ietf-netconf-server initiated with ID 1804289384.
netopeer-server[6931]: Setting the default SSH configuration for the ietf-netconf-server module...
netopeer-server[6931]: callback_srv_netconf_srv_listen_srv_port: SSH listening on the port 830
netopeer-server[6931]: Transapi calling callback /A:netconf/A:ssh/A:listen/A:port with op REM.
netopeer-server[6931]: callback_srv_netconf_srv_listen_srv_port: SSH stopped listening on the port 830
netopeer-server[6931]: Transapi calling callback /A:netconf/A:ssh/A:listen/A:interface with op ADD.
netopeer-server[6931]: callback_srv_netconf_srv_listen_srv_interface: SSH listening on the address 192.168.3.139:830
netopeer-server[6931]: Adding static transapi "/usr/local/etc/netopeer/cfgnetopeer/netopeer-cfgnetopeer.yin"
netopeer-server[6931]: ncds_new_internal: Relax NG validator set (/usr/local/etc/netopeer/cfgnetopeer/netopeer-cfgnetopeer-config.rng)
netopeer-server[6931]: ncds_new_internal: Schematron validator set (/usr/local/etc/netopeer/cfgnetopeer/netopeer-cfgnetopeer-schematron.xsl)
netopeer-server[6931]: "dynamic-modules" features in "netopeer-cfgnetopeer" module enabled.
netopeer-server[6931]: "ssh" features in "netopeer-cfgnetopeer" module enabled.
netopeer-server[6931]: Datastore netopeer-cfgnetopeer initiated with ID 846930887.
netopeer-server[6931]: Setting the default configuration for the cfgnetopeer module...
netopeer-server[6931]: Setting the default configuration for the cfgnetopeer module SSH...
netopeer-server[6931]: Transapi calling callback /A:netopeer/A:modules/A:module/A:enabled with op ADD.
netopeer-server[6931]: Adding augment model "/usr/local/etc/netopeer/ietf-interfaces/iana-if-type.yin"
netopeer-server[6931]: ncds_features_parse: no feature definitions found in data model iana-if-type.
netopeer-server[6931]: Adding transapi "/usr/local/etc/netopeer/ietf-interfaces/ietf-interfaces.yin"
netopeer-server[6931]: ncds_new_internal: Relax NG validator set (/usr/local/etc/netopeer/ietf-interfaces/ietf-interfaces-config.rng)
netopeer-server[6931]: ncds_new_internal: Schematron validator set (/usr/local/etc/netopeer/ietf-interfaces/ietf-interfaces-schematron.xsl)
netopeer-server[6931]: Adding augment model "/usr/local/etc/netopeer/ietf-interfaces/ietf-ip.yin"
netopeer-server[6931]: "ipv4-non-contiguous-netmasks" features in "ietf-ip" module enabled.
netopeer-server[6931]: "ipv6-privacy-autoconf" features in "ietf-ip" module enabled.
netopeer-server[6931]: Datastore ietf-interfaces initiated with ID 1681692778.
netopeer-server[6931]: Model "ietf-interfaces" transAPI: nothing changed.
netopeer-server[6931]: Starting FMON thread for ietf-interfaces data model.
netopeer-server[6931]: Netopeer server successfully initialized.

**Comment by michalvasko** [comment]
I do not see any errors on the server side so it seems the client did not even reach it, for whatever reason. I am not able to help you more because *libnetconf* and *netopeer* are not supported for quite a few years now, we have developed [libnetconf2](https://github.com/cesnet/libnetconf2) and [netopeer2](https://github.com/cesnet/netopeer2).

**Comment by Bijendra0508** [comment]
Hello Michal,

I switched to netopeer2 and libnetconf2. I used the following version:
netopeer2: 1.1.39
libnetconf2: 1.1.26
libssh:  git master branch: http://git.libssh.org/projects/libssh.git
libyang: 1.0.184
sysrepo: 1.4.70

I build successfully and installed the netopeer2. However while reading the datas of netopeer2-server i got a time out error.

Client Logs:

`root@embedded-PC:/home/abhishek_s/bijendra/5G-RU/NETCONF2/netopeer2# netopeer2-cli
> connet --login abhishek_s 192.168.3.42
connet: No such command, type 'help' for more information.
> connect --login abhishek_s 192.168.3.42
Interactive SSH Authentication
Type your password:
Password:
abhishek_s@localhost password:
> get
cli_send_recv: Timeout for receiving a reply expired.
>
`

Netopeer2-server Log: detailed log are attached:

> [INF]: SR: Ext SHM was defragmented and 4368 B were saved.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-keystore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-truststore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.

[netopeer2_server.txt](https://github.com/CESNET/netopeer/files/5595122/netopeer2_server.txt)

ideally i should receive a response from server but i am getting an timeout. please suggest what am i missing here,

**Comment by michalvasko** [comment]
In the output there is an error
```
[ERR]: LN: Could not bind "0.0.0.0" port 830 (Address already in use).
```
meaning you already have something listening on the address. It is most likely the old *netopeer* so terminate it first.

**Comment by Bijendra0508** [comment]
Hello Michal,

Thank you for your input. I am able to connect to netopeer2-server using netopeer2-cli running on same ubuntu distro.
But once i setup netopeer2-server on any other ubuntu distro in same network then netopeer2-cli failed to connect to server.

> root@shreya-PC:/home/bijendra/5G-RU# netopeer2-cli
> connect --login root 192.168.3.42
nc ERROR: Unable to connect to localhost:830 (Connection refused).
cmd_connect: Connecting to the localhost:830 as user "root" failed.
>

Is it mandatory that both netopeer2 server client must be on same linux machine.

**Comment by michalvasko** [comment]
Of course no, but it must be possible to connect from the client machine to the server machine, which does not seem to be your case. `Connection refused` means the system was not able to connect on TCP/IP layer, it is not a *netopeer2* problem.

**Comment by Bijendra0508** [comment]
Hello michal,

thank you for response.
is there a way i can hard code the localhost ip address. On this [issue](https://github.com/CESNET/libnetconf/issues/207)
you mentioned an xml where we can specify the ip address and port. similar thing how can i do here.
I am new in netconf so I don't know this will help or not just want to give a try.

**Comment by michalvasko** [comment]
I can help you to do that (say so) but I do not think that is really the issue because by default the server listens on all the interfaces. It is more likely it is being blocked by firewall or something like that.

**Comment by Bijendra0508** [comment]
Hello michal,

I tried to install netopeer2 on ARM platform running ubuntu 20.04
I installed these [modules](https://github.com/CESNET/netopeer/issues/193#issuecomment-733528770) and started running netopeer2 server and client.
Doing so i noticed below errors:
` Server's <hello> timeout elapsed`
`Client's <hello> timeout elapsed.`

**Client Logs:**

> > connect --ssh --host 192.168.2.137 --port 830 --login prashant
> Interactive SSH Authentication
> Type your password:
> Password:
> nc ERROR: Server's <hello> timeout elapsed.
> cmd_connect: Connecting to the 192.168.2.137:830 as user "prashant" failed.
> >

**Server log:**

> [INF]: LN: Accepted a connection on 0.0.0.0:830.
> [INF]: SR: Session 11 (user "root") created.
> [INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
> [INF]: LN: Received an SSH message "request-auth" of subtype "none".
> [INF]: LN: Received an SSH message "request-auth" of subtype "interactive".
> [INF]: LN: Received an SSH message "request-auth" of subtype "interactive".
> [INF]: LN: User "prashant" authenticated.
> [INF]: LN: Received an SSH message "request-channel-open" of subtype "session".
> [INF]: LN: Received an SSH message "request-channel" of subtype "subsystem".
> [ERR]: LN: Client's <hello> timeout elapsed.
> [2021/01/08 16:50:06.396212, 1] ssh_socket_exception_callback:  Socket exception callback: 1 (0)
> [2021/01/08 16:50:06.396336, 1] ssh_socket_exception_callback:  Socket error: disconnected
> [INF]: LN: Accepted a connection on 0.0.0.0:830.
> [INF]: SR: Session 12 (user "root") created.
> [INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
> [INF]: LN: Received an SSH message "request-auth" of subtype "none".
> [INF]: LN: Received an SSH message "request-auth" of subtype "interactive".
> [INF]: LN: Received an SSH message "request-auth" of subtype "interactive".
> [INF]: LN: User "prashant" authenticated.
> [INF]: LN: Received an SSH message "request-channel-open" of subtype "session".
> [INF]: LN: Received an SSH message "request-channel" of subtype "subsystem".
> [ERR]: LN: Client's <hello> timeout elapsed.
> [INF]: LN: Accepted a connection on 0.0.0.0:830.
> [INF]: SR: Session 13 (user "root") created.
> [INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
> [INF]: LN: Received an SSH message "request-auth" of subtype "none".
> [INF]: LN: Received an SSH message "request-auth" of subtype "interactive".
> [INF]: LN: Received an SSH message "request-auth" of subtype "interactive".
> [INF]: LN: Failed user "prashant" authentication attempt (#1).
> [INF]: LN: Received an SSH message "request-auth" of subtype "password".
> [INF]: LN: User "prashant" authenticated.
> [INF]: LN: Received an SSH message "request-channel-open" of subtype "session".
> [INF]: LN: Received an SSH message "request-channel" of subtype "subsystem".
> [ERR]: LN: Client's <hello> timeout elapsed.
> [INF]: LN: Accepted a connection on 0.0.0.0:830.
> [INF]: SR: Session 14 (user "root") created.
> [INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
> [INF]: LN: Received an SSH message "request-auth" of subtype "none".
> [INF]: LN: Received an SSH message "request-auth" of subtype "interactive".
> [INF]: LN: Received an SSH message "request-auth" of subtype "interactive".
> [INF]: LN: User "prashant" authenticated.
> [INF]: LN: Received an SSH message "request-channel-open" of subtype "session".
> [INF]: LN: Received an SSH message "request-channel" of subtype "subsystem".
> [ERR]: LN: Client's <hello> timeout elapsed.

Please suggest what could be wrong. 
**PS**: OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020

**Comment by michalvasko** [comment]
*OpenSSL* should not matter but rather *libssh*. What version are you using?

**Comment by Bijendra0508** [comment]
Hello Michal,

Current ssh version: libssh-0.9.2

**Comment by michalvasko** [comment]
That should be fine. Do you get the timeout error immediately after authenticating or after several seconds?

**Comment by Bijendra0508** [comment]
Hello Michal,

I got timeout error immediately after authenticltion

**Comment by michalvasko** [comment]
Okay, then I would suggest updating *libssh* to 0.9.5 and try it with that.

**Comment by Bijendra0508** [comment]
Hello Michal,
I tried with libssh 0.9.5 but result remail same. 

Server log:

> [INF]: LN: Accepted a connection on 0.0.0.0:830.
> [INF]: SR: Session 8 (user "root") created.
> [INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
> [INF]: LN: Received an SSH message "request-auth" of subtype "none".
> [INF]: LN: Received an SSH message "request-auth" of subtype "interactive".
> [INF]: LN: Received an SSH message "request-auth" of subtype "interactive".
> [INF]: LN: Failed user "bj" authentication attempt (#1).
> [INF]: LN: Received an SSH message "request-auth" of subtype "password".
> [INF]: LN: User "bj" authenticated.
> [INF]: LN: Received an SSH message "request-channel-open" of subtype "session".
> [INF]: LN: Received an SSH message "request-channel" of subtype "subsystem".
> [ERR]: LN: Client's <hello> timeout elapsed.
> [2021/01/14 11:44:49.592113, 1] ssh_socket_exception_callback:  Socket exception callback: 2 (104)
> [2021/01/14 11:44:49.592169, 1] ssh_socket_exception_callback:  Socket error: Connection reset by peer
>  

Client log:
> bj@localhost:~$ netopeer2-cli
> get_netconf_dir: Configuration directory "/home/bj/.netopeer2-cli" did not exist, created.
> load_config: No saved history.
> load_config: No saved configuration.
> > connect --login bj
> The authenticity of the host 'localhost' cannot be established.
> ssh-rsa key fingerprint is 7f:bb:b3:2d:57:1a:5e:a1:b8:98:b4:c6:53:7f:0a:f7:f5:e8:74:fa.
> Are you sure you want to continue connecting (yes/no)? yes
> Interactive SSH Authentication
> Type your password:
> Password:
> bj@localhost password:
> nc ERROR: Server's <hello> timeout elapsed.
> cmd_connect: Connecting to the localhost:830 as user "bj" failed.
> 

Platform OS details:

> bj@localhost:~$ cat /etc/os-release
> NAME="Ubuntu"
> VERSION="20.04 LTS (Focal Fossa)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 20.04 LTS"
> VERSION_ID="20.04"

**Comment by michalvasko** [comment]
Then I do not really have any more ideas what may be the cause. There is [this](https://github.com/sysrepo/sysrepo/issues/2080) problem on your Ubuntu 20.04 but it should not cause the issue you are having. I am sorry, I cannot help you.

**Comment by Bijendra0508** [comment]
Hello Michal,

Thank you for update. 
Lets hope in near future this problem get resolved and meanwhile i will switch to other version of ubuntu.

**Comment by Bijendra-puresoftware** [comment]
Hello Michal,

I tried to install netopeer2 server client on fresh ubuntu 18.04 with help of WSL. 
Since i got fresh 18.04 i forced to install couple of dependent packages. List are below:
1. apt-get install cmake
2. apt-get install build-essential
3. apt-get install libpcre3-dev libpcre3
4. apt-get install zlib1g-dev
5. apt install zlib1g
6. apt-get install libssl-dev

Following to above I installed:
Libyang: git clone https://github.com/CESNET/libyang.git
Libssh: git clone http://git.libssh.org/projects/libssh.git
sysrepo: git clone https://github.com/sysrepo/sysrepo.git
libnetconf2: git clone https://github.com/CESNET/libnetconf2.git
netopeer2: git clone https://github.com/CESNET/netopeer2.git

 I started the server and client by following commnd:
> netopeer2-server -d -v 3
> netopeer2-cli
> connect --login bijendra

Connection successfully established between server and client but **get** command hits the segmentation fault.
I am not very sure what went wrong. request you to please suggest what could be wrong.
Thank you.
[netopeer2_client_WSL_log.txt](https://github.com/CESNET/netopeer/files/5819782/netopeer2_client_WSL_log.txt)
[netopeer2_server_WSL_log.txt](https://github.com/CESNET/netopeer/files/5819783/netopeer2_server_WSL_log.txt)

**Comment by Bijendra0508** [comment]
Hello Michal,

I tried to install netopeer2 server client on fresh ubuntu 18.04 with help of WSL. 
Since i got fresh 18.04 i forced to install couple of dependent packages. List are below:
1. apt-get install cmake
2. apt-get install build-essential
3. apt-get install libpcre3-dev libpcre3
4. apt-get install zlib1g-dev
5. apt install zlib1g
6. apt-get install libssl-dev

Following to above I installed:
Libyang: git clone https://github.com/CESNET/libyang.git
Libssh: git clone http://git.libssh.org/projects/libssh.git
sysrepo: git clone https://github.com/sysrepo/sysrepo.git
libnetconf2: git clone https://github.com/CESNET/libnetconf2.git
netopeer2: git clone https://github.com/CESNET/netopeer2.git

 I started the server and client by following commnd:
> netopeer2-server -d -v 3
> netopeer2-cli
> connect --login bijendra

Connection successfully established between server and client but **get** command hits the segmentation fault.
I am not very sure what went wrong. request you to please suggest what could be wrong.
Thank you.
[netopeer2_client_WSL_log.txt](https://github.com/CESNET/netopeer/files/5819782/netopeer2_client_WSL_log.txt)
[netopeer2_server_WSL_log.txt](https://github.com/CESNET/netopeer/files/5819783/netopeer2_server_WSL_log.txt)

**Comment by michalvasko** [comment]
Ah, there is no check for WSL in `master` yet, only in `devel`. In any case, WSL is not supported (or more precisely, WSL does not support *sysrepo*) so that is causing all your problems. Use an actual Linux distribution (in a VM) instead.
