### ISSUE TITLE
Opendaylight Connection with a device with Netopeer

### ISSUE THREAD

**Issue by GabrielOrozco** [CESNET/netopeer#194]
Hello Team

I'm trying to connect a device that has a netopeer server with my opendaylight installation. However, I'm falling to get the yang models of the server.
When I try the hello message with the server (i.e., ssh -p 830 user@deviceaddress -s netconf)
I have no issue, all the yang models are listed.

However, when I try to use opendaylight to manage the device to a restconf northbound interface none of the models appear in 

GET http://172.17.0.2:8181/restconf/config/network-topology:network-topology/topology/topology-netconf/node/TSN-Switch/yang-ext:mount/

The only models that appear are ietf-keystore:keystore and netconf-server. The ietf-keystore has the certificates. 

After checking, I discovered that this certificates are for configuring something called Callhome, but I don't know if this related with the fact that none of the other models are listed

Thanks beforehand for your attention

**Comment by michalvasko** [comment]
Not sure I can help you, it seems to be an ODL problem so you better ask them. Also, *netopeer* is really old now and not supported for quite some time.

**Comment by GabrielOrozco** [comment]
Alright, just knowing that maybe is an issue of ODL and not a simple configuration in Netopeer seems enough for going in that direction.

Thanks for your answer
