### ISSUE TITLE
edit-config fails with error - "There is no device/data that could be affected."

### ISSUE THREAD

**Issue by deepthivemu** [CESNET/netopeer#198]
Hi, I have just started using netopeer and would need some help with the issues I am seeing. I am able to connect to the target from netopeer and also able to get its config (get-config). However, edit-config fails with an error "There is no device/data that could be affected.". 

I have tried some debugging and found from the output of "netopeer-manager list" that there are no modules installed. Based on the error log of "edit-config running", it looks like the issue is with "<config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">" in my xml file. How do I resolve this issue?

Logs of corresponding outputs attached.
[netopeer_logs.txt](https://github.com/CESNET/netopeer/files/7992927/netopeer_logs.txt)

**Comment by michalvasko** [comment]
If you have just started using *netopeer* then please stop right away and use [*netopeer2*](https://github.com/CESNET/netopeer2/) instead. This project is obsolete and outdated.

**Comment by deepthivemu** [comment]
I installed netopeer2 but connect fails with following errors. Is there any dependency to be met yet?

> 
> 
> 
> connect --ssh --host 10.52.141.158 --port 830 --login admin
admin@10.52.141.158 password: 
ly ERROR: Double-quoted string unknown special character '\.'. (Line number 192.)
ly ERROR: Parsing module "ietf-inet-types" failed.
ly ERROR: Double-quoted string unknown special character '\*'. (Line number 90.)
ly ERROR: Parsing module "ietf-netconf-acm" failed.
ly ERROR: Loading "ietf-netconf-acm" module failed.
ly ERROR: Loading "ietf-netconf-acm" module failed.
ly ERROR: Parsing module "ietf-netconf" failed.
nc ERROR: Loading base NETCONF schema failed.
ly ERROR: Value "admin" was not found in the dictionary.
ly ERROR: Value "10.52.141.158" was not found in the dictionary.
cmd_connect: Connecting to the 10.52.141.158:830 as user "admin" failed.
> 
###################################################################

root@server:~/deepthi/netconf/netopeer2# netopeer2-server -d -v3
[INF]: LY: Searching for "ietf-yang-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: SR: Applying scheduled changes.
[INF]: LY: Searching for "ietf-datastores" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-datastores@2018-02-14.yang" file.
[INF]: LY: Searching for "ietf-yang-library" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-yang-library@2019-01-04.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-inet-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "sysrepo-monitoring" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/sysrepo-monitoring@2021-07-29.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Implemented module "ietf-datastores@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Searching for "sysrepo-plugind" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/sysrepo-plugind@2020-12-10.yang" file.
[INF]: LY: Searching for "ietf-netconf" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-netconf@2013-09-29.yang" file.
[INF]: LY: Searching for "ietf-inet-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-netconf-acm" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-netconf-acm@2018-02-14.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-yang-metadata" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-yang-metadata@2016-08-05" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-yang-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-netconf-with-defaults" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-netconf-with-defaults@2011-06-01.yang" file.
[INF]: LY: Searching for "ietf-yang-metadata" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-yang-metadata@2016-08-05" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-netconf-notifications" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-netconf-notifications@2012-02-06.yang" file.
[INF]: LY: Searching for "ietf-inet-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Implemented module "ietf-netconf@2013-09-29" is not used for import, revision "2013-09-29" is imported instead.
[INF]: LY: Searching for "ietf-origin" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-origin@2018-02-14.yang" file.
[INF]: LY: Searching for "ietf-yang-metadata" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-yang-metadata@2016-08-05" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-netconf-monitoring" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-netconf-monitoring@2010-10-04.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-inet-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-netconf-nmda" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-netconf-nmda@2019-01-07.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-inet-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Implemented module "ietf-datastores@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Implemented module "ietf-netconf@2013-09-29" is not used for import, revision "2013-09-29" is imported instead.
[INF]: LY: Searching for "nc-notifications" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/nc-notifications@2008-07-14.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "notifications" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/notifications@2008-07-14.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-x509-cert-to-name" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-x509-cert-to-name@2014-12-10.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-crypto-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-crypto-types@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Implemented module "ietf-netconf-acm@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Searching for "ietf-keystore" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-keystore@2019-07-02.yang" file.
[INF]: LY: Implemented module "ietf-netconf-acm@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Searching for "ietf-truststore" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-truststore@2019-07-02.yang" file.
[INF]: LY: Implemented module "ietf-netconf-acm@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Implemented module "ietf-crypto-types@2019-07-02" is not used for import, revision "2019-07-02" is imported instead.
[INF]: LY: Searching for "ietf-tcp-common" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-tcp-common@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-ssh-server" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-ssh-server@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-ssh-common" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-ssh-common@2019-07-02.yang" file.
[INF]: LY: Searching for "iana-crypt-hash" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/iana-crypt-hash@2014-08-06.yang" file.
[INF]: LY: Implemented module "ietf-netconf-acm@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Searching for "ietf-tls-server" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-tls-server@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-tls-common" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-tls-common@2019-07-02.yang" file.
[INF]: LY: Implemented module "ietf-keystore@2019-07-02" is not used for import, revision "2019-07-02" is imported instead.
[INF]: LY: Implemented module "ietf-netconf-acm@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Searching for "ietf-netconf-server" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-netconf-server@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-tcp-client" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-tcp-client@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-inet-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-tcp-server" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-tcp-server@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-inet-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Implemented module "ietf-tcp-common@2019-07-02" is not used for import, revision "2019-07-02" is imported instead.
[INF]: LY: Searching for "ietf-interfaces" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-interfaces@2018-02-20.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-ip" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-ip@2018-02-22.yang" file.
[INF]: LY: Searching for "ietf-inet-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-yang-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-network-instance" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-network-instance@2019-01-21.yang" file.
[INF]: LY: Implemented module "ietf-interfaces@2018-02-20" is not used for import, revision "2018-02-20" is imported instead.
[INF]: LY: Searching for "ietf-yang-schema-mount" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-yang-schema-mount@2019-01-14.yang" file.
[INF]: LY: Searching for "ietf-inet-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-yang-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-subscribed-notifications" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-subscribed-notifications@2019-09-09.yang" file.
[INF]: LY: Searching for "ietf-inet-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Implemented module "ietf-interfaces@2018-02-20" is not used for import, revision "2018-02-20" is imported instead.
[INF]: LY: Implemented module "ietf-netconf-acm@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Searching for "ietf-restconf" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-restconf@2017-01-26.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-yang-push" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-yang-push@2019-09-09.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Implemented module "ietf-datastores@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Searching for "ietf-restconf" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-restconf@2017-01-26.yang" file.
[INF]: LY: Newer revision than "ietf-restconf@2017-01-26" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-yang-patch" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-yang-patch@2017-02-22.yang" file.
[INF]: LY: Searching for "ietf-restconf" in "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/root/deepthi/netconf/netopeer2/sysrepo/build/repository/yang/ietf-restconf@2017-01-26.yang" file.
[INF]: LY: Newer revision than "ietf-restconf@2017-01-26" not found, using this as the latest revision.
[INF]: LY: Use of anydata to define configuration data is not recommended. /ietf-yang-push:{augment='/sn:filters'}/ietf-yang-push:selection-filter/{uses='selection-filter-types'}/filter-spec/datastore-subtree-filter/datastore-subtree-filter
[INF]: LY: Use of anydata to define configuration data is not recommended. /ietf-subscribed-notifications:filters/stream-filter/{uses='stream-filter-elements'}/filter-spec/stream-subtree-filter/stream-subtree-filter
[INF]: LY: Use of anydata to define configuration data is not recommended. /ietf-yang-push:{augment='/sn:subscriptions/sn:subscription/sn:target'}/ietf-yang-push:datastore/{uses='datastore-criteria'}/{uses='selection-filter-objects'}/selection-filter/within-subscription/{uses='selection-filter-types'}/filter-spec/datastore-subtree-filter/datastore-subtree-filter
[INF]: LY: Use of anydata to define configuration data is not recommended. /ietf-subscribed-notifications:subscriptions/subscription/{uses='subscription-policy'}/{uses='subscription-policy-dynamic'}/{uses='subscription-policy-modifiable'}/target/stream/stream-filter/within-subscription/{uses='stream-filter-elements'}/filter-spec/stream-subtree-filter/stream-subtree-filter
[INF]: LY: Missing explicit "deprecated" status specified in parent "subnet", inheriting for "prefix-length".
[INF]: LY: Missing explicit "deprecated" status specified in parent "subnet", inheriting for "netmask".
[INF]: LY: The ordered-by statement is ignored in lists representing notification content (/ietf-yang-push:push-change-update/datastore-changes/{uses='ypatch:yang-patch'}/yang-patch/edit).
[INF]: SR: No scheduled changes.
[INF]: SR: Connection 61 created.
[INF]: SR: Session 7 (user "root", CID 61) created.
[INF]: SR: Triggering "ietf-subscribed-notifications" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[ERR]: LN: Could not bind "0.0.0.0" port 830 (Address already in use).
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-keystore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-truststore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.

**Comment by michalvasko** [comment]
As for the client errors, you probably have some old YANG modules installed somewhere, try to use `verb verbose` before connecting and it should print what modules it is using.

Regarding the server, this error
```
[ERR]: LN: Could not bind "0.0.0.0" port 830 (Address already in use).
```
probably means that you still have the old *netopeer-server* running and bound to this address.

**Comment by deepthivemu** [comment]
I have enabled verb verbose before connecting. It shows up more errors corresponding to SSH keys.

> 
> verb verbose
> 
> 
> connect --ssh --host 10.52.141.158 --login admin
nc VERBOSE: Trying to connect via IPv4 to 10.52.141.158:830.
nc VERBOSE: Successfully connected to 10.52.141.158:830 over IPv4.
[2022/02/04 11:49:32.229663, 2] ssh_config_parse_line:  Unapplicable option: SendEnv, line: 53
[2022/02/04 11:49:32.229691, 2] ssh_config_parse_line:  Unsupported option: HashKnownHosts, line: 54
[2022/02/04 11:49:32.229714, 2] ssh_connect:  libssh 0.8.90 (c) 2003-2019 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
[2022/02/04 11:49:32.229725, 2] ssh_connect:  Socket connecting, now waiting for the callbacks to work
[2022/02/04 11:49:32.229739, 1] socket_callback_connected:  Socket connection callback: 1 (0)
[2022/02/04 11:49:32.233287, 2] ssh_client_connection_callback:  SSH server banner: SSH-2.0-OpenSSH_8.0
[2022/02/04 11:49:32.233319, 2] ssh_analyze_banner:  Analyzing banner: SSH-2.0-OpenSSH_8.0
[2022/02/04 11:49:32.233334, 2] ssh_analyze_banner:  We are talking to an OpenSSH client version: 8.0 (80000)
[2022/02/04 11:49:32.233941, 1] ssh_known_hosts_read_entries:  Failed to open the known_hosts file '/etc/ssh/ssh_known_hosts': No such file or directory
[2022/02/04 11:49:32.234183, 2] ssh_kex_select_methods:  Negotiated curve25519-sha256,rsa-sha2-512,aes128-ctr,aes128-ctr,hmac-sha2-256-etm@openssh.com,hmac-sha2-256-etm@openssh.com,none,none,,
[2022/02/04 11:49:32.298925, 2] ssh_init_rekey_state:  Set rekey after 4294967296 blocks
[2022/02/04 11:49:32.298968, 2] ssh_init_rekey_state:  Set rekey after 4294967296 blocks
[2022/02/04 11:49:32.298992, 2] ssh_packet_client_curve25519_reply:  SSH_MSG_NEWKEYS sent
[2022/02/04 11:49:32.299003, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
[2022/02/04 11:49:32.299063, 2] ssh_packet_newkeys:  Signature verified and valid
[2022/02/04 11:49:32.307329, 1] ssh_packet_userauth_failure:  Access denied for 'none'. Authentication that can continue: publickey,password
[2022/02/04 11:49:32.307366, 2] ssh_packet_userauth_failure:  Access denied for 'none'. Authentication that can continue: publickey,password
nc VERBOSE: Password authentication (host "10.52.141.158", user "admin").
admin@10.52.141.158 password: 
nc VERBOSE: Authentication successful.
[2022/02/04 11:49:42.752855, 2] channel_open:  Creating a channel 43 with 64000 window and 32768 max packet
[2022/02/04 11:49:42.753275, 2] ssh_packet_global_request:  Received SSH_MSG_GLOBAL_REQUEST packet
[2022/02/04 11:49:42.753303, 2] ssh_packet_global_request:  UNKNOWN SSH_MSG_GLOBAL_REQUEST hostkeys-00@openssh.com, want_reply = 0
[2022/02/04 11:49:42.753315, 1] ssh_packet_global_request:  Invalid SSH_MSG_GLOBAL_REQUEST packet
[2022/02/04 11:49:42.792910, 2] ssh_packet_channel_open_conf:  Received a CHANNEL_OPEN_CONFIRMATION for channel 43:0
[2022/02/04 11:49:42.792947, 2] ssh_packet_channel_open_conf:  Remote window : 0, maxpacket : 32768
[2022/02/04 11:49:42.794975, 2] channel_rcv_change_window:  Adding 2097152 bytes to channel (43:0) (from 0 bytes)
[2022/02/04 11:49:42.794997, 2] channel_request:  Channel request subsystem success
[2022/02/04 11:49:42.822122, 2] grow_window:  growing window (channel 43:0) to 1280000 bytes
nc VERBOSE: Capability for <get-schema> support found.
nc VERBOSE: Capability for yang-library support not found.
ly VERBOSE: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
ly VERBOSE: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
nc VERBOSE: Retrieving data for schema "ietf-netconf", revision "2011-06-01".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "ietf-inet-types", revision "2013-07-15".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "ietf-netconf-acm", revision "2012-02-22".
nc VERBOSE: Reading schema from server via get-schema.
ly ERROR: Double-quoted string unknown special character '\.'. (Line number 192.)
ly ERROR: Parsing module "ietf-inet-types" failed.
ly ERROR: Double-quoted string unknown special character '\*'. (Line number 90.)
ly ERROR: Parsing module "ietf-netconf-acm" failed.
ly ERROR: Loading "ietf-netconf-acm" module failed.
ly VERBOSE: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
ly ERROR: Loading "ietf-netconf-acm" module failed.
ly ERROR: Parsing module "ietf-netconf" failed.
nc ERROR: Loading base NETCONF schema failed.
nc WARNING: Missing ietf-netconf schema in context, unable to send <close-session>.
ly ERROR: Value "admin" was not found in the dictionary.
ly ERROR: Value "10.52.141.158" was not found in the dictionary.
cmd_connect: Connecting to the 10.52.141.158:830 as user "admin" failed.

**Comment by michalvasko** [comment]
Right, then it seems you are still connecting to the obsolete *netopeer-server* that is running in the background, please stop it and uninstall it before trying to install *netopeer2-server*.

**Comment by deepthivemu** [comment]
Hi Michal, I could resolve the actual issue with edit-config on netopeer. The xml that I was using had some redundant nodes for the command edit-config. I just had to trim the xml file as in the attachment.

[trimmed _xml.txt](https://github.com/CESNET/netopeer/files/8015157/trimmed._xml.txt)

**Comment by michalvasko** [comment]
Fine, just do not expect any more support from me. Like I said, *netopeer* is obsolete and should not be used anymore.

**Comment by deepthivemu** [comment]
Sure. This was just an info. I will be moving with netopeer2 next. You can close this issue.
