### ISSUE TITLE
Send netconf message to netopeer server through ssh session, session force shutdown 

### ISSUE THREAD

**Issue by huangdihu** [CESNET/netopeer#28]
Hi, 

I have a netopeer server, and I connect to it through "ssh root@localhost -p 830 -s netconf" in bash.

Netconf server replied me with hello message.
But after that, I tried to send hello message and get rpc message through the ssh session, the ssh session was forced shutdown.
Is there any way to solve this problem? And do I need extra configuration of my netopeer server to be able to send netconf message through ssh session? I cannot use any existing netconf client, just pure bash. Thanks!

**Comment by michalvasko** [comment]
Hi,

I never tried what you're describing, but I gave it a shot. To my surprise, I did manage to communicate fine. However, using simple ssh as the client requires exact and thorough knowledge of the NETCONF protocol. For one, do not advertise "netconf:base:1.1" in the hello message, unless you want to count the length of every message you send, use 1.0 message delimiters. Other than that, it should work as one expects, even though this is a really uncomfortable way of using NETCONF.

Regards,
Michal
