### ISSUE TITLE
build netopeer server

### ISSUE THREAD

**Issue by JackLIN-F** [CESNET/netopeer#29]
Hi,
I build netopeer server.

....
checking for pkg-config... /usr/bin/pkg-config
checking for roff2html... no
checking for distro... redhat
checking for /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for uname... yes
checking for host architecture... x86_64
checking for lnctool... no
configure: error: "lnctool not found!"

**Comment by JackLIN-F** [comment]
Hi,
I check build libnetconf.

configure: WARNING: Due to missing pyang, lnctool will not work.
configure: creating ./config.status

so, lnctool not found!  right?

**Comment by rkrejci** [comment]
no, "missing pyang" means that pyang was not found. And lnctool uses pyang so it will not work.

**Comment by JackLIN-F** [comment]
Hi Rkrejci :

     Thanks
