### ISSUE TITLE
pyang: error: no such option: --features

### ISSUE THREAD

**Issue by JackLIN-F** [CESNET/netopeer#30]
Hi,
I build netopeer server. I have a problem:

...........
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
configure: generating validation files...
Usage: pyang [options] [<filename>...]

Validates the YANG module in <filename> (or stdin), and all its dependencies.

pyang: error: no such option: --features
Command 'pyang -p /home/SDN/netopeer-master/server/config/ -f dsdl --dsdl-no-documentation --dsdl-no-dublin-core -o /tmp/dsdlhKN55t.dsdl /home/SDN/netopeer-master/server/config/ietf-netconf-server.yin --features ietf-netconf-server:ssh,inbound-ssh' failed (2)
configure: error: Generating validation files for ietf-netconf-server failed.
[root@CentOS-6 server]#

**Comment by rkrejci** [comment]
make sure that you are using the latest pyang version:
```
$ pyang --version
pyang 1.5
```

**Comment by JackLIN-F** [comment]
# pyang --version
pyang 1.4.1

**Comment by rkrejci** [comment]
it is too old, get the latest version from github - https://github.com/mbj4668/pyang

**Comment by UnknowSelf** [comment]
# pyang --version
pyang 1.7.3
but I meet the same question

**Comment by rkrejci** [comment]
@UnknowSelf, if you really have **_the same_** output from our scripts, then contact pyang authors, because according to pyang docs, version 1.7.3 should support the `--features` option.

**Comment by UnknowSelf** [comment]
@rkrejci Thanks for your answer, I have resolved the problem,  Because te python version is too old.
I suggest to use python2.7 or latest version.

**Comment by aritrikdas** [comment]
I'm using pyang 2.0.2 but still facing the same issue.

**Comment by michalvasko** [comment]
Hi,
it supports the `--features` parameter according to its help, so you can ask them why it is not working, it is not a *netopeer* issue.

Regards,
Michal
