### ISSUE TITLE
undefined reference to `ssh_message_type'

### ISSUE THREAD

**Issue by JackLIN-F** [CESNET/netopeer#31]
Hi,
make file , found some error

........
server.c:(.text+0x788): undefined reference to `ssh_bind_free'
.obj/src/ssh/server_ssh.o: In function `netconf_session_thread':
server_ssh.c:(.text+0x50): undefined reference to `nc_session_accept_libssh_channel'
.obj/src/ssh/server_ssh.o: In function `sshcb_msg':
server_ssh.c:(.text+0x23c): undefined reference to `ssh_message_type'
server_ssh.c:(.text+0x248): undefined reference to `ssh_message_subtype'
server_ssh.c:(.text+0x394): undefined reference to `ssh_message_service_service'
server_ssh.c:(.text+0x3e8): undefined reference to `ssh_message_channel_request_open_reply_accept'
server_ssh.c:(.text+0x464): undefined reference to `ssh_message_auth_user'
server_ssh.c:(.text+0x4b4): undefined reference to `ssh_message_auth_kbdint_is_re

because libnetconf.so leak libssh 
./configure --disable-libssh

So, Need I disable this feature?

**Comment by michalvasko** [comment]
Hi,

if I understand it correctly, you compiled libnetconf without libssh support. This way SSH must be disabled in netopeer for it to compile, so yes, disable it in netopeer. I cleaned and updated these checks in netopeer, so now if configure succeeds, the compilation should finish without errors. Try it again, please, pay attention to the warnings/errors configure prints and let us know if you encounter any more compilation errors. Thanks.

**Comment by JackLIN-F** [comment]
Thanks
