### ISSUE TITLE
Questions for supporting "if-feature"

### ISSUE THREAD

**Issue by jinxud** [CESNET/netopeer#34]
Hi,
We want to support ‘if-feature’ in Libnetconf. After verify and analyzing the related source code, I have 1 questions for netopeer

parse_model_cfg

name = strdup(basename(model_path));
/*cut off the .yin suffix */
aux = strrchr(name, '.');

if the model files is like this. config@2015-06-25.yin. the name will be config@2015-06-25
then will call ncds_feature_enable(name, feature). but in models_list, the model name is without date. which will cause cannot find the model, and update the feature status failed.

Is my understanding right? Thanks a lot.

Thanks,

**Comment by michalvasko** [comment]
Hi,

if you look just a bit further in the code you can see that this name is used only for enabling features on this model. It is loaded into libnetconf using ncds_add_model(), which gets the model name from its top node "module", not the file name.

Regards,
Michal

**Comment by rkrejci** [comment]
The described problem was really there, but I already fixed it in #33. Please try to pull the current master and test if the fix works for you.

**Comment by jinxud** [comment]
yes, I got it. after I raise the issue 34, I noticed the problem was fixed. sorry for any inconvenience.
