### ISSUE TITLE
Question: How to get hostname

### ISSUE THREAD

**Issue by JackLIN-F** [CESNET/netopeer#35]
Hi,
   Connect netopeer-server and Netopeer server successfully initialized.
    I want to get-config hostname of ietf-system but rpc-reply data is null.
    Please help me how to do? I don't understand what's happen?
    I write debug at callback_systemns_system_systemns_hostname() function and nothing.

Thanks

================================
# ./netopeer-server -v4
netopeer-server[22724]: Shared memory location: /dev/shm/libnetconfshm
netopeer-server[22724]: POSIX SHM File Descriptor: 4 (568B).
netopeer-server[22724]: Failed to open semaphore directory "/dev/shm" (No such file or directory).
netopeer-server[22724]: ncds_features_parse: no feature definitions found in data model ietf-inet-types.
netopeer-server[22724]: ncds_features_parse: no feature definitions found in data model ietf-yang-types.
netopeer-server[22724]: ncds_features_parse: no feature definitions found in data model ietf-netconf-monitoring.
netopeer-server[22724]: ncds_features_parse: no feature definitions found in data model ietf-netconf-notifications.
netopeer-server[22724]: ncds_features_parse: no feature definitions found in data model nc-notifications.
netopeer-server[22724]: ncds_features_parse: no feature definitions found in data model notifications.
netopeer-server[22724]: ncds_features_parse: no feature definitions found in data model ietf-netconf-with-defaults.
netopeer-server[22724]: ncds_features_parse: no feature definitions found in data model ietf-netconf-acm.
netopeer-server[22724]: ncds_set_validation: Relax NG validator set (//var/lib/libnetconf//ietf-netconf-acm-config.rng)
netopeer-server[22724]: ncds_set_validation: Schematron validator set (//var/lib/libnetconf//ietf-netconf-acm-schematron.xsl)
netopeer-server[22724]: Datastore ietf-netconf-acm initiated with ID 8.
netopeer-server[22724]: Checking the default Events stream path //var/lib/libnetconf//streams/.
netopeer-server[22724]: Adding augment model "//etc/netopeer/cfgnetopeer/ietf-x509-cert-to-name.yin"
netopeer-server[22724]: ncds_features_parse: no feature definitions found in data model ietf-x509-cert-to-name.
netopeer-server[22724]: Adding static transapi "//etc/netopeer/cfgnetopeer/ietf-netconf-server.yin"
netopeer-server[22724]: ncds_new_internal: Relax NG validator set (/etc/netopeer/cfgnetopeer/ietf-netconf-server-config.rng)
netopeer-server[22724]: ncds_new_internal: Schematron validator set (/etc/netopeer/cfgnetopeer/ietf-netconf-server-schematron.xsl)
netopeer-server[22724]: Datastore ietf-netconf-server initiated with ID 1804289384.
netopeer-server[22724]: Setting the default SSH configuration for the ietf-netconf-server module...
netopeer-server[22724]: callback_srv_netconf_srv_listen_srv_port: SSH listening on the port 830
netopeer-server[22724]: Adding static transapi "//etc/netopeer/cfgnetopeer/netopeer-cfgnetopeer.yin"
netopeer-server[22724]: ncds_new_internal: Relax NG validator set (/etc/netopeer/cfgnetopeer/netopeer-cfgnetopeer-config.rng)
netopeer-server[22724]: ncds_new_internal: Schematron validator set (/etc/netopeer/cfgnetopeer/netopeer-cfgnetopeer-schematron.xsl)
netopeer-server[22724]: Datastore netopeer-cfgnetopeer initiated with ID 846930887.
netopeer-server[22724]: Setting the default configuration for the cfgnetopeer module...
netopeer-server[22724]: Setting the default configuration for the cfgnetopeer module SSH...
netopeer-server[22724]: Netopeer server successfully initialized.
netopeer-server[22724]: Received an SSH message "request-service" of subtype "ssh-userauth".
netopeer-server[22724]: Received an SSH message "request-auth" of subtype "password".
netopeer-server[22724]: User 'root' authenticated.
netopeer-server[22724]: Received an SSH message "request-channel-open" of subtype "session".
netopeer-server[22724]: Received an SSH message "request-channel" of subtype "subsystem".
netopeer-server[22724]: Writing message (session 1): <?xml version="1.0" encoding="UTF-8"?>
< hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:base:1.1</capability>
    <capability>urn:ietf:params:netconf:capability:writable-running:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:startup:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:interleave:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:notification:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:validate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:validate:1.1</capability>
    <capability>urn:ietf:params:netconf:capability:with-defaults:1.0?basic-mode=explicit&amp;also-supported=report-all,report-all-tagged,trim,explicit</capability>
    <capability>urn:ietf:params:netconf:capability:url:1.0?scheme=scp,file</capability>
    <capability>urn:cesnet:tmc:netopeer:1.0?module=netopeer-cfgnetopeer&amp;revision=2015-05-19&amp;features=ssh,dynamic-modules</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-server?module=ietf-netconf-server&amp;revision=2014-01-24&amp;features=ssh,inbound-ssh,outbound-ssh</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-x509-cert-to-name?module=ietf-x509-cert-to-name&amp;revision=2013-03-26</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-acm?module=ietf-netconf-acm&amp;revision=2012-02-22</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults?module=ietf-netconf-with-defaults&amp;revision=2010-06-09</capability>
    <capability>urn:ietf:params:xml:ns:netconf:notification:1.0?module=notifications&amp;revision=2008-07-14</capability>
    <capability>urn:ietf:params:xml:ns:netmod:notification?module=nc-notifications&amp;revision=2008-07-14</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-notifications?module=ietf-netconf-notifications&amp;revision=2011-08-07</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring?module=ietf-netconf-monitoring&amp;revision=2010-10-04</capability>
    <capability>urn:ietf:params:xml:ns:netconf:base:1.0?module=ietf-netconf&amp;revision=2011-03-08&amp;features=writable-running,candidate,rollback-on-error,validate,startup,url</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-yang-types?module=ietf-yang-types&amp;revision=2013-07-15</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-inet-types?module=ietf-inet-types&amp;revision=2010-09-24</capability>
  </capabilities>
  <session-id>1</session-id>
</hello>
netopeer-server[22724]: Received message (session 1): <?xml version='1.0' encoding='UTF-8'?>
< hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:capability:writable-running:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:confirmed-commit:1.1</capability>
    <capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:url:1.0?scheme=http,ftp,file,https,sftp</capability>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:base:1.1</capability>
    <capability>urn:ietf:params:netconf:capability:validate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:xpath:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:notification:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:validate:1.1</capability>
    <capability>urn:ietf:params:netconf:capability:startup:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:with-defaults:1.0?basic-mode=explicit&amp;also-supported=trim,report-all,report-all-tagged</capability>
    <capability>urn:ietf:params:netconf:capability:interleave:1.0</capability>
  </capabilities>
</hello>
netopeer-server[22724]: Adding new event (5)
netopeer-server[22724]: Created session 1 for user 'root' (UID 0) (recovery)
netopeer-server[22724]: New server session for 'root' with ID 1

netopeer-server[22724]: Received message (session 1): <?xml version='1.0' encoding='UTF-8'?>
<rpc message-id="0" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <get-config>
    <source>
      <running/>
    </source>
    <filter type="subtree">
      <sys:system xmlns:sys="urn:ietf:params:xml:ns:yang:ietf-system">
        <sys:hostname/>
      </sys:system>
    </filter>
  </get-config>
</rpc>
netopeer-server[22724]: Writing message (session 1): <?xml version="1.0" encoding="UTF-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="0">
  <data/>
</rpc-reply>
![1](https://cloud.githubusercontent.com/assets/12999678/8518506/45b5c1a4-23fd-11e5-9d8e-6e4066f2bb34.jpg)

**Comment by michalvasko** [comment]
Hi,

I did exactly what you and everything worked as expected. It's hard for me to guess the problem, but one can be seen from your netopeer log. The shared memory size was increased from your 568b to 600b quite some time ago, so I must assume you're using some really old libnetconf, please use version 0.10.0. If that won't solve your problem, try reinstalling everything from scratch, libnetconf, netopeer, and cfgsystem transAPI module.

Regards,
Michal

**Comment by JackLIN-F** [comment]
Hi~
Thanks your help.
The libnetconf version is 0.10.0. 
Root cause: I forgot run cfgsystem transAPI module. :p
