### ISSUE TITLE
./configure error for transAPI/cfgsystem

### ISSUE THREAD

**Issue by JackLIN-F** [CESNET/netopeer#36]
Hi,
I need the augeas  package. So, where is the package to download and what is version?

[root@CentOS-6 cfgsystem]# yum -y install augeas-libs
Loaded plugins: fastestmirror, refresh-packagekit, security
Loading mirror speeds from cached hostfile
Setting up Install Process
Package augeas-libs-0.9.0-1.el6.x86_64 already installed and latest version
Nothing to do

Thanks

====================================
configure: error: Package requirements (augeas >= 1.0.0) were not met:

No package 'augeas' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables AUGEAS_CFLAGS
and AUGEAS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by michalvasko** [comment]
Hi,

CentOS usually has really old packages so you should have already got used to having to manually download packages/sources when using recent software. You can find the newest tarballs of augeas on http://download.augeas.net/ and you need at least version 1.0, obviously. Please post real issues with netopeer here, not basic Linux ones.

Regards,
Michal

**Comment by JackLIN-F** [comment]
Hi~
Thanks
