### ISSUE TITLE
Question: netopeer-cli and ssh shell

### ISSUE THREAD

**Issue by JackLIN-F** [CESNET/netopeer#37]
Hi,
I can use netopeer-cli to get-config.But use ssh shell is fail.
What is difference between two method ?
Thanks

$ ssh root@172.19.96.152 -p 830 -s netconf
Interactive SSH Authentication
Type your password
Password:
<?xml version="1.0" encoding="UTF-8"?>
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities> ........................
</hello>
]]>]]><?xml version='1.0' encoding='UTF-8'?>
<rpc message-id="1" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <get-config>
    <source>
      <candidate/>
    </source>
    <filter type="subtree">
      <sys:system xmlns:sys="urn:ietf:params:xml:ns:yang:ietf-system"/>
    </filter>
  </get-config>
</rpc>
]]>]]>
Connection to 172.19.96.152 closed by remote host.

netopeer-server display:
netopeer-server[11860]: Adding new event (6)
netopeer-server[11860]: netconf_session_thread: failed to create a new NETCONF session
netopeer-server[11860]: Freeing session for 'root'

=========================
Use netopeer-cli 
netconf> get-config
  Select target datastore (running|startup|candidate|url:<dsturl>): running
  Result:
<system xmlns="urn:ietf:params:xml:ns:yang:ietf-system">
    <hostname>CentOS-6.2-test</hostname>
    <clock>
      <timezone-name>GMT</timezone-name>
    </clock>......................

**Comment by michalvasko** [comment]
Hi,

please refer to the issue #28.

Regards,
Michal
