### ISSUE TITLE
No transAPI "commit" callback registration. How notify device driver(s) of configuration changes?

### ISSUE THREAD

**Issue by tdenesyk** [CESNET/netopeer#40]
Hi All,
I'm a newbie. I apologize in advance if this is a stupid question.

I'm trying to implement firmware that will repond to the 'commit' action by applying the new configuration data to various device drivers on my circuit card.

I don't see how to associate a transAPI callback with the 'commit' netconf action.
Is there a different way to accomplish this?

I'm suspecting that I'm just not 'getting' something.

Thanks,
Tom

**Comment by tdenesyk** [comment]
Hi All,
Ok I have the transition function figured out sort of. I think it should also fire on a "commit' but it doesn't. 

If it did, it would explain why there I couldn't find a distinct  call-back mechanism for 'commit'.

Tom

**Comment by michalvasko** [comment]
Hi Tom,
there is, indeed, no callback to be called on the commit operation because none is needed. The basic mechanism is having a <running> and a <startup> datastore. On any (partial) change of the <running> configuration, the corresponding callbacks are called, defined in a transAPI module. The <candidate> datastore extension does not need any special callback. Just modify it and when you commit, the changes are reflected in the <running> configuration and the standard callbacks are called. You should be able to do everything you need this way.

Regards,
Michal

**Comment by tdenesyk** [comment]
Hi Michal,
Thanks for the quick reply.

I think there is something about candidate/running stores that I'm missing.
I see the call-back called when I edit-config  the running store.

But I don't see it called when a commit is performed after doing an edit config on the candidate.

My reasoning is that in the case of candidate having different content than running, a commit (which copies candidate to running) should trigger the call-back.

Hmm, for that matter a copy-config from candidate to running should trigger the call back too. I'll try that when I get into the office this morning.

Comments?

Cheers,
Tom





Sent from my Samsung Galaxy Tab®4


-------- Original message --------

**Comment by tdenesyk** [comment]
Hi Michal
I now understand how the config change call-callback mechanism is supposed to work..

But the call-back is NOT being called in the case of commit and candidate has different data than running.. 

Regards,
Tom

**Comment by tdenesyk** [comment]
Hey Michal,
There is a copy operation occurring. 
Using 'get-config --filter", I can see that the running has same data as the candidate after the commit. 
But the call-back is never called.

Tom

**Comment by michalvasko** [comment]
Hi Tom,
what you're describing is weird and I would probably need to see your transAPI module source, the model it uses, the running configuration before the commit, and lastly the candidate configuration before the commit.

Regards,
Michal

**Comment by tdenesyk** [comment]
Ok.
I have a test device called blade.
I'll send you the yang, the transAPI c file, and the config file.

Thanks,
Tom




Sent from my Samsung Galaxy Tab®4


-------- Original message --------

**Comment by tdenesyk** [comment]
Hi Michal,
Before I send pursue my example blade model any further...  Perhaps it is easier to to talk about the turing-machine.

I tried the turing-machine - added a trace call (nc_verb_verbose) to each function in turing-machine.c.

I get the same result from the turing-machine as with my blade model. (turing transapi_data_callback is only called when I edit-config to the running store.)

Stepping through the intialization of turing machine I got to transapi.c: 409
        if (xmldiff_set_priorities(diff, ds->tapi_callbacks, ds->tapi_callbacks_count) != EXIT_SUCCESS) {
            VERB("Model \"%s\" transAPI: there was not a single callback found for the configuration change.", ds->data_model->name);


I don't understand why xmldiff_set_priorities would fail. I don't think this is normal. (Confirm?)
I am now pursuing this question. I'm suspecting something basic about the netconf/netopeer installation on my pc.

What do you think?

Regards,
Tom

**Comment by tdenesyk** [comment]
Hi Michal,
I reduced my model to the simplest possible. There is one int32 test variable.

In the zip you will find

·        the config of ‘running’ both before and after the commit. (running_before.xml, running_after.xml)

·        Config of candidate

·        simple.yang, simple.yin

·        simple.c, with trace statement on the callback.

·        and simple.xml and simple99.xml. One file sets the test variable to 1 and the other to 99

As I said earlier, the only way in, my installation, to get the callback to fire is to edit-config to the running store.

I get same behavior with turing-machine and when I modify the interfaces or system devices.

Cheers,
Tom

**Comment by michalvasko** [comment]
Hi Tom,
even though you did not include the zip, I believe I have fixed your problem :) I am sorry for not trying it myself sooner, I just thought that such a fundamental bug could not be present. The opposite is true and the last commit in libnetconf should fix this issue. Again, I'm sorry for all the effort you put into this report, thanks, and please verify that it works with the newest libnetconf.

Regards,
Michal

**Comment by tdenesyk** [comment]
Hi Michal,
If I had a dollar for every time I failed to attach a zip, I'd be a wealthy man. Sorry about that.

I'll test the fix today.

After the 'commit' is tested I'll be trying out the file callbacks. I may have questions about that for you too.

Thank you.

Tom




Sent from my Samsung Galaxy Tab®4


-------- Original message --------

**Comment by tdenesyk** [comment]
The fix is works well.

Thank you.

Tom
