### ISSUE TITLE
If there exists a netopeer-server instance, then start another netopeer-server instance twice will kill the existed instance.

### ISSUE THREAD

**Issue by classcwnd** [CESNET/netopeer#41]
Several issues:
1) If there exists a netopeer-server instance, then start another netopeer-server instance twice will kill the existed instance. I think the existed instance shall not be killed by other netopeer-server instance.

2) We found even there is no netopeer-server instance, the /tmp/netopeer.socket is still there sometime. That's to say /tmp/netopeer.socket is not removed when netopeer-server was quit last time.
This results in netopeer-server can not startup at the first time. But it can startup at second time without removing /tmp/netopeer.socket manually.

**Comment by michalvasko** [comment]
Hi,

what kind of netopeer version are you using? The one from master does not use "/tmp/netopeer.socket" for quite some time.

Regards,
Michal

**Comment by classcwnd** [comment]
It's 0.9.2.

**Comment by michalvasko** [comment]
Hi Yu,

I find that hard to believe. You are likely using libnetconf 0.9.2, which is old, use 0.10.0. Also, the newest netopeer version is 0.8.0, which works well with libnetconf 0.10.0. This should solve your problems.

Regards,
Michal
