### ISSUE TITLE
netconf server doesn't work well with 'subscribe' from two cli's

### ISSUE THREAD

**Issue by tomdenesyk** [CESNET/netopeer#42]
Started a cli and connected to localhost, then 'subscribe'.
Started a second cli on a different station, then 'subscribe'.

Use 'edit-config' to change configuration.

Saw notification on one cli but not on the other.

Disconnected one cli and caused new notifications - didn't see notifications anywhere.

**Comment by michalvasko** [comment]
Hi,

you will have to describe what you did exactly, all the steps and what was happening. I tried connecting two CLIs. I connected first, subscribed. Then I connected second (CLI 1 notif), subscribed. I sent edit-config using first CLI (CLI 2 notif). I disconnected the second CLI (CLI 1 notif) and then terminated the server (CLI 1 notif). Everything behaved as expected.

Regards,
Michal

**Comment by tomdenesyk** [comment]
Hi Michal,

Here's my recipe...


1) using the turing-machine

2) start cli #1 and connect using local host

3) on cli#1 issue a 'subscribe' with no options

4) start cli#2 and connect using the ip address of the pc running the server.

5) on cli#2 issue a 'subscribe' with no options.

6) from cli#1

user-rpc
 <initialize xmlns="http://example.net/turing-machine">
    <tape-content>ABC</tape-content>
  </initialize>

user-rpc
    <run xmlns="http://example.net/turing-machine"/>
7) at the conclusion of the <run> there is a notification on cli#2 but not on cli#1.


I tried various combinations of disconnect/connect/subscribe on the two cli's and never saw notifications on both cli's when both were connected and subscribed.


Regards,

Tom




________________________________

**Comment by tomdenesyk** [comment]
Hi Michal,

I think the problem is somehow related to  both cli's having a stream name of "NETCONF".



ncntf_stream_get (stream=0x7fffd4003330 "NETCONF") at src/notifications.c:602
#1  0x00007ffff76e874c in ncntf_subscription_check (subscribe_rpc=0x7fffd4000ad0) at src/notifications.c:2262
#2  0x0000000000409d7e in np_ssh_client_netconf_rpc (client=0x8dbda0) at src/ssh/server_ssh.c:562
#3  0x000000000040422c in client_main_thread (arg=0x8dbda0) at src/server.c:243
#4  0x00007ffff7145182 in start_thread (arg=0x7fffea3e5700) at pthread_create.c:312
#5  0x00007ffff6e7247d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111


regards,
Tom

________________________________

**Comment by rkrejci** [comment]
Should be now fixed in last libnetconf (see the referenced libnetconf issue above).
