### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by JackLIN-F** [CESNET/netopeer#44]
Hi,
I first see the message: Client session closed, removing it.  then Segmentation fault!!!
I guess some error.

Thanks,

===================================================
ofc-server[1710]: Adding new event (6)
ofc-server[1710]: Created dummy session 0 for user 'root' (UID 0) - recovery session
ofc-server[1710]: Created dummy session 0 for user 'root' (UID 0) - recovery session
ofc-server[1710]: Created dummy session 0 for user 'root' (UID 0) - recovery session
ofc-server[1710]: Created dummy session 0 for user 'root' (UID 0) - recovery session
ofc-server[1710]: Created dummy session 0 for user 'root' (UID 0) - recovery session
ofc-server[1710]: Created dummy session 0 for user 'root' (UID 0) - recovery session
ofc-server[1710]: Created dummy session 0 for user 'root' (UID 0) - recovery session
ofc-server[1710]: Created dummy session 0 for user 'root' (UID 0) - recovery session
ofc-server[1710]: Created dummy session 0 for user 'root' (UID 0) - recovery session
ofc-server[1710]: Created dummy session 0 for user 'root' (UID 0) - recovery session
ofc-server[1710]: Created dummy session 0 for user 'root' (UID 0) - recovery session
ofc-server[1710]: Created dummy session 0 for user 'root' (UID 0) - recovery session
ofc-server[1710]: Received an SSH message "request-service" of subtype "ssh-userauth".
ofc-server[1710]: Received an SSH message "request-auth" of subtype "none".
ofc-server[1710]: Received an SSH message "request-auth" of subtype "password".
ofc-server[1710]: User 'root' authenticated.
ofc-server[1710]: Received an SSH message "request-channel-open" of subtype "session".
ofc-server[1710]: Received an SSH message "request-channel" of subtype "subsystem".
ofc-server[1710]: Writing message (session 267): <?xml version="1.0" encoding="UTF-8"?>
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:base:1.1</capability>
    <capability>urn:ietf:params:netconf:capability:writable-running:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:startup:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:interleave:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:notification:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:validate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:validate:1.1</capability>
    <capability>urn:ietf:params:netconf:capability:with-defaults:1.0?basic-mode=explicit&amp;also-supported=report-all,report-all-tagged,trim,explicit</capability>
    <capability>urn:ietf:params:netconf:capability:url:1.0?scheme=scp,file</capability>
    <capability>urn:onf:config:yang?module=of-config&amp;revision=2015-02-11</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-system?module=ietf-system&amp;revision=2014-08-06</capability>
    <capability>urn:cesnet:tmc:netopeer:1.0?module=netopeer-cfgnetopeer&amp;revision=2015-05-19&amp;features=ssh,dynamic-modules</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-server?module=ietf-netconf-server&amp;revision=2014-01-24&amp;features=ssh,inbound-ssh,outbound-ssh</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-x509-cert-to-name?module=ietf-x509-cert-to-name&amp;revision=2013-03-26</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-acm?module=ietf-netconf-acm&amp;revision=2012-02-22</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults?module=ietf-netconf-with-defaults&amp;revision=2010-06-09</capability>
    <capability>urn:ietf:params:xml:ns:netconf:notification:1.0?module=notifications&amp;revision=2008-07-14</capability>
    <capability>urn:ietf:params:xml:ns:netmod:notification?module=nc-notifications&amp;revision=2008-07-14</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-notifications?module=ietf-netconf-notifications&amp;revision=2011-08-07</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring?module=ietf-netconf-monitoring&amp;revision=2010-10-04</capability>
    <capability>urn:ietf:params:xml:ns:netconf:base:1.0?module=ietf-netconf&amp;revision=2011-03-08&amp;features=writable-running,candidate,rollback-on-error,validate,startup,url</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-yang-types?module=ietf-yang-types&amp;revision=2013-07-15</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-inet-types?module=ietf-inet-types&amp;revision=2010-09-24</capability>
  </capabilities>
  <session-id>267</session-id>
</hello>
ofc-server[1710]: Client session closed, removing it.
ofc-server[1710]: Freeing session for 'root'
Segmentation fault
#

**Comment by michalvasko** [comment]
Hi,

for one, it would be nice if you included a detailed description of what you did so I can easily reproduce your problem. Secondly, you are using a modified old netopeer, which actually has its own github page so I am left wondering why did you post your issue here. My guess, though, is that some more recent libnetconf changes are causing the SEGFAULT, so if you use libnetconf 0.9.2, everything should work.

Regards,
Michal

**Comment by JackLIN-F** [comment]
Hi~
I never see this error using latest libnetconf  and netopeer.
