### ISSUE TITLE
How to enable call-home?

### ISSUE THREAD

**Issue by wirelessr** [CESNET/netopeer#46]
Hi,

I know the call-home feature on netopeer-cli can be activated by "netconf> listen"

But, how about netopeer-server?

How to trigger netopeer-server to connect to a specific call-home server?

**Comment by michalvasko** [comment]
Hi,

just look into the ietf-netconf-server model supported in netopeer, it includes Call Home settings. So adjust the running configuration accordingly and it should start connecting immediately.

Regards,
Michal

**Comment by wirelessr** [comment]
Hi,

I try to use this config:

<netconf xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <ssh>
    <call-home>
      <applications>
        <application nc:operation="create">
          <name>root</name>
            <servers>
              <server>
                <address>192.168.1.1</address>
                <port>6666</port>
              </server>
            </servers>
        </application>
      </applications>
    </call-home>
  </ssh>
</netconf>

And the result is:

netconf> edit-config running
NETCONF error: operation-failed (application) - Datastore fails to validate (Extra element call-home in interleave)
NETCONF error: operation-failed (application) - Datastore fails to validate (Element ssh failed to validate content)

Is there any problem?

**Comment by michalvasko** [comment]
Hi,

yes, there is a problem, look at the model carefully. You're missing the mandatory host-key list in the host-keys container, at least one entry must be present.

Regards,
Michal

**Comment by wirelessr** [comment]
Hi,

Got it, thanks.

But I don't know what the meaning of "name". Is the local user at remote server?

**Comment by michalvasko** [comment]
Hi,

the name is likely anything you decide it is, the simplest would be the path to a file with it. Nevertheless, netopeer currently ignores this, it must just be present for the validation to pass. If you look at the current draft, it seems there will be another model, which will deal with host keys exclusively and it will be referenced from the netconf-server one. We'll implement it once the standard is final.

Regards,
Michal

**Comment by wirelessr** [comment]
Hi,

One more question. What are the cert-maps and psk-maps needed by call-home with TLS?

**Comment by michalvasko** [comment]
Hi,

actually, neither of what you mentioned is needed by TLS Call Home, look at the model again. If nothing else, you don't have to support either as they depend on a feature each. So, cert-maps and psk-maps are general for TLS, you can learn what cert-maps are in the ietf-x509-cert-to-name model. PSK was removed in the later drafts, you need not to worry about that, we do not support it in netopeer.

Regards,
Michal

**Comment by wirelessr** [comment]
Thanks, that really help.
