### ISSUE TITLE
Is it possible to start multiple netopeer servers daemon instances on multi IP interface Linux box ?

### ISSUE THREAD

**Issue by aadimurthy** [CESNET/netopeer#49]
Currently i am able to start netopeer server on Linux box listening on single IP address .
But i want start the different server daemons and each has to listen on individual IP addresses hosted on same Linux machine
Could we only have one netopeer daemon per one Linux OS ?Is it not possible to start different daemons running with independent database on same machine just like OpenLDAP server ?

**Comment by michalvasko** [comment]
Hi,

this should be possible although not tested much so you may encounter some issues (which we will be happy to fix as long as they do not require bigger changes). What exactly is your problem, did you try anything and it did not work or are you just asking whether it is possible?

Regards,
Michal

**Comment by aadimurthy** [comment]
Currently we have netconf manager/client  which can handle the bulk number of  netconf agents/server in a network and i have to test this 
I am able to test my manger with single netopeer/ netconf server successfully .
But that's not my complete use-case  . i need to test scalability of manager by starting the multiple severs instances with individual IPs and database as many as possible on single linux machine (16 core 64GB RAM ) 
I haven't tried much yet on this and i am even trying to change the listening address  to another in same machine.
Is there any procedure/configuration  i need follow to run multiple independent instances ?

**Comment by michalvasko** [comment]
Hi,

then like I said, it should be possible, but not exactly user-friendly.

For one, the installation process is tailored to install one instance of Netopeer. You can execute it more times, but it will always read the same configuration (and thus wanting to listen on the same addresses, which must inevitably fail), so this will have to be adjusted manually. Nevertheless, it may be enough to configure every instance with different module directory (configure parameter `--with-modules-dir`).

Secondly, libnetconf defines an exact limit on concurrently running applications. If you pass this limit, you will see verbose messages and if this new instance crashes, it will not be notified about it on the next run. Other than that I believe it should work properly, you can also try adjusting this limit in libnetconf netconf_internal.h, the macro NC_APPS_MAX (default is 10).

Right now I can't think of any other problems you may encounter. Please let us know what did you find out. Naturally, we will also try to provide support if you get stuck on something.

Regards,
Michal

**Comment by aadimurthy** [comment]
Well ! this is luring me to try this ! Thanks Michal for your info. will try and let u know if any issue persists

**Comment by krishnakumar4a4** [comment]
Hi @aadimurthy and @michalvasko,

I have tried the multiple instances of netopeer(on different ports of same IP or on different IP's on the same linux box) on a single linux machine with a simple tweak in the **netconf_server_transapi.c** file. 

However the _modules dir(--sysconfdir)_, _datastore_ and _netopeer-manager_ has to be unique for each instance.
> At first I changed the port and IP address in the **_callback_srv_netconf_srv_listen_srv_port_** function by just hardcoding the port number(changed new_port  variable to 831) and IP address(replaced "::0" to "127.0.0.3") for the **_add_bind_dir_** function call, which eventually the changed the port and IP address of my netopeer-server after building it with the following steps
```add_bind_addr(&netopeer_options.binds, transport, "::0", new_port);```
changed to....
```add_bind_addr(&netopeer_options.binds, transport, "127.0.0.3", 831);```

```
make clean
autoreconf --force --install
./configure --sysconfdir=/etc/netopeer_1 --prefix=/usr 
make
make install
```
<h1>Note:</h1> 
>After doing the above steps, the _netopeer-server_ and _netopeer-manager_ scripts are modified locally. We have to use only those scripts to start the server and also to add models to it. These two scripts are unique for each unique IP and port combination of netopeer instance.
>We have to copy these scripts to some other location to reuse them as these scripts will be modified each time the server is built with different port and IP address.

I have repeated the above steps for multiple times with different IP and port combinations and were able to start multiple netopeer instances on the same linux box.

RAM utilization for **3 netopeer instances** without any load is barely less than **30MB** which is acceptable value in our case.

Please get back to me for queries and feedback on this.

Regards,
**_Krishna_**

**Comment by aadimurthy** [comment]
Great ! Krishna .Even i tried in similar way and able to start multiple instances . Thanks for detailed explanation  !!

**Comment by michalvasko** [comment]
Hi,

thanks for the information and trying it out. However, I don't think that modifying **add_bind_addr** is necessary. It just adds addresses based on the configuration. So if you have a separate configuration for each *netopeer* instance, you can add those addresses into their configuration, each having a different one.

Regards,
Michal

**Comment by LilyCuili** [comment]
it is of much use for me

**Comment by LilyCuili** [comment]
Hello,
I met with a problem when install multi netopeer server instances.
under path ../netopeer/server
first I install one netopeer server as below:
./configure --sysconfdir=/etc/netopeer_1 --prefix=/usr/local/netopeer_1
make
make install


and then I install another one:
./configure --sysconfdir=/etc/netopeer_2 --prefix=/usr/local/netopeer_2
make
make install

now I the issue is that when I start  /usr/local/netopeer_2/bin/netopeer-server -d
when I start netconf client by ssh command,it will read datastore-server.xml under path :
/etc/netopeer_1/netopeer/cfgnetopeer
not /etc/netopeer_2/netopeer/cfgnetopeer
Is it because that I didn't "make clean" and "autoreconf --force --install"

**Comment by LilyCuili** [comment]
I attached the netopeer server's log when start /usr/local/netopeer_2/bin/netopeer-server -d
from the log can see it find some files under 
/etc/netopeer_1/netopeer/cfgnetopeer
I can't find the reason

**Comment by LilyCuili** [comment]
cuili@cuili-H81M-DS2-D:/usr/local/netopeer_3/bin$ sudo ./netopeer-server -v3
netopeer-server[2641]: Shared memory location: /dev/shm/libnetconfshm
netopeer-server[2641]: Shared memory file libnetconfshm already exists - opening
netopeer-server[2641]: POSIX SHM File Descriptor: 4 (600B).
netopeer-server[2641]: ncds_features_parse: no feature definitions found in data model ietf-inet-types.
netopeer-server[2641]: ncds_features_parse: no feature definitions found in data model ietf-yang-types.
netopeer-server[2641]: ncds_features_parse: no feature definitions found in data model ietf-netconf-monitoring.
netopeer-server[2641]: ncds_features_parse: no feature definitions found in data model ietf-netconf-notifications.
netopeer-server[2641]: ncds_features_parse: no feature definitions found in data model nc-notifications.
netopeer-server[2641]: ncds_features_parse: no feature definitions found in data model notifications.
netopeer-server[2641]: ncds_features_parse: no feature definitions found in data model libnetconf-notifications.
netopeer-server[2641]: ncds_features_parse: no feature definitions found in data model ietf-netconf-with-defaults.
netopeer-server[2641]: ncds_features_parse: no feature definitions found in data model ietf-netconf-acm.
netopeer-server[2641]: ncds_set_validation: Relax NG validator set (//var/lib/libnetconf//ietf-netconf-acm-config.rng)
netopeer-server[2641]: ncds_set_validation: Schematron validator set (//var/lib/libnetconf//ietf-netconf-acm-schematron.xsl)
netopeer-server[2641]: Datastore ietf-netconf-acm initiated with ID 9.
netopeer-server[2641]: Checking the default Events stream path //var/lib/libnetconf//streams/.
netopeer-server[2641]: Reading configuration for NETCONF-server module failed
netopeer-server[2641]: Starting necessary NETCONF server plugin failed!
cuili@cuili-H81M-DS2-D:/usr/local/netopeer_3/bin$ ./netopeer-server -d
cuili@cuili-H81M-DS2-D:/usr/local/netopeer_3/bin$ sudo ./netopeer-server -v3
netopeer-server[2683]: Shared memory location: /dev/shm/libnetconfshm
netopeer-server[2683]: Shared memory file libnetconfshm already exists - opening
netopeer-server[2683]: POSIX SHM File Descriptor: 4 (600B).
netopeer-server[2683]: ncds_features_parse: no feature definitions found in data model ietf-inet-types.
netopeer-server[2683]: ncds_features_parse: no feature definitions found in data model ietf-yang-types.
netopeer-server[2683]: ncds_features_parse: no feature definitions found in data model ietf-netconf-monitoring.
netopeer-server[2683]: ncds_features_parse: no feature definitions found in data model ietf-netconf-notifications.
netopeer-server[2683]: ncds_features_parse: no feature definitions found in data model nc-notifications.
netopeer-server[2683]: ncds_features_parse: no feature definitions found in data model notifications.
netopeer-server[2683]: ncds_features_parse: no feature definitions found in data model libnetconf-notifications.
netopeer-server[2683]: ncds_features_parse: no feature definitions found in data model ietf-netconf-with-defaults.
netopeer-server[2683]: ncds_features_parse: no feature definitions found in data model ietf-netconf-acm.
netopeer-server[2683]: ncds_set_validation: Relax NG validator set (//var/lib/libnetconf//ietf-netconf-acm-config.rng)
netopeer-server[2683]: ncds_set_validation: Schematron validator set (//var/lib/libnetconf//ietf-netconf-acm-schematron.xsl)
netopeer-server[2683]: Datastore ietf-netconf-acm initiated with ID 9.
netopeer-server[2683]: Checking the default Events stream path //var/lib/libnetconf//streams/.
netopeer-server[2683]: Adding augment model "/etc/netopeer_1/netopeer/cfgnetopeer/ietf-x509-cert-to-name.yin"
netopeer-server[2683]: ncds_features_parse: no feature definitions found in data model ietf-x509-cert-to-name.
netopeer-server[2683]: Adding static transapi "/etc/netopeer_1/netopeer/cfgnetopeer/ietf-netconf-server.yin"
netopeer-server[2683]: ncds_new_internal: Relax NG validator set (/etc/netopeer_1/netopeer/cfgnetopeer/ietf-netconf-server-config.rng)
netopeer-server[2683]: ncds_new_internal: Schematron validator set (/etc/netopeer_1/netopeer/cfgnetopeer/ietf-netconf-server-schematron.xsl)
netopeer-server[2683]: "ssh" features in "ietf-netconf-server" module enabled.
netopeer-server[2683]: "inbound-ssh" features in "ietf-netconf-server" module enabled.
netopeer-server[2683]: "outbound-ssh" features in "ietf-netconf-server" module enabled.
netopeer-server[2683]: Datastore ietf-netconf-server initiated with ID 1804289384.
netopeer-server[2683]: Setting the default SSH configuration for the ietf-netconf-server module...
netopeer-server[2683]: callback_srv_netconf_srv_listen_srv_port: SSH listening on the port 830
netopeer-server[2683]: Transapi calling callback /A:netconf/A:ssh/A:listen/A:port with op REM.
netopeer-server[2683]: callback_srv_netconf_srv_listen_srv_port: SSH stopped listening on the port 830
netopeer-server[2683]: Transapi calling callback /A:netconf/A:ssh/A:listen/A:interface with op ADD.
netopeer-server[2683]: callback_srv_netconf_srv_listen_srv_interface: SSH listening on the address 172.16.75.143:831
netopeer-server[2683]: Adding static transapi "/etc/netopeer_1/netopeer/cfgnetopeer/netopeer-cfgnetopeer.yin"
netopeer-server[2683]: ncds_new_internal: Relax NG validator set (/etc/netopeer_1/netopeer/cfgnetopeer/netopeer-cfgnetopeer-config.rng)
netopeer-server[2683]: ncds_new_internal: Schematron validator set (/etc/netopeer_1/netopeer/cfgnetopeer/netopeer-cfgnetopeer-schematron.xsl)
netopeer-server[2683]: "dynamic-modules" features in "netopeer-cfgnetopeer" module enabled.
netopeer-server[2683]: "ssh" features in "netopeer-cfgnetopeer" module enabled.
netopeer-server[2683]: Datastore netopeer-cfgnetopeer initiated with ID 846930887.
netopeer-server[2683]: Setting the default configuration for the cfgnetopeer module...
netopeer-server[2683]: Setting the default configuration for the cfgnetopeer module SSH...
netopeer-server[2683]: Netopeer server successfully initialized.

**Comment by LilyCuili** [comment]
I have found the root cause.
I 'make clean' but failed,then I ignore it to configure next.
I should 'make clean' before ./configure next netopeer server.
now it works well.thanks

**Comment by Smile004** [comment]
Hi @krishnakumar4a4,
I have a query, i need to start netopeer server with different port (than default 830), 
I have changed  <default value="830"/> to <default value="840"/> in file "ietf-netconf-server.yin" in the location /usr/local/etc/netopeer/cfgnetopeer .
Then i started ./netopeer-server but still it is listening on default 830 port.
How i need to configure to make it work with port 840???
Please help


Regards,
Smile004

**Comment by LilyCuili** [comment]
Can't make NETOPEER server to listen on IPv4 only or a specific port?
You need to change the startup config in /usr/local/etc/netopeer/cfgnetopeer/datastore-server.xml like the following:

<?xml version="1.0" encoding="UTF-8"?>
<datastores xmlns="urn:cesnet:tmc:datastores:file">
  <running lock=""/>
  <startup lock="">
    <netconf xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
      <ssh>
        <listen>
          <interface>
            <address>0.0.0.0</address>
            <port>830</port>
          </interface>
        </listen>
      </ssh>
    </netconf>
  </startup>
  <candidate modified="false" lock=""/>
</datastores>

**Comment by LilyCuili** [comment]
http://www.seguesoft.com/index.php/how-to-set-up-netopeer-server-to-use-with-netconfc#Inctool

**Comment by LilyCuili** [comment]
You need to change the startup config in /usr/local/etc/netopeer/cfgnetopeer/datastore-server.xml like the following:
<?xml version="1.0" encoding="UTF-8"?>
<datastores xmlns="urn:cesnet:tmc:datastores:file">
  <running lock=""/>
  <startup lock="">
    <netconf xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
      <ssh>
        <listen>
          <interface>
            <address>0.0.0.0</address>
            <port>830</port>
          </interface>
        </listen>
      </ssh>
    </netconf>
  </startup>
  <candidate modified="false" lock=""/>
</datastores>

**Comment by LilyCuili** [comment]
the text can't be uploaded correctly,please follow the guide in the link:
http://www.seguesoft.com/index.php/how-to-set-up-netopeer-server-to-use-with-netconfc#Inctool

**Comment by Smile004** [comment]
Hi @LilyCuili 
I have change the startup config in /usr/local/etc/netopeer/cfgnetopeer/datastore-server.xml like 

<?xml version="1.0" encoding="UTF-8"?>
<datastores xmlns="urn:cesnet:tmc:datastores:file">
  <running lock=""/>
  <startup lock="">
    <netconf xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
      <ssh>
        <listen>
          <interface>
            <address>0.0.0.0</address>
            <port>840</port>
          </interface>
        </listen>
      </ssh>
    </netconf>
  </startup>
  <candidate modified="false" lock=""/>
</datastores>

Then i started netopeer server with command
./netopeer-server
But again it listen on same default port 830

**Comment by LilyCuili** [comment]
I think perhaps there is something wrong with your datastore-server.xml,please paste your context.

**Comment by Smile004** [comment]
Yeah thanks @LilyCuili  now i can able to change any port which i want to listen on.
It was an issue with datastore-server.xml file, i have not configured properly.
Now its working fine.

**Comment by Smile004** [comment]
Hi @LilyCuili 
Any familiar guide to learn how to use these commands,
*get
*get-config
*edit-config
*commit


Regards
Smile004

**Comment by krishnakumar4a4** [comment]
@Smile004 all the commands you are asking are standard netconf protocol operations. You can directly refer RFC to know how to use them.
https://tools.ietf.org/html/rfc6241#section-7
