### ISSUE TITLE
Callhome is not working on some linux systems.

### ISSUE THREAD

**Issue by BanuPrakashReddy** [CESNET/netopeer#50]
I have verified passwordless callhome session on ubuntu, it is working fine. 
I have an embedded machine which also run linux. I have followed same procedure as I did on ubuntu.

I repeatedly see below errors:

 Call Home (app abc) client thread creation timeout, retrying.
 Call Home: connected to 127.0.0.1:6666
 np_ssh_create_client: SSH key exchange error (src/ssh/server_ssh.c:1053): 

Please note that, passwordless "connect" works without any problem on the same machine. 
But when try to "listen", It always says that tcp connect is established, but fails at ssh-keyexchange API.

Can someone help me in finding the issue.

**Comment by michalvasko** [comment]
Hi,

we likely cannot reproduce your problem, so I can only help you indirectly. For starters, your lines do not match mine, so your changes could be causing the problem. Also, you can try using different versions of libssh and see if it makes any difference. I cannot think of anything else, I saw this error during Netopeer implementation, but it was always caused by some serious mistake of mine.

Regards,
Michal

**Comment by BanuPrakashReddy** [comment]
Thanks for your response.
Found the issue......!!!!
Increased the leaf value "response-time" in netopeer-cfgnetopeer.yang from 50ms to 500ms and it worked.
Because it is embedded machine,  the timeout was not enough.
I think, default value of response-time should be increased.

Regards,
Banu Prakash

**Comment by michalvasko** [comment]
Hi Banu,

we were actually planning to remove this option from Netopeer, but now we will need to discuss it again. Thanks for letting us know.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi Banu,

just wanted to let you know that Netopeer from the current master branch should establish Call Home connections successfully irrespective of the response time value.

Regards,
Michal

**Comment by BanuPrakashReddy** [comment]
Hi Michal

Thanks for updating .

Regards,
Banu Prakash

**Comment by sivaprasadmsr** [comment]
Hi Team,

I am using callhome netconf-server(netopeer ) , and want to use ubuntu as callhome netconf-client. Is there any application for callhome netconf-client on ubuntu/linux. 

Any help is much appreciated.
Thanks.
