### ISSUE TITLE
Netopeer-server is not considering public key added in authorized_keys

### ISSUE THREAD

**Issue by BanuPrakashReddy** [CESNET/netopeer#51]
Hi,

I am facing a weird problem, I know I am going wrong somewhere. The problem is : 

I have to copy public key(Created at client side) in server path and mention the path of public key in cfgnetopeer yang file like the below way:

      <ssh>
        <client-auth-keys>
          <client-auth-key>
            <path>/home/netconf/.ssh/.id_private.pub</path>
            <username>netconf</username>
          </client-auth-key>
        </client-auth-keys>
      </ssh>
 
Then only the authentication gets success. 
If I directly do ssh-copy-id from client, then it is getting added in authorized keys at server side, but authentication is failing. 
Is this the expected behaviour ?. 
Is netopeer-server ignores the public keys present in authorized keys ?

**Comment by michalvasko** [comment]
Hi,

yes, this is the intended behaviour and a security measure. You need every public key that can be used for authorization to be explicitly mentioned in the Netopeer configuration.

Regards,
Michal
