### ISSUE TITLE
netopeer-server[29100]: sock_listen: could not bind "::0" (Address already in use)

### ISSUE THREAD

**Issue by mohitccem** [CESNET/netopeer#52]
I am getting this error after starting the netopeer-server. 

![netopeer-server](https://cloud.githubusercontent.com/assets/10466012/10213759/ccd6d5ea-682e-11e5-84bf-6b54c99e7dbb.PNG)

**Comment by michalvasko** [comment]
Hi,

that means that some other application is already listening on the same port, likely another instance of Netopeer. You can easily check it with the command `netstat -tlp`.

Regards,
Michal
