### ISSUE TITLE
[libnet conf  error ] when i am trying to communicate between client and server

### ISSUE THREAD

**Issue by mohitccem** [CESNET/netopeer#53]
Client side error :
![client error](https://cloud.githubusercontent.com/assets/10466012/10219080/8e5988a0-6859-11e5-9751-0b8f9f835c10.PNG)

Server side error : 
![server error](https://cloud.githubusercontent.com/assets/10466012/10219126/dc455a4e-6859-11e5-9c32-6d6c87f2bf32.PNG)

**Comment by michalvasko** [comment]
Hi,

from the error it seems that the client supports only one key algorithm, which does not match the one supported by the server. I have never experienced this so I am mostly guessing, but one reason I can think of, which may perhaps cause this, is some improper SSH key configuration. Something forces the client to only support ECDSA keys, which are not supported by Netopeer at the moment, but if you required it, it should be quite easy to add. This is, however, not a real solution to your problem.

Regards,
Michal

**Comment by mohitccem** [comment]
where the state data (read only ) is getting stored ?

**Comment by michalvasko** [comment]
Hi,

I am unsure how this relates to your original problem, but state data are not stored anywhere. They are built on request, in transAPI modules the function *get_state_data* is responsible for this, it returns an XML document with this module's state data.

Regards,
Michal

**Comment by mohitccem** [comment]
how i can integrate the code generated by lnctool  with the server.

**Comment by michalvasko** [comment]
Hi,

there is a tool written for this purpose, look at *netopeer-manager*. Anyway, we are drifting away from the original topic, so if you have any other problems, please create separate issues. Thank you.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,

it seems your original issue happened to someone else as well, could you please share whether you managed to resolved it and how? Thank you.

Regards,
Michal
