### ISSUE TITLE
Multiple netopeer instances

### ISSUE THREAD

**Issue by krishnakumar4a4** [CESNET/netopeer#55]
We are looking for a way to start multiple netopeer server daemons on a single linux machine.
Right now, it is able to start on localhost(127.0.0.1 or ::0) and port 830. 
But we also want to configure the ip address and port.

Could you please tell us whether there is a way to configure this through command line,if exists. Otherwise, respective files which can be of help to us. So that we will try doing some code changes on them.

**Comment by michalvasko** [comment]
Hi,

please look at the issue #49. But to answer your question, the addresses must be adjusted by hand. They are a part of the *ietf-netconf-server* model, whose configuration is in the file *(prefix)/netopeer/cfgnetopeer/datastore-server.xml*.

Regards,
Michal

**Comment by krishnakumar4a4** [comment]
Hi, 
solved this issue myself in #49.
Please refer to it.

Regards,
*_Krishna_*
