### ISSUE TITLE
What is the exact use of Transapi?

### ISSUE THREAD

**Issue by krishnakumar4a4** [CESNET/netopeer#59]
Hi,
We have a netopeer server with custom yang models imported and have to perform get-config,edit-config operations on those.
I don't have any device here, I just want to make the changes reflected in the datastore using the edit-config request. Do I need to write a transpi for this operation?
I have tried to give the edit-config without any transapi and I got the errors like "Failed to apply changes on the device" and "There is no device/data that could be affected."

**Comment by rkrejci** [comment]
Hi,
transapi modules are supposed to apply configuration changes made in a datastore to a device or application or whatever. So, in your case, you don't need transapi module. On the other hand, you need netopeer module - it is used to make netopeer server to know about your yang model. To "create" netopeer module, you only have to run `netopeer-manager(1)` and provide information about your data model, enabled features and datastore file - see the [man page](https://rawgit.com/CESNET/netopeer/master/server/manager/netopeer-manager.1.html)
