### ISSUE TITLE
Question: I want to implement like cisco the "Extended NETCONF Operations" 

### ISSUE THREAD

**Issue by JackLIN-F** [CESNET/netopeer#60]
Hi~
As title ~ 
http://www.cisco.com/c/en/us/td/docs/switches/datacenter/sw/nx-os/xml/user/guide/nxos_xml_interface/using.html

How to implement the function? 
Thanks,
JLin

Example 1-10 Configuration CLI Commands Sent Through <exec-command>
 <?xml version="1.0"?>
  <nf:rpc xmlns:nf="urn:ietf:params:xml:ns:netconf:base:1.0" 
   xmlns:nxos="http://www.cisco.com/nxos:1.0" message-id="3">
    <nxos:exec-command>
       <nxos:cmd>conf t ; interface ethernet 2/1 </nxos:cmd>
       <nxos:cmd>channel-group 2000 ; no shut; </nxos:cmd>
    </nxos:exec-command>
 </nf:rpc>]]>]]>

**Comment by JackLIN-F** [comment]
Hi~
I reference OF-CONFIG project.

Using custom struct:
struct ncds_custom_funcs ofcds_funcs = {
    .init = ofcds_init,
    .free = ofcds_free,
    .was_changed = ofcds_changed,
    .rollback = ofcds_rollback,
    .lock = ofcds_lock,
    .unlock = ofcds_unlock,
    .is_locked = NULL,
    .getconfig = ofcds_getconfig,
    .copyconfig = ofcds_copyconfig,
    .deleteconfig = ofcds_deleteconfig,
    .editconfig = ofcds_editconfig,
};

And use ncds_custom_set_data to init:

    	ncds_custom_set_data(ds.ofc, NULL, &ofcds_funcs);
    	if ((ds.ofc_id = ncds_init(ds.ofc)) < 0) {
       	        nc_close();
        	nc_verb_error("Initiating of-config datastore failed (error code %d).",
                      ds.ofc_id);
        	return EXIT_FAILURE;
    	}


SO, Do I need to add .exe-ccommand = ofcds_exec-command on ofcds_funcs struct ??

Thanks

**Comment by michalvasko** [comment]
Hi,

I have problems understanding what you are trying to do. If you want to implement you own RPC (none of edit-config, get-config, ...), it is quite simple (look at the **turing** or **cfgsystem** transAPI module implementation). If you need a custom data store (not using an XML file for storing the configuration) for some reason then I suggest you wait for *libnetconf2*. It will still take some time, but implementing a custom data store with the current *libnetconf* is difficult, to put it mildly.

Regards,
Michal
