### ISSUE TITLE
netopeer-server

### ISSUE THREAD

**Issue by mohitccem** [CESNET/netopeer#61]
I have added my yang model using netopeer-manager , in segue soft netopeer client it is showing the data model. Now i have made changes in c files generated by lnctool , but no output is shown in the server whereas when i am making changes in turing-machine example i.e. turing-machine.c , it is being reflected in both client and server. How i will know the c file generated is integrated into the server .

**Comment by michalvasko** [comment]
Hi,

the C file must always be compiled into a shared object (*.so), which must be pointed to in the module configuration (default /usr/local/etc/netopeer/modules.conf.d/). *make* and *make install* should do the trick.

Regards,
Michal

**Comment by mohitccem** [comment]
Hi, 
what steps i should follow after making changes to the code. As of now i am doing : 
autoreconf
make 
make install

Regards,
Mohit

**Comment by mohitccem** [comment]
Hi , 

It's working now. Thanks for your support.

Regards,
Mohit
