### ISSUE TITLE
Problem with the server installation netopeer

### ISSUE THREAD

**Issue by RoGuEs3** [CESNET/netopeer#62]
Hi,

I have this problem when executes the command ./configure
i have installed Pyang 1.5, so I don't know what the problem is.
Please for any tips and advices.

./configure --with-libnetconf
checking for pkg-config... /usr/bin/pkg-config
checking for roff2html... no
checking for distro... ubuntu
configure: WARNING: Unsupported Linux distro "ubuntu", only RHEL and SUSE are fully supported.
checking pkg-config is at least version 0.9.0... yes
checking for LIBNETCONF... yes
checking for uname... yes
checking for host architecture... x86_64
checking for lnctool... no
configure: error: "lnctool not found!"

And it's from config.log file:

This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by netopeer-server configure 0.8.0, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure 

## --------- ##

hostname = mateusz-inzynierka
uname -m = x86_64
uname -r = 3.19.0-32-generic
uname -s = Linux
uname -v = #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /usr/sbin
PATH: /usr/bin
PATH: /sbin
PATH: /bin
PATH: /usr/games
PATH: /usr/local/games

## ----------- ##

configure:2478: checking for pkg-config
configure:2496: found /usr/bin/pkg-config
configure:2509: result: /usr/bin/pkg-config
configure:2524: checking for roff2html
configure:2555: result: no
configure:2592: checking for distro
configure:2594: result: ubuntu
configure:2607: WARNING: Unsupported Linux distro "ubuntu", only RHEL and SUSE are fully supported.
configure:2791: checking pkg-config is at least version 0.9.0
configure:2794: result: yes
configure:2815: checking for LIBNETCONF
configure:2822: $PKG_CONFIG --exists --print-errors "libnetconf"
configure:2825: $? = 0
configure:2839: $PKG_CONFIG --exists --print-errors "libnetconf"
configure:2842: $? = 0
configure:2900: result: yes
configure:2937: checking for uname
configure:2953: found /bin/uname
configure:2965: result: yes
configure:2978: checking for host architecture
configure:2987: result: x86_64
configure:3007: checking for lnctool
configure:3035: result: no
configure:3044: error: "lnctool not found!"

## ---------------- ##

ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBNETCONF_CFLAGS_set=
ac_cv_env_LIBNETCONF_CFLAGS_value=
ac_cv_env_LIBNETCONF_LIBS_set=
ac_cv_env_LIBNETCONF_LIBS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_PKG_CONFIG_LIBDIR_set=
ac_cv_env_PKG_CONFIG_LIBDIR_value=
ac_cv_env_PKG_CONFIG_PATH_set=
ac_cv_env_PKG_CONFIG_PATH_value=
ac_cv_env_PKG_CONFIG_set=
ac_cv_env_PKG_CONFIG_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_path_PKG_CONFIG=/usr/bin/pkg-config
ac_cv_path_ROFF2HTML=no
ac_cv_prog_LNCTOOL_EXISTS=no
ac_cv_prog_UNAME=yes
pkg_cv_LIBNETCONF_CFLAGS='-I/usr/local/include  '
pkg_cv_LIBNETCONF_LIBS='-L/usr/local/lib -lnetconf  '

## ----------------- ##

BUILDREQS=' libnetconf-devel'
CC=''
CFLAGS='-Wall -Wextra -O3'
CLIENT_STRUCT_SIZE=''
CONFIGURE_PARAMS=''
CONFIGURE_PWD='/home/rogu3/Pobrane/netopeer-master/server'
CPP=''
CPPFLAGS='-I/usr/local/include    -DRCSID=\"$(IDNOGIT)\"'
DEFS=''
DISTRO='ubuntu'
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
EXEEXT=''
GREP=''
INSTALL_DATA=''
INSTALL_PROGRAM=''
INSTALL_SCRIPT=''
LDFLAGS=''
LIBNETCONF_CFLAGS='-I/usr/local/include  '
LIBNETCONF_DATADIR='/usr/local/share'
LIBNETCONF_LIBS='-L/usr/local/lib -lnetconf  '
LIBOBJS=''
LIBS='-L/usr/local/lib -lnetconf   '
LNCTOOL_EXISTS='no'
LTLIBOBJS=''
MODULESDIR=''
NCSERVER_FEATURES=''
NETOPEER_FEATURES=''
NPCONF='yes'
OBJEXT=''
PACKAGE_BUGREPORT=''
PACKAGE_NAME='netopeer-server'
PACKAGE_STRING='netopeer-server 0.8.0'
PACKAGE_TARNAME='netopeer-server'
PACKAGE_URL=''
PACKAGE_VERSION='0.8.0'
PATH_SEPARATOR=':'
PKG_CONFIG='/usr/bin/pkg-config'
PKG_CONFIG_LIBDIR=''
PKG_CONFIG_PATH=''
PTHREAD_CC=''
PTHREAD_CFLAGS=''
PTHREAD_LIBS=''
RELEASE='1'
REQS=' libnetconf'
ROFF2HTML='no'
RPMBUILD=''
SERVER_LIBS=''
SERVER_TLS_CFGS=''
SERVER_TRANSPORT_HDRS=''
SERVER_TRANSPORT_SRCS=''
SHELL='/bin/bash'
SSH='yes'
TLS='no'
UNAME='yes'
USERMAIL=''
USERNAME=''
XML2_CONFIG=''
ac_ct_CC=''
ax_pthread_config=''
bindir='${exec_prefix}/bin'
build=''
build_alias=''
build_cpu=''
build_os=''
build_vendor=''
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host=''
host_alias=''
host_cpu=''
host_os=''
host_vendor=''
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
libdir='${prefix}/lib64'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='NONE'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "netopeer-server"
#define PACKAGE_TARNAME "netopeer-server"
#define PACKAGE_VERSION "0.8.0"
#define PACKAGE_STRING "netopeer-server 0.8.0"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""

configure: exit 1

**Comment by RoGuEs3** [comment]
I apologize for such a long entry, but i couldn't attach config log in file

**Comment by rkrejci** [comment]
lnctool is part of libnetconf, so it should be installed with libnetconf, but it wasn't. Was the libnetconf compilation/installation without any error or warning? Did you installed pyang before compiling/installing libnetconf?

**Comment by RoGuEs3** [comment]
Yes libnetconf compilation and installation without errors.  Pyang I installed after installing libnetconf. Should I now install libnetconf again?

**Comment by RoGuEs3** [comment]
I tried to install Pyang 1.6 before installation libnetconf, but failed. I installing libnetconf without errors and then Pyang 1.5 without errors

**Comment by michalvasko** [comment]
Hi,
libnetconf detects whether you have pyang installed in configure and based on that installs lnctool. So, run the whole sequence again (configure, make, make install) and it should be fixed.

Regards,
Michal

**Comment by RoGuEs3** [comment]
I done it and now is problem with ssh during installation netopeer server. I compiled before libnetconf with --disable-libssh parameter, but I've got libssh2 and installed libssh-4. libssh is still required during compiling netopeer server and when i wants to compile libnetconf without --disable-libssh parameter. I must install libssh 0.6.4(don't know how, got errors during compiling) if there is another solution?

**Comment by michalvasko** [comment]
Hi,
I will try to answer even though I have problems understanding you. You can compile libnetconf without libssh (libssh2 is irrelevant, this is another library, whose package is called libssh4 for some reason) and SSH client will still work using the ssh(1) utility, custom SSH server too. However, netopeer itself strictly requires libssh for SSH to work. If you absolutely cannot install libssh, you can use the old libnetconf (0.9.x) with the old netopeer (branch "libnetconf 0.9.x"), but they are no longer supported.

Regards,
Michal

**Comment by RoGuEs3** [comment]
Hi Michal
Can you tell me how to install libssh step by step, because i still can't handle this? I can't find installation version with auto tools only by cmake.
Thank you in advice

**Comment by michalvasko** [comment]
Hi,
I am sorry, but your issue is out of netopeer scope. Why can't you compile and install it using cmake? There is INSTALL file in libssh source, just follow it.

Regards,
Michal

**Comment by RoGuEs3** [comment]
Hi
I know that there is INSTALL file, i follow the instructions and receives error like this:
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug ..
Inconsistency detected by ld.so: dl-version.c: 224: _dl_check_map_versions: Assertion `needed != ((void *)0)' failed!

I know there is a lot of information and tutorials about netopeer, I follow the intructions, but still can't handle with installing netopeer server for few days. Maybe I should change the Linux distro(I have got Ubuntu 14.04) or something?
I will be grateful if someone tells me how to install the netopeer server step by step with all the required packages and programs. It may seem silly, but I can't handle with it.
Thank for the advice and understanding.

Regards,
Mateusz

**Comment by michalvasko** [comment]
Hi Mateusz,
just search the web for this error and you should be able to fix it, based on what I found it seems like a CMake problem. Changing distribution may help (from my experience Ubuntu is not very developer-friendly), but is not required. There are packages available on [libssh webpage](www.libssh.org) for OpenSUSE and Fedora, though, so you would not need to compile it there.

Regards,
Michal

**Comment by RoGuEs3** [comment]
Thank you Michal
I will trying to fix it, but if I still fails that change distro. Which distro are you recommend for use with Netconf server?

Regards,
Mateusz

**Comment by michalvasko** [comment]
Officially supported are RHEL and SUSE-based ones. We are developing on OpenSUSE, so we should be able to provide best support if you use that distro.

Regards,
Michal

**Comment by RoGuEs3** [comment]
Hi
I fixed a bug with cmake and finally installed libssh, the latest version. When I want to install libnetconf during compilation recevies such an error:
checking for ssh_pki_key_ecdsa_name in -lssh... no
configure: error: Missing libssh (>=0.6.4)
I can't understand it, because I've got the latest version of libssh. 
I have a request to you Michal, can you tell me how to install the netopeer server step by step on OpenSuse? I will trying to install the server on OpenSuse.

Regards,
Mateusz

**Comment by michalvasko** [comment]
Hi Mateusz,
my guess is that you have an older version of libssh installed from a package (on Ubuntu I saw some 0.5.x as the newest), which is used instead the new one you installed from source. To fix it, it should be enough to uninstall the old package (libssh-devel and libssh-4) and then run ldconfig as root to update library paths.

On OpenSUSE there should be a package available for all the versions, no manual compilation and installation is required. Nevertheless, from standard repositories only older versions may be available, so you may need to download newer ones manually (using [this](https://software.opensuse.org/find) page, for instance).

Regards,
Michal

**Comment by RoGuEs3** [comment]
Thank you for your advice. I'll try to deal with this when I be able to.

Regards,
Mateusz

**Comment by RoGuEs3** [comment]
Hi
I fixed the problem with ssh.  Then I installed libssh the newest version and libnetconf without errors. When I want to install netopeer server during compilation receives such and error: 
...
configure: 
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
configure: error: Cannot compile without any transport protocol!

I just installed ssh so i don't know which protocol is concerned.

Regards,
Mateusz

**Comment by RoGuEs3** [comment]
Hi,
Possible that when compiling the server can't find the correct path in which is ssh lib? What is the default path, in which it is sought ssh. I have got ssh in the default locations, I installed it without specifying location. 

Regards

**Comment by michalvasko** [comment]
Hi Mateusz,
what parameters did you use with configure, or just plain?
```
./configure
```

Also, I will need the whole configure output, you skipped the important parts.

Regards,
Michal

**Comment by RoGuEs3** [comment]
Hi Michal
I tried without any parameters and with this ./configure --with-dbus-services, but it unrecognized.
Output during compiling the server:

./configure
checking for pkg-config... /usr/bin/pkg-config
checking for roff2html... no
checking for distro... ubuntu
configure: WARNING: Unsupported Linux distro "ubuntu", only RHEL and SUSE are fully supported.
checking pkg-config is at least version 0.9.0... yes
checking for LIBNETCONF... yes
checking for uname... yes
checking for host architecture... x86_64
checking for lnctool... yes
checking python module: os... yes
checking python module: copy... yes
checking python module: curses... yes
checking python module: libxml2... yes
checking python module: subprocess... yes
checking python module: re... yes
checking python module: string... yes
checking python module: argparse... yes
checking python module: xml... yes
checking for rpmbuild... no
checking for clang... no
checking for llvm-gcc... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking for main in -lxml2... yes
checking for xml2-config... yes
checking for library containing ncntf_dispatch_receive... none required
checking for nc_session_accept_libssh_channel in -lnetconf... no
configure: 
configure: WARNING: libnetconf does not support SSH, disabling it!
configure: 
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
configure: error: Cannot compile without any transport protocol!

Did you need logs from log file also?

Regards

**Comment by michalvasko** [comment]
Hi Mateusz,
for one, where did you get the macro *--with-dbus-services*? It is not supported for more than a year. Configure clearly tells you that your libnetconf does not support SSH meaning it was compiled without libssh. This is likely some old version you installed before. So, remove all the old versions of libnetconf, install it again, and run *ldconfig*.

Regards,
Michal

**Comment by RoGuEs3** [comment]
Hi Michal,
This macro I found in one of the tutorials, but it is not important just tried with different parameters. 
Overall, I have tried to compile without parameters. I've done it before with libssh, I removed old version ssh and installed libssh 0.7.1 and then libnetconf without parameters in ./configure (without --disable-libssh parameter). Both libssh and libnetconf  have installed properly without errors. After installing both I run ldconfig. Maybe it's problem with ldconfig, not all links have been associated. I'll check it tomorrow.

Regards

**Comment by RoGuEs3** [comment]
Hi
I give up with netopeer on Ubuntu after a few reinstallations. I can't handle with the installation on Ubuntu. I will try to install netopeer on OpenSuse. Can someone tell me how to quickly and easily install it on this OS with all the required packages? I will be very grateful. I know there are tutorials, but even with them I had a problems as I tried on Ubuntu.

Regards,
Mateusz

**Comment by michalvasko** [comment]
Hi Mateusz,
you will mostly need several packages (use zypper to download them on OpenSUSE). For libnetconf it is libxml2-devel, libssh-devel, libopenssl-devel. Also, pyang needs to be installed separately (download from [here](https://github.com/mbj4668/pyang), installation is described in README). For netopeer you will additionally need some python modules, configure will tell you which (they are named python-*, replace * with the module name). If you get stuck somewhere, please try to search the web first, ask us for support afterwards. Thanks.

Regards,
Michal

**Comment by RoGuEs3** [comment]
Hi Michal

Thank you. 
Regards

-----Wiadomość oryginalna-----
Od: "michalvasko" <notifications@github.com>
Wysłano: ‎2015-‎11-‎16 15:10
Do: "CESNET/netopeer" <netopeer@noreply.github.com>
DW: "RoGuEs3" <kedziormateusz7@gmail.com>
Temat: Re: [netopeer] Problem with the server installation netopeer (#62)

Hi Mateusz,
you will mostly need several packages (use zypper to download them on OpenSUSE). For libnetconf it is libxml2-devel, libssh-devel, libopenssl-devel. Also, pyang needs to be installed separately (download from here, installation is described in README). For netopeer you will additionally need some python modules, configure will tell you which (they are named python-*, replace * with the module name). If you get stuck somewhere, please try to search the web first, ask us for support afterwards. Thanks.
Regards,
Michal

**Comment by kamade** [comment]
Mateusz,

I had some of the same problems as you had. I am using Ubuntu LTS 14.04 and configure would croak on libssh-devel vs 0.6.4.

The following snippet from Netopeer documentation helped me fix my environment:
http://seguesoft.com/how-to-set-up-netopeer-server-to-use-with-netconfc

<snippet>
sudo apt-get install libtool
sudo apt-get install libtool-bin
sudo apt-get install libxml2-dev
sudo apt-get install libxlst-dev
sudo apt-get install xsltproc 
sudo apt-get install libcurl4-openssl-dev

sudo apt-get install libssh-dev ! If the system supplied is lower than 0.6.4 download libssh and build our own
 tar xvf libssh-0.7.2.tar.gz
 cd libssh-0.7.2
 mkdir build
 cd build
 cmake ..
 make 
 sudo make install

If you have installed libssh-dev but it is < 0.6.4, and the configure script still can't find the libssh-0.7.2 installed, you may have to remove it by doing:
  sudo apt-get remove libss-dev
  rm -rf /usr/include/libssh

</snippet>

**Comment by wangxinyuanUESTC** [comment]
Hi , I read your article, benefit a lot, would like to ask how to remove other versions of libssh? because i had installed libssh-0.6.5 but this error(configure: error: Missing libssh (>=0.6.4)) still occurred while I installed the libnetconf . Thank you very much!

**Comment by michalvasko** [comment]
Hi,
best is to use `ldconfig` (it requires root access). You can execute `# ldconfig -p | grep libssh`, which will display all the found libssh libraries on your system. If there is another version than you would expect, just delete it (the path is displayed) and then run just `ldconfig` for it to scan the available libraries again.

Regards,
Michal

**Comment by shubhtrix** [comment]
./configure 
checking for pkg-config... /usr/bin/pkg-config
checking for roff2html... no
checking for distro... ubuntu
configure: WARNING: Unsupported Linux distro "ubuntu", only RHEL and SUSE are fully supported.
checking pkg-config is at least version 0.9.0... yes
checking for LIBNETCONF... yes
checking for uname... yes
checking for host architecture... x86_64
checking for lnctool... no
configure: error: "lnctool not found!"
HOW TO COMPILE SERVER ON UBUNTU. LOADS OF DEPENDENCIES. 
This above missing tool lnctool under "libnetconfig/dev-tools/lnctool", is there any way which can simplify it's README.

**Comment by michalvasko** [comment]
Hi,
for one, please do not write into year-old closed issues, rather open a new one.

You got this error because your *libnetconf* installation failed to install its part `lnctool`. The reason most likely being that you do not have `pyang` installed (*libnetconf* configure warns about this). So, reinstall *libnetconf* having `pyang` installed and *netopeer*  will also install.

However, it would be best if you did not use *netopeer* at all and rather go for [netopeer2](https://github.com/cesnet/netopeer2).

Regards,
Michal

**Comment by shubhtrix** [comment]
Oh!!

Resolved issue with after recompiling and installing yang dependencies.
Thanks for that help, and recommendations towards netopeer2.  
Once again, thanks for your help and response. 
 
Regards,
Shubh
