### ISSUE TITLE
netopeer-server[29755]: Unable to monitor "/etc/sysconfig/network-scripts/ifcfg-docker0" (No such file or directory)

### ISSUE THREAD

**Issue by mohitccem** [CESNET/netopeer#64]
Hi ,

This message is shown in while running server and one more problem is that the i am enable to retrieve data from the datastore .

Regards,
Mohit

**Comment by michalvasko** [comment]
Hi Mohit,
a part of the cfginterfaces module is a file monitor, which tries to prevent some outside changes to network interface configuration files to go unnoticed. The message is just warning you that "docker0" interface configuration file could not be monitored because it does not exist. This usually means that the particular interface is managed some other way and any changes to it using netopeer will either not be applied or reset after computer restart.

Being unable to retrieve data from the datastore is too general a problem for us to be able to help you without more information. Please write which step fails (starting netopeer, connecting to it, sending get/get-config) and include the error message as well.

Regards,
Michal

**Comment by mohitccem** [comment]
Hi ,
I am able to connect . While performing get , get and edit config it is giving error. The datastore xml file is present.

Regards,
Mohit

**Comment by michalvasko** [comment]
Hi Mohit,
I asked you to include the error message and I must ask you to do it again, we cannot help you without it.

Regards,
Michal

**Comment by mohitccem** [comment]
get : 
Request ########################################
<?xml version='1.0' encoding='UTF-8'?>
<rpc message-id="0" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <get>
    <filter type="subtree">
      <vONT:InternetGatewayDevice xmlns:vONT="urn:ietf:params:xml:ns:yang:vONT"/>
    </filter>
  </get>
</rpc>


Reply Error or Operation Failed #####################
<?xml version='1.0' encoding='UTF-8'?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="0">
  <data/>
</rpc-reply>

edit-config : 
Request ########################################
<?xml version='1.0' encoding='UTF-8'?>
<rpc message-id="25" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <edit-config>
    <target>
      <running/>
    </target>
    <config>
      <vONT:InternetGatewayDevice xmlns:vONT="urn:ietf:params:xml:ns:yang:vONT">
        <vONT:InterfaceProfile>
          <vONT:port>34</vONT:port>
          <vONT:Type>true</vONT:Type>
          <vONT:VLAN>true</vONT:VLAN>
          <vONT:Description>ONT</vONT:Description>
          <vONT:DHCPClient>Enable</vONT:DHCPClient>
          <vONT:DeviceMAC>00:0a:95:9d:68:16</vONT:DeviceMAC>
          <vONT:IPAddress>127.0.5.3</vONT:IPAddress>
          <vONT:SubnetAddress>255.255.0.0</vONT:SubnetAddress>
          <vONT:GatewayAddress>127.0.4.6</vONT:GatewayAddress>
          <vONT:DNSAddress>127.0.4.5</vONT:DNSAddress>
        </vONT:InterfaceProfile>
      </vONT:InternetGatewayDevice>
    </config>
  </edit-config>
</rpc>


Reply Error or Operation Failed #####################
<?xml version='1.0' encoding='UTF-8'?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="25">
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message>Datastore fails to validate (Element InternetGatewayDevice failed to validate content)</error-message>
  </rpc-error>
  <default:rpc-error xmlns:default="urn:ietf:params:xml:ns:netconf:base:1.0">
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message>Datastore fails to validate (Extra element InterfaceProfile in interleave)</error-message>
  </default:rpc-error>
  <default:rpc-error xmlns:default="urn:ietf:params:xml:ns:netconf:base:1.0">
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message>Datastore fails to validate (Element InterfaceProfile failed to validate content)</error-message>
  </default:rpc-error>
  <default:rpc-error xmlns:default="urn:ietf:params:xml:ns:netconf:base:1.0">
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message>Datastore fails to validate (Element port failed to validate content)</error-message>
  </default:rpc-error>
  <default:rpc-error xmlns:default="urn:ietf:params:xml:ns:netconf:base:1.0">
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message>Datastore fails to validate (Error validating datatype unsignedInt)</error-message>
  </default:rpc-error>
</rpc-reply>

**Comment by michalvasko** [comment]
Hi Mohit,
this is a strange error. What version of netopeer and libnetconf are you using? Did you modify either of them?

Regards,
Michal

**Comment by mohitccem** [comment]
Hi ,
The values were invalid according to the model , but earlier when i have performed edit-config operation , the same value which is giving error now was getting stored. I am using segue soft client.  What could be the  possible reason ? Why validation was not there at that time and now it's working.

**Comment by rkrejci** [comment]
And what has changed from that time? One possible reason is that client is allowed to specify that validation is not supposed to be performed after edit-config. Another reason can be a changed validation tools/files on the server side.

**Comment by mohitccem** [comment]
Hi,

the data is validated in client side itself or it is going to the server and then getting tested ?

Regards,
Mohit

**Comment by rkrejci** [comment]
It depend on client, according to RFC, server is supposed to do validation, but client can also do some of the checks. 
Anyway, I was talking about validation on the server side since you were getting validation errors from server.
