### ISSUE TITLE
libnetconf ERROR: Input channel error listen: receiving call Home failed.

### ISSUE THREAD

**Issue by Barathi07** [CESNET/netopeer#66]
When i try to connect to server from the netopeer-cli, using 'listen' command,am getting the following error: libnetconf ERROR: Input channel error listen: receiving call Home failed. Trying to establish the reverse ssh connection. 
Started the callhome.c file in examples/apps directory.  gave the input parameters as host and port while running the callhome file in the format: ./callhome host:port
netopeer-server is also running.
using libnetconf-0.9.x version and netopeer-0.6.0 version.

**Comment by michalvasko** [comment]
Hi,
libnetconf and netopeer you are using are outdated and no longer supported. I am sorry, I can only recommend you to use the newest versions and if you encounter any issues with them, we will try to help.

Regards,
Michal

**Comment by Barathi07** [comment]
Should I use the master branch or 0.10.x?
Please suggest the branch to use for call home(reverse SSH connection).

**Comment by Barathi07** [comment]
Hi,
     I have tried with libnetconf-master branch. When i try to create a binary for callhome.c file, i got the following ERROR:
gcc -Wall -g -I../../src/  -o callhome callhome.c -L../../.libs/ -lnetconf
callhome.c: In function 'main':
callhome.c:99:3: error: too few arguments to function 'nc_callhome_connect'
   pid = nc_callhome_connect(srv, 5, 3, STUNNEL, arg);
   ^
In file included from ../../src/libnetconf_ssh.h:45:0,
                 from callhome.c:17:
../../src/callhome.h:216:5: note: declared here
 int nc_callhome_connect(struct nc_mngmt_server *host_list, uint8_t reconnect_secs, uint8_t reconnect_count, const char* server_path, char *const argv[], int *com_socket);
     ^
callhome.c:102:3: error: too few arguments to function 'nc_callhome_connect'
   pid = nc_callhome_connect(srv, 5, 3, NULL, NULL);
   ^
In file included from ../../src/libnetconf_ssh.h:45:0,
                 from callhome.c:17:
../../src/callhome.h:216:5: note: declared here
 int nc_callhome_connect(struct nc_mngmt_server *host_list, uint8_t reconnect_secs, uint8_t reconnect_count, const char* server_path, char *const argv[], int *com_socket);
     ^
make: *** [callhome] Error 1

Should i include a additional parameter with NULL value?
WHAT I TRIED:
eg: libnetconf-master/examples/apps/callhome.c 
        if (proto == NC_TRANSPORT_TLS) {
                pid = nc_callhome_connect(srv, 5, 3, STUNNEL, arg, NULL);
        } else {
                /* for SSH we don't need to specify specific arguments */
                pid = nc_callhome_connect(srv, 5, 3, NULL, NULL, NULL);
        }

Using the master branch for both libnetconf and netopeer

**Comment by michalvasko** [comment]
Hi,
this was an outdated and likely not even functioning example, establishing Call Home using libnetconf API is not that simple. Current netopeer uses its own implementation of Call Home, not libnetconf one.

Regards,
Michal
