### ISSUE TITLE
NOTICE file for overall project license is missing

### ISSUE THREAD

**Issue by be4ming** [CESNET/netopeer#67]
Cannot find LICENSE or NOTICE files for netopeer overall project license terms. Based on a repository search of "license" it appears that it might be dual licensed: BSD / GPL? Expecting something like [Fusion/RootTools](https://github.com/Fusion/RootTools)'s LICENSE / NOTICE files inside the [RootTools_sdk3_generic folder](https://github.com/Fusion/RootTools/tree/master/RootTools_sdk3_generic) (dual-licensed).

**Comment by michalvasko** [comment]
Hi,
I unified and updated the license information in every source file, everything should be clear now, it is dual-licensed like you said.

Regards,
Michal

**Comment by be4ming** [comment]
Hi Michal, 

Thank you for the update! 

Regards, 
Glenda
