### ISSUE TITLE
libnetconf ERROR: Input channel error (end of file) listen: receiving call Home failed.

### ISSUE THREAD

**Issue by Barathi07** [CESNET/netopeer#69]
With the 'listen' command in netopeer-cli, got the error:

libnetconf ERROR: Input channel error (end of file)
listen: receiving call Home failed.

Using the master branch for both libnetconf(0.10.0) and netopeer(0.8.0)
netopeer-server is also running.

**Comment by michalvasko** [comment]
Hi,
I will need more information to help you. For starters, what is your configuration of netopeer (transAPI ietf-netconf-server)? If you had configured Call Home correctly and had run netopeer with "-v 3", you should have seen a repeated message that netopeer is trying to connect to a client, but fails to do so. Then you should have started netopeer-cli and used the listen command. Did you pass any parameters to it, or not?

Regards,
Michal

**Comment by Barathi07** [comment]
Hi  Michal,
    Still now I have tried to run the callhome.c file in libnetconf.
I ran the file like as follows:
./callhome 127.0.0.1:6666

     I tried in a new server from scratch.The reverse SSH connection got
established successfully. But,I have tried with libnetconf-0.9.1 and
netopeer-0.6.2.
    With those versions only,it worked.I didn't get any error.

I haven't tried to establish callhome connection from netopeer.
Can u please guide me to establish the callhome(reverse SSH) connection
from netopeer?
   Do I need to do any changes in the netopeer-cli.
   Please mention which versions to use for libnetconf and netopeer.

Regards,
Barathi

**Comment by Barathi07** [comment]
Hi  Michal,
    Still now I have tried to run the callhome.c file in libnetconf.
I ran the file like as follows:
./callhome 127.0.0.1:6666

     I tried in a new server from scratch.The reverse SSH connection got
established successfully. But,I have tried with libnetconf-0.9.1 and
netopeer-0.6.2.
    With those versions only,it worked.I didn't get any error.

I haven't tried to establish callhome connection from netopeer.
Can u please guide me to establish the callhome(reverse SSH) connection
from netopeer?
   Do I need to do any changes in the netopeer-cli.
   Please mention which versions to use for libnetconf and netopeer.

**Comment by michalvasko** [comment]
Hi,
do not use that example, it is outdated and have already been removed. So, use the libnetconf and netopeer from master branches (libnetconf 0.10.0 and netopeer 0.8.0). To try Call Home out, look [here](https://github.com/CESNET/netopeer/wiki/CallHome).

Regards,
Michal

**Comment by Barathi07** [comment]
Thank you for the response.I will try out and let u know.
If we establish the reverse ssh connection(i.e) initiate connection from server to client, to which port will it listen?
Default ssh port is 830
Pls tell the callhome ssh port

**Comment by michalvasko** [comment]
The example in the wiki page I linked in the previous post uses the default port 6666.

**Comment by rkrejci** [comment]
That's because the Call Home is still only the IETF draft and IANA did not yet assigned any port number to it.

**Comment by Barathi07** [comment]
okay..Thank you so much..
