### ISSUE TITLE
Question: How to transfer yang file to yin and rng file???

### ISSUE THREAD

**Issue by JackLIN-F** [CESNET/netopeer#70]
Hi~
I have a my.yang file.
Use ncds_new_transapi_static to load my.yin file
How to transfer yang file to yin and rng file?

Thanks

**Comment by JackLIN-F** [comment]
Hi~
I found:  pyang -f yin data-model.yang -o data-model.yin

How to transfer yang file to rng file?

Thanks

**Comment by rkrejci** [comment]
Please read the [transapi tutorial](https://rawgit.com/CESNET/libnetconf/master/doc/doxygen/html/d9/d25/transapi.html).
