### ISSUE TITLE
How to reply to output node on RPC?

### ISSUE THREAD

**Issue by macauleycheng** [CESNET/netopeer#71]
We want to implement the sal-flow.yang (https://github.com/YangModels/yang/blob/master/experimental/odp/sal-flow.yang).

In trasnapi, how do we return the RPC output node? Could you give me a simple example?
```
Take add-flow as example:
    rpc add-flow {
       input {
             uses tr:transaction-metadata;
             leaf flow-ref {
                type types:flow-ref;
            }
            uses node-flow;            
        }
        _**output**_ {
            uses tr:transaction-aware;
        }
    }
```

**Comment by michalvasko** [comment]
Hi,
you simply use the function *nc_reply_data()*. In your example, you could end the RPC transAPI callback by returning **nc_reply_data("\<xmlns:tr="urn:opendaylight:flow:transaction" tr:transaction-aware>421\</tr:transaction-aware>")**, but if working only with libnetconf, it does not even need the namespace, even though it should (too complex to fix it current libnetconf).

Regards,
Michal
