### ISSUE TITLE
With new netopeer, Is there a way to configure deny/allow host, deny/allow users mechanism

### ISSUE THREAD

**Issue by BanuPrakashReddy** [CESNET/netopeer#72]
Previuosly we used to have sshd_config.running file where we dyncamically change deny/allow users.
But now we dont use the file. With new libntecon/netopeer architecture is there a way we can configure deny/allow user mechanism.

**Comment by michalvasko** [comment]
Hi,
there is the NACM module and always was, so I am guessing you want to restrict connecting to the server itself. If you have previously used the *AllowUsers* option, there is no direct replacement. Local users are used for *interactive* and *password* authentication, so you would need to change them, but you can set who can connect using what public key and with what username by modifying the configuration of **netopeer-cfgnetopeer** transAPI. *netopeer-configurator* can do this in a user-friendly way.

Regards,
Michal
