### ISSUE TITLE
turing machine doesn't work (error message: There is no device/data that could be affected)

### ISSUE THREAD

**Issue by gamgio** [CESNET/netopeer#74]
Hi,

I downloaded, built and installed libnetconfd/netopeer on Ubuntu 14.04  .
As exercise I also added turing-machine example into the netopeer server.

I installed turing machine library in the path /usr/local/lib/turing-machine.so and added the turing-machine yang model using the following command:

    machine@libnetconf:~$ netopeer-manager add --name turing --model /usr/local/etc/netopeer/turing-machine/turing-machine.yin --datastore /var/lib/libnetconf/turing.xml

Verify it using the command:

    machine@libnetconf:~/git/netopeer/transAPI/turing$ netopeer-manager list
    Reading the configuration from /usr/local/etc/netopeer/modules.conf.d/
    List of startup Netopeer modules:
    turing (enabled)
    machine@libnetconf:~/git/netopeer/transAPI/turing$

After that I started the netconf server using the following command:

    machine@libnetconf:~$netopeer-server -v 3
    ...................
    ...................
    netopeer-server[2353]: Datastore turing-machine initiated with ID 1681692778.
    netopeer-server[2353]: Netopeer server successfully initialized.

 I also started the netconf cli using the following command:

    machine@libnetconf:~$ netopeer-cli
    netconf> connect 127.0.0.1
    root@127.0.0.1 password:
    netconf> edit-config --config /home/vagrant/git/netopeer/transAPI/turing/examples/0n1n-config.xml
    
    Select target datastore (running|startup|candidate|url:<dsturl>): running
    
    Result OK
    netconf>
    netconf> user-rpc
    <initialize xmlns="http://example.net/turing-machine">
      <tape-content>ABC</tape-content>
    </initialize>
    
    NETCONF error: operation-failed (application) - There is no device/data that could be affected.
    netconf>

On the netconf server side the following printout appears:

    netopeer-server[2353]: Writing message (session 1): <?xml version="1.0" encoding="UTF-8"?>
    <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
      <ok/>
    </rpc-reply>
    netopeer-server[2353]: Received message (session 1): <?xml version="1.0" encoding="UTF-8"?>
    <rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="2">
      <initialize xmlns="http://example.net/turing-machine">
        <tape-content>ABC</tape-content>
      </initialize>
    </rpc>
    netopeer-server[2353]: Writing message (session 1): <?xml version="1.0" encoding="UTF-8"?>
    <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="2">
      <rpc-error>
        <error-type>application</error-type>
        <error-tag>operation-failed</error-tag>
        <error-severity>error</error-severity>
        <error-message>There is no device/data that could be affected.</error-message>
      </rpc-error>
    </rpc-reply>

What I am wrong ? 
What is missing in steps above ? 
Is there a README or wiki/doc page with all steps that I need to perform to run, in the right way,  the turing machine ?
Where can I find all steps that I need to configure and  run the turing machine ?

I also read some issues about a similar problem but reading them it is not clear how to solve it.
Pls, could you help me ? 

Let me know if you need more details.
thxs in advance

**Comment by michalvasko** [comment]
Hi,
there is indeed something wrong because I tried sending the example *edit-config*, then the exact same *initialize* RPC and it worked correctly. All your steps seem correct and I don't know where to start looking for the issue. Are you using the most recent libnetconf/netopeer? I can only suggest you remove this module using *netopeer-manager* and install it again with
    # make install
in the *turing* module directory. This was the only difference in my case, when it worked.

Regards,
Michal

**Comment by gamgio** [comment]
Hi Michal,

after your answer I created a new VM and installed libnetcon and netopeer again.
Now it works very well.

thxs for your support

BR,
gamgio
