### ISSUE TITLE
cfginterfaces utility: Build problem

### ISSUE THREAD

**Issue by gamgio** [CESNET/netopeer#75]
Hi all,

I have the following build problem:

machine@libNetconf:~/git/netopeer/transAPI/cfginterfaces$ make
./libtool --tag=CC --quiet --mode=compile gcc -Wall -I/usr/include/libxml2  -O3 -Wno-unused-result  -fPIC -shared -c cfginterfaces.c -o .obj/cfginterfaces.lo
./libtool --tag=CC --quiet --mode=compile gcc -Wall -I/usr/include/libxml2  -O3 -Wno-unused-result  -fPIC -shared -c iface_if.c -o .obj/iface_if.lo
In file included from /usr/include/fcntl.h:279:0,
                 from iface_if.c:6:
In function 'open',
    inlined from 'write_sysctl_proc_net' at iface_if.c:81:6:
/usr/include/x86_64-linux-gnu/bits/fcntl2.h:50:24: error: call to '__open_missing_mode' declared with attribute error: open with O_CREAT in second argument needs 3 arguments
    __open_missing_mode ();
                        ^
make: *** [.obj/iface_if.lo] Error 1
machine@libNetconf:~/

Other info:
machine@libNetconf:~/git/netopeer/transAPI/cfginterfaces$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
machine@libNetconf:~/git/netopeer/transAPI/cfginterfaces$

machine@libNetconf:~/git/netopeer/transAPI/cfginterfaces$ uname -a
Linux libNetconf 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
machine@libNetconf:~/git/netopeer/transAPI/cfginterfaces$

Pls could you help me ?

Regards,
\gamgio

**Comment by michalvasko** [comment]
Hi,
please pull the most recent version, this was fixed 4 months ago.

Regards,
Michal

**Comment by gamgio** [comment]
Hi Michal

do I need to use a specific branch instead of a master branch ? 
In that case pls give me the name of the specific branch.

Below you can see other information:

machine@libNetconf:~/git/netopeer$ git pull
Already up-to-date.
machine@libNetconf:~/git/netopeer$ git branch
master
machine@libNetconf:~/git/netopeer$ git pull --rebase
Current branch master is up to date.
machine@libNetconf:~/git/netopeer$ git branch -r
  origin/HEAD -> origin/master
  origin/libnetconf-0.6.x
  origin/libnetconf-0.7.x
  origin/libnetconf-0.9.x
  origin/libnetconf_libssh
  origin/master
  origin/openwrt
  origin/restconf-impl
  origin/transapiv6
machine@libNetconf:~/git/netopeer$ 
machine@libNetconf:~/git/netopeer$ ls
cli  server  transAPI
machine@libNetconf:~/git/netopeer$ cd transAPI/cfginterfaces/
machine@libNetconf:~/git/netopeer/transAPI/cfginterfaces$ make
./libtool --tag=CC --quiet --mode=compile gcc -Wall -I/usr/include/libxml2  -O3 -Wno-unused-result  -fPIC -shared -c iface_if.c -o .obj/iface_if.lo
In file included from /usr/include/fcntl.h:279:0,
                 from iface_if.c:6:
In function 'open',
    inlined from 'write_sysctl_proc_net' at iface_if.c:81:6:
/usr/include/x86_64-linux-gnu/bits/fcntl2.h:50:24: error: call to '__open_missing_mode' declared with attribute error: open with O_CREAT in second argument needs 3 arguments
    __open_missing_mode ();
                        ^
make: *** [.obj/iface_if.lo] Error 1
machine@libNetconf:~/git/netopeer/transAPI/cfginterfaces$ 

Regards,
gamgio

**Comment by michalvasko** [comment]
Hi Gamgio,
this is weird, it seems you do have the newest revision. Can you please look at the line 81 in iface_if.c? There were only 2 parameters to the *open()* function call before, there should be 3 when O_CREAT is used (this is exactly the error you are getting). It is fixed in the master branch, though.

Regards,
Michal

**Comment by gamgio** [comment]
Hi Michal

Now it works.

Thxs for your support.
\gamgio
