### ISSUE TITLE
netopeer server restart

### ISSUE THREAD

**Issue by mohitccem** [CESNET/netopeer#76]
Hi, 

I have made a simple yang model with one leaf and generated the code with lnctool and added the model with netopeer-manager. edit-config and get-config operation is working , but when the server is restarted the data linked with this Test module is getting deleted from the datastore.

yang model : 
```
module Test {
        namespace "urn:ietf:params:xml:ns:yang:test";
        prefix ts;

  leaf test1 {
       type string;
    }
}
```
Regards,
Mohit

**Comment by michalvasko** [comment]
Hi Mohit,
did you copy them into the *startup* datastore? The *running* datastore is supposed to be rewritten by *startup* during restart.

Regards,
Michal

**Comment by mohitccem** [comment]
Hi,
No , i didn't copied them to startup datastore. I have used candidate datastore.

Regards,
Mohit

**Comment by michalvasko** [comment]
Hi,
did you specify a datastore in *netopeer-namager* when you added your model?

Regards,
Michal

**Comment by mohitccem** [comment]
Hi,

yes , i have added a datastore when i added my model and when i am
performing edit-config  , i can see that value in my datastore file.

Regards,

Mohit

**Comment by michalvasko** [comment]
Hi Mohit,
it did work for me, any changes in *candidate* remained after I restarted *netopeer*. Nevertheless, it is not a strict requirement and if you want persistent data, you should use the *startup* datastore.

Regards,
Michal
