### ISSUE TITLE
unable to retrieve State Data value 

### ISSUE THREAD

**Issue by mohitccem** [CESNET/netopeer#77]
YANG -
```
module brg {

        namespace "urn:ietf:params:xml:ns:yang:brg";
        prefix br;

        leaf test1 {
                   type string;
        }

        leaf WANDeviceNumberOfEntries {
             type uint32 ;
             config false;
             description "Number of instances of WANDevice.";
        }

 }
```
C file-
```
/*
 * This is automatically generated callbacks file
 * It contains 3 parts: Configuration callbacks, RPC callbacks and state data callbacks.
 * Do NOT alter function signatures or any structures unless you know exactly what you are doing.
 */

#include <stdlib.h>
#include <sys/inotify.h>
#include <libxml/tree.h>
#include <libnetconf_xml.h>
#include <pthread.h>


/* transAPI version which must be compatible with libnetconf */
int transapi_version = 6;

/* Signal to libnetconf that configuration data were modified by any callback.
 * 0 - data not modified
 * 1 - data have been modified
 */
int config_modified = 0;
/*
 * Determines the callbacks order.
 * Set this variable before compilation and DO NOT modify it in runtime.
 * TRANSAPI_CLBCKS_LEAF_TO_ROOT (default)
 * TRANSAPI_CLBCKS_ROOT_TO_LEAF
 */
const TRANSAPI_CLBCKS_ORDER_TYPE callbacks_order = TRANSAPI_CLBCKS_ORDER_DEFAULT;


/* Do not modify or set! This variable is set by libnetconf to announce edit-config's error-option
Feel free to use it to distinguish module behavior for different error-option values.
 * Possible values:
 * NC_EDIT_ERROPT_STOP - Following callback after failure are not executed, all successful callbacks executed till
                         failure point must be applied to the device.
 * NC_EDIT_ERROPT_CONT - Failed callbacks are skipped, but all callbacks needed to apply configuration changes are executed
 * NC_EDIT_ERROPT_ROLLBACK - After failure, following callbacks are not executed, but previous successful callbacks are
                         executed again with previous configuration data to roll it back.
 */
NC_EDIT_ERROPT_TYPE erropt = NC_EDIT_ERROPT_NOTSET;

/**
 * @brief Initialize plugin after loaded and before any other functions are called.

 * This function should not apply any configuration data to the controlled device. If no
 * running is returned (it stays *NULL), complete startup configuration is consequently
 * applied via module callbacks. When a running configuration is returned, libnetconf
 * then applies (via module's callbacks) only the startup configuration data that
 * differ from the returned running configuration data.

 * Please note, that copying startup data to the running is performed only after the
 * libnetconf's system-wide close - see nc_close() function documentation for more
 * information.

 * @param[out] running	Current configuration of managed device.

 * @return EXIT_SUCCESS or EXIT_FAILURE
*/

uint32_t WAN=3;
static pthread_mutex_t tm_data_lock = PTHREAD_MUTEX_INITIALIZER;


int transapi_init(xmlDocPtr *running) {
	return EXIT_SUCCESS;
}

/**
 * @brief Free all resources allocated on plugin runtime and prepare plugin for removal.
 */
void transapi_close(void) {
	return;
}

/**
 * @brief Retrieve state data from device and return them as XML document
 *
 * @param model	Device data model. libxml2 xmlDocPtr.
 * @param running	Running datastore content. libxml2 xmlDocPtr.
 * @param[out] err  Double pointer to error structure. Fill error when some occurs.
 * @return State data as libxml2 xmlDocPtr or NULL in case of error.
 */
xmlDocPtr get_state_data(xmlDocPtr model, xmlDocPtr running, struct nc_err **err) {
	fprintf(stderr,"\n Inside get_state_data");

	 char *data = NULL;
	 xmlDocPtr doc = NULL;
	 xmlNodePtr root;
	 xmlNsPtr ns;
	
	 /* create XML doc with <brg/> root */
         doc = xmlNewDoc(BAD_CAST "1.0");
         xmlDocSetRootElement(doc, root = xmlNewDocNode(doc, NULL, BAD_CAST "brg", NULL));
         ns = xmlNewNs(root, BAD_CAST "http://example.net/brg", NULL);
	 xmlSetNs(root, ns);

 	 /* lock internal structures */
         pthread_mutex_lock(&tm_data_lock);

	 /* add <WANDevicesNumberOfEntries/> leaf */
	 asprintf(&data, "%d", WAN);
	 xmlNewChild(root, root->ns, BAD_CAST "WANDeviceNumberOfEntries", BAD_CAST data);
	 free(data);
	 data = NULL;


	 /* unlock internal structures */
	 pthread_mutex_unlock(&tm_data_lock);

	 /* return turing machine state information */
	 return doc;



      //  return NULL;
	
}
/*
 * Mapping prefixes with namespaces.
 * Do NOT modify this structure!
 */
struct ns_pair namespace_mapping[] = {{"br", "urn:ietf:params:xml:ns:yang:brg"}, {NULL, NULL}};

/*
 * CONFIGURATION callbacks
 * Here follows set of callback functions run every time some change in associated part of running datastore occurs.
 * You can safely modify the bodies of all function as well as add new functions for better lucidity of code.
 */

/**
 * @brief This callback will be run when node in path /br:test1 changes
 *
 * @param[in] data	Double pointer to void. Its passed to every callback. You can share data using it.
 * @param[in] op	Observed change in path. XMLDIFF_OP type.
 * @param[in] old_node	Old configuration node. If op == XMLDIFF_ADD, it is NULL.
 * @param[in] new_node	New configuration node. if op == XMLDIFF_REM, it is NULL.
 * @param[out] error	If callback fails, it can return libnetconf error structure with a failure description.
 *
 * @return EXIT_SUCCESS or EXIT_FAILURE
 */
/* !DO NOT ALTER FUNCTION SIGNATURE! */
int callback_br_test1(void **data, XMLDIFF_OP op, xmlNodePtr old_node, xmlNodePtr new_node, struct nc_err **error) {
	fprintf(stderr,"\n Inside br_test1");
	return EXIT_SUCCESS;
}

/*
 * Structure transapi_config_callbacks provide mapping between callback and path in configuration datastore.
 * It is used by libnetconf library to decide which callbacks will be run.
 * DO NOT alter this structure
 */
struct transapi_data_callbacks clbks =  {
	.callbacks_count = 1,
	.data = NULL,
	.callbacks = {
		{.path = "/br:test1", .func = callback_br_test1}
	}
};

/**
 * @brief Get a node from the RPC input. The first found node is returned, so if traversing lists,
 * call repeatedly with result->next as the node argument.
 *
 * @param name	Name of the node to be retrieved.
 * @param node	List of nodes that will be searched.
 * @return Pointer to the matching node or NULL
 */
xmlNodePtr get_rpc_node(const char *name, const xmlNodePtr node) {
	xmlNodePtr ret = NULL;

	for (ret = node; ret != NULL; ret = ret->next) {
		if (xmlStrEqual(BAD_CAST name, ret->name)) {
			break;
		}
	}

	return ret;
}

/*
 * RPC callbacks
 * Here follows set of callback functions run every time RPC specific for this device arrives.
 * You can safely modify the bodies of all function as well as add new functions for better lucidity of code.
 * Every function takes an libxml2 list of inputs as an argument.
 * If input was not set in RPC message argument is set to NULL. To retrieve each argument, preferably use get_rpc_node().
 */

/*
 * Structure transapi_rpc_callbacks provides mapping between callbacks and RPC messages.
 * It is used by libnetconf library to decide which callbacks will be run when RPC arrives.
 * DO NOT alter this structure
 */
struct transapi_rpc_callbacks rpc_clbks = {
	.callbacks_count = 0,
	.callbacks = {
	}
};

/*
 * Structure transapi_file_callbacks provides mapping between specific files
 * (e.g. configuration file in /etc/) and the callback function executed when
 * the file is modified.
 * The structure is empty by default. Add items, as in example, as you need.
 *
 * Example:
 * int example_callback(const char *filepath, xmlDocPtr *edit_config, int *exec) {
 *     // do the job with changed file content
 *     // if needed, set edit_config parameter to the edit-config data to be applied
 *     // if needed, set exec to 1 to perform consequent transapi callbacks
 *     return 0;
 * }
 *
 * struct transapi_file_callbacks file_clbks = {
 *     .callbacks_count = 1,
 *     .callbacks = {
 *         {.path = "/etc/my_cfg_file", .func = example_callback}
 *     }
 * }
 */
struct transapi_file_callbacks file_clbks = {
	.callbacks_count = 0,
	.callbacks = {{NULL}}
};
```

**Comment by rkrejci** [comment]
Is there any question or are you just sharing your code?

**Comment by mohitccem** [comment]
Hi , 
I am enable to retrieve the data for WANDevicesNumberOfEntries (state data) , when i am performing get-data . I have referred turing-machine example , what's need to be updated in this code ??

**Comment by michalvasko** [comment]
Hi Mohit,
what exactly is the problem? You send a **get** and receive state data without yours or an error? Could you please provide the output of *netopeer* during startup with *-v 3*?

Regards,
Michal

**Comment by mohitccem** [comment]
Hi Michal ,

Yes , i can send get , but it is not retrieved . Output after performing get - 

Request ########################################
<?xml version='1.0' encoding='UTF-8'?>
<rpc message-id="0" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <get>
    <filter type="subtree">
      <br:WANDeviceNumberOfEntries xmlns:br="urn:ietf:params:xml:ns:yang:brg"/>
    </filter>
  </get>
</rpc>
Reply Error or Operation Failed #####################
<?xml version='1.0' encoding='UTF-8'?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="0">
  <data/>
</rpc-reply>

Output of -v 3 - 
[root@sys-214-25 ~]# netopeer-server -v 3
netopeer-server[29403]: Shared memory location: /dev/shm/libnetconfshm
netopeer-server[29403]: POSIX SHM File Descriptor: 4 (600B).
netopeer-server[29403]: ncds_features_parse: no feature definitions found in data model ietf-inet-types.
netopeer-server[29403]: ncds_features_parse: no feature definitions found in data model ietf-yang-types.
netopeer-server[29403]: ncds_features_parse: no feature definitions found in data model ietf-netconf-monitoring.
netopeer-server[29403]: ncds_features_parse: no feature definitions found in data model ietf-netconf-notifications.
netopeer-server[29403]: ncds_features_parse: no feature definitions found in data model nc-notifications.
netopeer-server[29403]: ncds_features_parse: no feature definitions found in data model notifications.
netopeer-server[29403]: ncds_features_parse: no feature definitions found in data model ietf-netconf-with-defaults.
netopeer-server[29403]: ncds_features_parse: no feature definitions found in data model ietf-netconf-acm.
netopeer-server[29403]: ncds_set_validation: Relax NG validator set (//var/lib/libnetconf//ietf-netconf-acm-config.rng)
netopeer-server[29403]: ncds_set_validation: Schematron validator set (//var/lib/libnetconf//ietf-netconf-acm-schematron.xsl)
netopeer-server[29403]: Datastore ietf-netconf-acm initiated with ID 8.
netopeer-server[29403]: Checking the default Events stream path //var/lib/libnetconf//streams/.
netopeer-server[29403]: Adding augment model "/usr/local/etc/netopeer/cfgnetopeer/ietf-x509-cert-to-name.yin"
netopeer-server[29403]: ncds_features_parse: no feature definitions found in data model ietf-x509-cert-to-name.
netopeer-server[29403]: Adding static transapi "/usr/local/etc/netopeer/cfgnetopeer/ietf-netconf-server.yin"
netopeer-server[29403]: ncds_new_internal: Relax NG validator set (/usr/local/etc/netopeer/cfgnetopeer/ietf-netconf-server-config.rng)
netopeer-server[29403]: ncds_new_internal: Schematron validator set (/usr/local/etc/netopeer/cfgnetopeer/ietf-netconf-server-schematron.xsl)
netopeer-server[29403]: "ssh" features in "ietf-netconf-server" module enabled.
netopeer-server[29403]: "inbound-ssh" features in "ietf-netconf-server" module enabled.
netopeer-server[29403]: "outbound-ssh" features in "ietf-netconf-server" module enabled.
netopeer-server[29403]: Datastore ietf-netconf-server initiated with ID 1804289384.
netopeer-server[29403]: Setting the default SSH configuration for the ietf-netconf-server module...
netopeer-server[29403]: callback_srv_netconf_srv_listen_srv_port: SSH listening on the port 830
netopeer-server[29403]: Adding static transapi "/usr/local/etc/netopeer/cfgnetopeer/netopeer-cfgnetopeer.yin"
netopeer-server[29403]: ncds_new_internal: Relax NG validator set (/usr/local/etc/netopeer/cfgnetopeer/netopeer-cfgnetopeer-config.rng)
netopeer-server[29403]: ncds_new_internal: Schematron validator set (/usr/local/etc/netopeer/cfgnetopeer/netopeer-cfgnetopeer-schematron.xsl)
netopeer-server[29403]: "dynamic-modules" features in "netopeer-cfgnetopeer" module enabled.
netopeer-server[29403]: "ssh" features in "netopeer-cfgnetopeer" module enabled.
netopeer-server[29403]: Datastore netopeer-cfgnetopeer initiated with ID 846930887.
netopeer-server[29403]: Setting the default configuration for the cfgnetopeer module...
netopeer-server[29403]: Setting the default configuration for the cfgnetopeer module SSH...
netopeer-server[29403]: Transapi calling callback /A:netopeer/A:modules/A:module/A:enabled with op ADD.
netopeer-server[29403]: Adding transapi "/usr/local/etc/netopeer/ietf-system/ietf-system.yin"
netopeer-server[29403]: ncds_new_internal: Relax NG validator set (/usr/local/etc/netopeer/ietf-system/ietf-system-config.rng)
netopeer-server[29403]: ncds_new_internal: Schematron validator set (/usr/local/etc/netopeer/ietf-system/ietf-system-schematron.xsl)
netopeer-server[29403]: "timezone-name" features in "ietf-system" module enabled.
netopeer-server[29403]: "authentication" features in "ietf-system" module enabled.
netopeer-server[29403]: "local-users" features in "ietf-system" module enabled.
netopeer-server[29403]: Datastore ietf-system initiated with ID 1681692778.
netopeer-server[29403]: Model "ietf-system" transAPI: nothing changed.
netopeer-server[29403]: Starting FMON thread for ietf-system data model.
netopeer-server[29403]: Transapi calling callback /A:netopeer/A:modules/A:module/A:enabled with op ADD.
netopeer-server[29403]: Adding transapi "/usr/local/etc/netopeer/turing-machine/turing-machine.yin"
netopeer-server[29403]: ncds_features_parse: no feature definitions found in data model turing-machine.
netopeer-server[29403]: ncds_new_internal: Relax NG validator set (/usr/local/etc/netopeer/turing-machine/turing-machine-config.rng)
netopeer-server[29403]: ncds_new_internal: Schematron validator set (/usr/local/etc/netopeer/turing-machine/turing-machine-schematron.xsl)
netopeer-server[29403]: Datastore turing-machine initiated with ID 1714636916.
netopeer-server[29403]: Transapi calling callback /A:netopeer/A:modules/A:module/A:enabled with op ADD.
netopeer-server[29403]: Adding base model "/root/netconf/netopeer-master/transAPI/toaster/toaster.yin"
netopeer-server[29403]: ncds_features_parse: no feature definitions found in data model toaster.
netopeer-server[29403]: ncds_new_internal: Relax NG validator set (/root/netconf/netopeer-master/transAPI/toaster/toaster-config.rng)
netopeer-server[29403]: ncds_new_internal: Schematron validator set (/root/netconf/netopeer-master/transAPI/toaster/toaster-schematron.xsl)
netopeer-server[29403]: Datastore toaster initiated with ID 1957747794.
netopeer-server[29403]: Transapi calling callback /A:netopeer/A:modules/A:module/A:enabled with op ADD.
netopeer-server[29403]: Adding transapi "/usr/local/etc/netopeer/vONT-PARAMETER/vONT-PARAMETER.yin"
netopeer-server[29403]: ncds_features_parse: no feature definitions found in data model vONT-PARAMETER.
netopeer-server[29403]: ncds_new_internal: Relax NG validator set (/usr/local/etc/netopeer/vONT-PARAMETER/vONT-PARAMETER-config.rng)
netopeer-server[29403]: ncds_new_internal: Schematron validator set (/usr/local/etc/netopeer/vONT-PARAMETER/vONT-PARAMETER-schematron.xsl)
netopeer-server[29403]: Datastore vONT-PARAMETER initiated with ID 424238336.
netopeer-server[29403]: transAPI module for the model "vONT-PARAMETER" does not have any callbacks.
netopeer-server[29403]: Transapi calling callback /A:netopeer/A:modules/A:module/A:enabled with op ADD.
netopeer-server[29403]: Adding transapi "/usr/local/etc/netopeer/brg/brg.yin"
netopeer-server[29403]: ncds_features_parse: no feature definitions found in data model brg.
netopeer-server[29403]: ncds_new_internal: Relax NG validator set (/usr/local/etc/netopeer/brg/brg-config.rng)
netopeer-server[29403]: ncds_new_internal: Schematron validator set (/usr/local/etc/netopeer/brg/brg-schematron.xsl)
netopeer-server[29403]: Datastore brg initiated with ID 719885387.
netopeer-server[29403]: transAPI module for the model "vONT-PARAMETER" does not have any callbacks.
netopeer-server[29403]: Transapi calling callback /A:test1 with op ADD.

 Inside br_test1netopeer-server[29403]: Netopeer server successfully initialized.

Regards,
Mohit

**Comment by michalvasko** [comment]
Hi,
so do you see the output of *get_state_data* function when you issue a **get**? My guess is you don't, in that case the problem will likely be that you have 2 transAPI modules sharing one model. The state function is called from the first module instead of the second, so just remove it.

Regards,
Michal

**Comment by rkrejci** [comment]
No, the problem is in the data returned by your `get_state_data()`. Your code is creating the following tree, right?
```
<brg xmlns="http://example.net/brg">
  <WANDeviceNumberOfEntries>2</WANDeviceNumberOfEntries>
</brg>
```

But that does not match your data model, which does not have any top-level container. So, to solve the issue you can

a) add a top level container `brg` into your data model to hold both the `test1` and `WANDeviceNumberOfEntries` leafs, or
b) return only this:
```
<WANDeviceNumberOfEntries xmlns="http://example.net/brg">2</WANDeviceNumberOfEntries>
```
from the `get_state_data()`.

**Comment by mohitccem** [comment]
Hi,
Yes , i can see the output of get_state_data function. I have modified the yang file accordingly but still the value is not retrieved.

yang -

module brg {

        namespace "urn:ietf:params:xml:ns:yang:brg";
        prefix br;

        container brg{
        leaf test1 {
                   type string;
        }

        leaf WANDeviceNumberOfEntries {
             type uint32 ;
             config false;
             description "Number of instances of WANDevice.";
        }
        }

 }

RPC XML -

Request ########################################
<?xml version='1.0' encoding='UTF-8'?>
<rpc message-id="0" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <get-config>
    <source>
      <running/>
    </source>
    <filter type="subtree">
      <br:WANDeviceNumberOfEntries xmlns:br="urn:ietf:params:xml:ns:yang:brg"/>
    </filter>
  </get-config>
</rpc>


Reply Error or Operation Failed #####################
<?xml version='1.0' encoding='UTF-8'?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="0">
  <data/>
</rpc-reply>

Regards,
Mohit

**Comment by michalvasko** [comment]
Hi,
the modification should correct the problem with state data, but you modified the path to test1, so the callback won't work anymore. To get state data you have to modify your filter to:
    <filter type="subtree">
      <br:brg xmlns:br="urn:ietf:params:xml:ns:yang:brg"/>
    </filter>

Regards,
Michal

**Comment by mohitccem** [comment]
Hi,
I have modified the filter .

![modified filter](https://cloud.githubusercontent.com/assets/10466012/11802982/16d7d19e-a31c-11e5-8273-8622faf3a2b0.PNG)

Regards,
Mohit

**Comment by michalvasko** [comment]
Hi Mohit,
now I noticed that there is namespace mismatch. In your module you use **urn:ietf:params:xml:ns:yang:brg**, while in the code **http://example.net/brg**. You have to use the same one in the model, in the code and then in the filter.

Regards,
Michal

**Comment by mohitccem** [comment]
Hi Michal ,

It's working now .Thanks for your assistance.

Regards,
Mohit
