### ISSUE TITLE
Error while making netopeer

### ISSUE THREAD

**Issue by krishnakumar4a4** [CESNET/netopeer#82]
After successfully configuring libnetconf with my user defined prefix(eg:--prefix=/usr_1).
I tried to make and performed make which throws the below error:

```gcc -Wall -Wextra -O3  -DNP_SSH -I/yang_1/include/  -DRCSID=\""released as version 0.8.0"\" -I/usr/include/libxml2 .obj/src/server.o .obj/src/cfgnetopeer_transapi.o .obj/src/netconf_server_transapi.o .obj/src/ssh/server_ssh.o .obj/src/ssh/cfgnetopeer_transapi_ssh.o .obj/src/ssh/netconf_server_transapi_ssh.o -lnetconf -lnetconf -L/yang_1/lib/ -Wl,-rpath,/yang_1/lib  -lxml2 -o netopeer-server;
.obj/src/cfgnetopeer_transapi.o: In function `callback_n_netopeer_n_hello_timeout':
cfgnetopeer_transapi.c:(.text+0x4db): undefined reference to `nc_hello_timeout'
cfgnetopeer_transapi.c:(.text+0x560): undefined reference to `nc_hello_timeout'
collect2: ld returned 1 exit status
make: *** [netopeer-server] Error 1```

Can someone help with this error, this is blocking a important delivery of us. Is this the problem with libnetconf library or anything else.
For netopeer my configuration is as follows
./configure --sysconfdir=/etc --prefix=/usr_1 --with-libnetconf=/usr_1

**Comment by michalvasko** [comment]
Hi,
I will assume you not just configured libnetconf, but installed as well. What is the output of #`ldconfig -p | grep libnetconf`? If you get no output that means that the linker cannot find libnetconf. To correct this, check the file `/etc/ld.so.conf`. If it contains only the line `include ld.so.conf.d/*.conf` then create an arbitrary file ending with .conf (libnetconf.conf) in `/etc/ld.so.conf.d/` with the content `/usr_1/lib`. If `/etc/ld.so.conf` contains only some paths then just add `/usr_1/lib` at the end, on a new line. Afterwards run #`ldconfig` and then #`ldconfig -p | grep libnetconf` should produce some output and netopeer build as it should.

Regards,
Michal

**Comment by gracehllee** [comment]
I have the same question in Ubuntu12.04, when I make neopeer server ,
it show error =>
# make
sed -e 's|${prefix}|/usr/local|g' config/Netopeer.xml.tmp > config/Netopeer.xml;
sed -e 's|${prefix}|/usr/local|g' config/NETCONF-server.xml.tmp > config/NETCONF-server.xml;
clang -Wall -Wextra -O3 -pthread -DNP_SSH -I/usr/local/include    -DRCSID=\""built from git f1d5b8180b594aebcbc1"\" -I/usr/include/libxml2 .obj/src/server.o .obj/src/cfgnetopeer_transapi.o .obj/src/netconf_server_transapi.o .obj/src/ssh/server_ssh.o .obj/src/ssh/cfgnetopeer_transapi_ssh.o .obj/src/ssh/netconf_server_transapi_ssh.o -lcrypt -lssh -lnetconf -L/usr/local/lib -lnetconf    -lxml2 -o netopeer-server;
.obj/src/cfgnetopeer_transapi.o: In function `callback_n_netopeer_n_hello_timeout':
src/cfgnetopeer_transapi.c:(.text+0xab6): undefined reference to `nc_hello_timeout'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [netopeer-server] Error 1

And 
 # ldconfig -p | grep libnetconf
libnetconf.so.0 (libc6,x86-64) => /usr/local/lib/libnetconf.so.0
libnetconf.so (libc6,x86-64) => /usr/local/lib/libnetconf.so

I don't know how to do?

**Comment by michalvasko** [comment]
Hi,

what version of libnetconf did you install? You need version 0.10.0, best from the master branch. 

Regards,
Michal

**Comment by gracehllee** [comment]
Hi,
 libnetconf version is 0.10.0.  , netopeer server version is 0.8.0

**Comment by michalvasko** [comment]
Hi,
please try the following steps:

1. `# rm -rf /usr/local/lib/libnetconf.*`
2. `# make install` libnetconf again
3. `# ldconfig`
4. Try to recompile netopeer.

Regards,
Michal

**Comment by gracehllee** [comment]
Hi michalvasko,
Thanks for your prompt response.
I did the steps , but it don't work...it stopped in make error, got same message:
.obj/src/cfgnetopeer_transapi.o: In function `callback_n_netopeer_n_hello_timeout':
src/cfgnetopeer_transapi.c:(.text+0xab6): undefined reference to `nc_hello_timeout'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [netopeer-server] Error 1

I follow the step in below website:
https://wiki.opendaylight.org/view/OpenDaylight_Controller:Config:Examples:Netconf:Manual_netopeer_installation

Thanks~
HuiLan

**Comment by michalvasko** [comment]
Hi Hui,
please do not follow the guide you linked to, it's outdated and causing the problems you have. If you download libnetconf using `git clone https://github.com/CESNET/libnetconf` and netopeer from github as well, it will work just fine. You don't have to use any special configure parameters (but can, use `configure --help` to look at all the supported ones). So if you follow the steps in my previous post with the latest versions it must work.

Regards,
Michal

**Comment by gracehllee** [comment]
Hi michalvasko,
I cloned from your github repository  and rebuild it again.
It successfully ..
Many thanks for your great help~~

HuiLan

**Comment by bindyan** [comment]
Hi Michalvasko, This helped me. Just pulling from git clone https://github.com/CESNET/libnetconf and netopeer from githb worked! The links on the ODL wiki page need to be modified to reflect the same! I will take an AR for that!

**Comment by michalvasko** [comment]
Hi,
we went to the trouble of modifying the wiki page ourselves so that is is updated, the information there have already been corrected.

Regards,
Michal

**Comment by aksenofontova** [comment]
Hello
I need help too. Can't configure netopeer Ubuntu 15.04
I pulled from git clone https://github.com/CESNET/libnetconf and netopeer. Libnetconf is ok.
But I have errors when try install netopeer, like this
/netopeer/server$  ./configure
checking for pkg-config... /usr/bin/pkg-config
checking for roff2html... no
checking for distro... ubuntu
configure: WARNING: Unsupported Linux distro "ubuntu", only RHEL and SUSE are fully supported.
checking pkg-config is at least version 0.9.0... yes
checking for LIBNETCONF... yes
checking for uname... yes
checking for host architecture... x86_64
checking for lnctool... yes
checking python module: os... yes
checking python module: copy... yes
checking python module: curses... yes
checking python module: libxml2... yes
checking python module: subprocess... yes
checking python module: re... yes
checking python module: string... yes
checking python module: argparse... yes
checking python module: xml... yes
checking for rpmbuild... rpmbuild
checking for clang... no
checking for llvm-gcc... llvm-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether llvm-gcc accepts -g... yes
checking for llvm-gcc option to accept ISO C89... none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking for main in -lxml2... yes
checking for xml2-config... yes
checking for library containing ncntf_dispatch_receive... none required
checking for nc_session_accept_libssh_channel in -lnetconf... yes
checking for library containing ssh_pki_key_ecdsa_name... -lssh
checking for library containing crypt... -lcrypt
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
configure: generating validation files...
Traceback (most recent call last):
  File "/usr/local/bin/pyang", line 4, in <module>
    __import__('pkg_resources').run_script('pyang==1.7.1', 'pyang')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 698, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1616, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/pyang-1.7.1-py2.7.egg/EGG-INFO/scripts/pyang", line 439, in <module>
    run()
  File "/usr/local/lib/python2.7/dist-packages/pyang-1.7.1-py2.7.egg/EGG-INFO/scripts/pyang", line 408, in run
    emit_obj.emit(ctx, modules, fd)
  File "/usr/local/lib/python2.7/dist-packages/pyang-1.7.1-py2.7.egg/pyang/translators/dsdl.py", line 89, in emit
    emit_dsdl(ctx, modules, fd)
  File "/usr/local/lib/python2.7/dist-packages/pyang-1.7.1-py2.7.egg/pyang/translators/dsdl.py", line 98, in emit_dsdl
    ctx.opts.dsdl_record_defs, debug=0)
  File "/usr/local/lib/python2.7/dist-packages/pyang-1.7.1-py2.7.egg/pyang/translators/dsdl.py", line 402, in from_modules
    self.handle_substmts(module, self.data, gpset)
  File "/usr/local/lib/python2.7/dist-packages/pyang-1.7.1-py2.7.egg/pyang/translators/dsdl.py", line 908, in handle_substmts
    self.handle_stmt(sub, p_elem, pset)
  File "/usr/local/lib/python2.7/dist-packages/pyang-1.7.1-py2.7.egg/pyang/translators/dsdl.py", line 903, in handle_stmt
    method(stmt, p_elem, pset)
  File "/usr/local/lib/python2.7/dist-packages/pyang-1.7.1-py2.7.egg/pyang/translators/dsdl.py", line 1102, in rpc_stmt
    self.handle_substmts(inst, elem, pset)
  File "/usr/local/lib/python2.7/dist-packages/pyang-1.7.1-py2.7.egg/pyang/translators/dsdl.py", line 908, in handle_substmts
    self.handle_stmt(sub, p_elem, pset)
  File "/usr/local/lib/python2.7/dist-packages/pyang-1.7.1-py2.7.egg/pyang/translators/dsdl.py", line 903, in handle_stmt
    method(stmt, p_elem, pset)
  File "/usr/local/lib/python2.7/dist-packages/pyang-1.7.1-py2.7.egg/pyang/translators/dsdl.py", line 1030, in leaf_stmt
    self.leafref_type(stmt, elem)
  File "/usr/local/lib/python2.7/dist-packages/pyang-1.7.1-py2.7.egg/pyang/translators/dsdl.py", line 1241, in leafref_type
    cnode = cnode.i_leafref_ptr[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
Command 'pyang -p /home/user/netopeer/server/config/ -f dsdl --dsdl-no-documentation --dsdl-no-dublin-core -o /tmp/dsdlWqqUTf.dsdl /home/user/netopeer/server/config/netopeer-cfgnetopeer.yin --features netopeer-cfgnetopeer:dynamic-modules,ssh' failed (1)
configure: error: Generating validation files for netopeer-cfgnetopeer failed.

What can i do with this?
_pyang_ was installed ok
 pyang -h
Usage: pyang [options] [<filename>...]
Validates the YANG module in <filename> (or stdin), and all its dependencies.
Options:
....

**Comment by michalvasko** [comment]
Hi,
this is a problem of **pyang**. But according to our knowledge, it should be fixed already, so just properly updatei t and you should be good to go.

Regards,
Michal
