### ISSUE TITLE
Is netopeer 9 compatible with libnetconf 10?

### ISSUE THREAD

**Issue by harshawasthi90** [CESNET/netopeer#94]
when i try to compile it with libnetconf 10 i get following errors..

gcc -Wall -Wextra -O3 -pthread -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  -I/usr/local/include   -I/usr/include/libxml2 -DBINDIR=\"/usr/local/bin\" -DCFG_DIR=\"//etc/netopeer\" -DMODULES_CFG_DIR=\"//etc/netopeer/modules.conf.d//\" -DVERSION=\"0.6.1\" -fPIC -c src/cfgnetopeer-transapi.c -o .obj/src/cfgnetopeer-transapi.o
src/cfgnetopeer-transapi.c:619:3: warning: initialization from incompatible pointer type
   {.path = "/n:netopeer", .func = callback_n_netopeer},
   ^
src/cfgnetopeer-transapi.c:619:3: warning: (near initialization for ‘netopeer_clbks.callbacks[0].func’)
src/cfgnetopeer-transapi.c:620:3: warning: initialization from incompatible pointer type
   {.path = "/n:netopeer/n:modules/n:module", .func = callback_n_netopeer_n_modules_n_module},
   ^
src/cfgnetopeer-transapi.c:620:3: warning: (near initialization for ‘netopeer_clbks.callbacks[1].func’)
src/cfgnetopeer-transapi.c:621:3: warning: initialization from incompatible pointer type
   {.path = "/n:netopeer/n:modules/n:module/n:enabled", .func = callback_n_netopeer_n_modules_n_module_n_enabled}
   ^
src/cfgnetopeer-transapi.c:621:3: warning: (near initialization for ‘netopeer_clbks.callbacks[2].func’)
src/cfgnetopeer-transapi.c:696:3: warning: initialization from incompatible pointer type
   {.name="netopeer-reboot", .func=rpc_netopeer_reboot, .arg_count=1, .arg_order={"type"}},
   ^
src/cfgnetopeer-transapi.c:696:3: warning: (near initialization for ‘netopeer_rpc_clbks.callbacks[0].func’)
src/cfgnetopeer-transapi.c:696:3: error: unknown field ‘arg_count’ specified in initializer
src/cfgnetopeer-transapi.c:696:3: warning: excess elements in struct initializer
src/cfgnetopeer-transapi.c:696:3: warning: (near initialization for ‘netopeer_rpc_clbks.callbacks[0]’)
src/cfgnetopeer-transapi.c:696:3: error: unknown field ‘arg_order’ specified in initializer
src/cfgnetopeer-transapi.c:696:3: error: extra brace group at end of initializer
src/cfgnetopeer-transapi.c:696:3: error: (near initialization for ‘netopeer_rpc_clbks.callbacks[0]’)
src/cfgnetopeer-transapi.c:696:3: warning: excess elements in struct initializer
src/cfgnetopeer-transapi.c:696:3: warning: (near initialization for ‘netopeer_rpc_clbks.callbacks[0]’)
src/cfgnetopeer-transapi.c:697:3: warning: initialization from incompatible pointer type
   {.name="reload-module", .func=rpc_reload_module, .arg_count=1, .arg_order={"module"}}
   ^
src/cfgnetopeer-transapi.c:697:3: warning: (near initialization for ‘netopeer_rpc_clbks.callbacks[1].func’)
src/cfgnetopeer-transapi.c:697:3: error: unknown field ‘arg_count’ specified in initializer
src/cfgnetopeer-transapi.c:697:3: warning: excess elements in struct initializer
src/cfgnetopeer-transapi.c:697:3: warning: (near initialization for ‘netopeer_rpc_clbks.callbacks[1]’)
src/cfgnetopeer-transapi.c:697:3: error: unknown field ‘arg_order’ specified in initializer
src/cfgnetopeer-transapi.c:697:3: error: extra brace group at end of initializer
src/cfgnetopeer-transapi.c:697:3: error: (near initialization for ‘netopeer_rpc_clbks.callbacks[1]’)
src/cfgnetopeer-transapi.c:697:3: warning: excess elements in struct initializer
src/cfgnetopeer-transapi.c:697:3: warning: (near initialization for ‘netopeer_rpc_clbks.callbacks[1]’)
Makefile:187: recipe for target '.obj/src/cfgnetopeer-transapi.o' failed

**Comment by michalvasko** [comment]
Hi,
by netopeer 9 you probably mean version 0.6.1, which is compatible only with libnetconf 0.9.x. Current netopeer, version 0.8.0 is compatible only with libnetconf 0.10.0. So no, it is not.

Regards,
Michal
