### ISSUE TITLE
Issue Re:YIN models.

### ISSUE THREAD

**Issue by bhavanikudupudi** [CESNET/netopeer#95]
Hi,

I am working on YIN models obtained through 'lnc' tool. I came across multiple 'choice' statements with same attribute value in a single model. Can we have choice statements with same attribute values in multiple YIN models or whether the attribute values for choice statements are unique for each Yin models?. It is mentioned in rfc only regarding a single model.

Regards,
K Girija Bhavani.

**Comment by michalvasko** [comment]
Hi,
two models can theoretically be completely similar except their name and their namespace. For details look into [this RFC section](https://tools.ietf.org/html/rfc6020#section-6.2.1). You can read there that cases actually have a separate namespace.

Regards,
Michal
