### ISSUE TITLE
How state data is stored in the netopeer-server's XML file?

### ISSUE THREAD

**Issue by AlexanderChou** [CESNET/netopeer#96]
I am wondering how state data is stored in the datastore? Is it the same as config data? 
Could you please give me one example to explain it?

**Comment by michalvasko** [comment]
Hi,
no, state data is not stored anywhere. It is retrieved and built for every request by calling `get_state_data` of the appropriate transAPI module. You can look into our [tutorial](https://rawgit.com/CESNET/libnetconf/master/doc/doxygen/html/d9/d25/transapi.html).

Regards,
Michal
