### ISSUE TITLE
Segmentation fault on latest netopeer/libnetconf

### ISSUE THREAD

**Issue by BanuPrakashReddy** [CESNET/netopeer#97]
Hi , 

If I push the below configuration to running datastore, netopeer-server crashes with sig11.

```
    <netconf xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
      <ssh>
        <listen>
          <interface>
           <address>0.0.0.0</address>
          </interface>
        </listen>
      </ssh>
    </netconf>
```

The crash happens at line no:284 in file "netconf_server_transapi.c", because format specifier of __LINE__ is given as %s instead of %d.

Ideally this line should not get hit  which indicates failure of configuring netopeer-server if I push the above config.  But, after a commit to fix "dissapearing values when transapi module changes configuration",  configuring server ssh config is getting failed.
The link to fix is --> https://github.com/CESNET/libnetconf/commit/aa02adb30cf2f3ce773ee3a5b4cf04438c1bd6d5 

I think, this should also be fixed.

Regards,
Banu Prakash Reddy

**Comment by rkrejci** [comment]
Should be fixed with current master branches of libnetconf (https://github.com/CESNET/libnetconf/commit/a639acf2f308214415479e0c8d28b57d21bd12c6) and netopeer (https://github.com/CESNET/netopeer/commit/1854a8f83378cb4fecafaba7e2cdce2c76f61b37).
