### ISSUE TITLE
Default operation none

### ISSUE THREAD

**Issue by versatildefuy** [CESNET/netopeer#98]
Hi!
I'm trying to use the xc:operation="<operation>" to modify my model. I send the request with --defop none and I receive an affirmative, but nothings changes in the model. 
This is an example:
My model:
![captura de pantalla de 2016-03-21 12 38 43](https://cloud.githubusercontent.com/assets/16953641/13917553/eb03cc52-ef61-11e5-93e4-2561fd0da817.png)
The xml request:
![captura de pantalla de 2016-03-21 12 40 23](https://cloud.githubusercontent.com/assets/16953641/13917586/1bba5582-ef62-11e5-86ad-f077795c8f48.png)
edit-config command:
![captura de pantalla de 2016-03-21 12 41 25](https://cloud.githubusercontent.com/assets/16953641/13917608/4024f79c-ef62-11e5-80dc-c7ad8cedaebb.png)
server-log:
![captura de pantalla de 2016-03-21 12 42 05](https://cloud.githubusercontent.com/assets/16953641/13917631/57c32482-ef62-11e5-8b01-19f89e377f90.png)

If I use --defop merge it works and, at this point, I don't know if its necessary to change something in the configuration. 
I've tried with nacm disabled and enabled (write permit) without differences.

Sorry for my english.
Thanks in advance.

**Comment by rkrejci** [comment]
You miss the definition of the `xc` namespace in your data. The server is not able correctly interpret the `operation` attribute since it does not have a correct namespace.
