### ISSUE TITLE
Creating datastore failed (Datastore already exists)

### ISSUE THREAD

**Issue by jkcreddy** [CESNET/netopeer#99]
Hi

netopeer server version : 0.8.0
libnetconf version : 0.10.0

I installed turing machine library in the path /usr/local/lib/turing-machine.so and added the turing-machine yang model using the following command:

#netopeer-manager add --name turing --model /usr/local/etc/netopeer/turing-machine/turing-machine.yin --datastore /var/lib/libnetconf/turing.xml

Verified it by

# netopeer-manager list
Reading the configuration from /usr/local/etc/netopeer/modules.conf.d/
List of startup Netopeer modules:
ietf-interfaces (enabled)
turing-machine (enabled)
turing (enabled)

When i tried to run netopeer server using 'netopeer-server -v 5'

I am facing following problem:

Please help regarding this

netopeer-server[15612]: Shared memory location: /dev/shm/libnetconfshm
netopeer-server[15612]: Shared memory file libnetconfshm already exists - opening
netopeer-server[15612]: POSIX SHM File Descriptor: 4 (600B).
netopeer-server[15612]: ncds_features_parse: no feature definitions found in data model ietf-inet-types.
netopeer-server[15612]: ncds_features_parse: no feature definitions found in data model ietf-yang-types.
netopeer-server[15612]: ncds_features_parse: no feature definitions found in data model ietf-netconf-monitoring.
netopeer-server[15612]: ncds_features_parse: no feature definitions found in data model ietf-netconf-notifications.
netopeer-server[15612]: ncds_features_parse: no feature definitions found in data model nc-notifications.
netopeer-server[15612]: ncds_features_parse: no feature definitions found in data model notifications.
netopeer-server[15612]: ncds_features_parse: no feature definitions found in data model ietf-netconf-with-defaults.
netopeer-server[15612]: ncds_features_parse: no feature definitions found in data model ietf-netconf-acm.
netopeer-server[15612]: ncds_set_validation: Relax NG validator set (//var/lib/libnetconf//ietf-netconf-acm-config.rng)
netopeer-server[15612]: ncds_set_validation: Schematron validator set (//var/lib/libnetconf//ietf-netconf-acm-schematron.xsl)
netopeer-server[15612]: Datastore ietf-netconf-acm initiated with ID 8.
netopeer-server[15612]: Checking the default Events stream path //var/lib/libnetconf//streams/.
netopeer-server[15612]: Unable to load shared library (/usr/local/lib/: cannot read file data: Is a directory).
netopeer-server[15612]: ncds_new_transapi: Failed to prepare transAPI structures.
netopeer-server[15612]: Adding augment model "/usr/local/etc/netopeer/cfgnetopeer/ietf-x509-cert-to-name.yin"
netopeer-server[15612]: ncds_features_parse: no feature definitions found in data model ietf-x509-cert-to-name.
netopeer-server[15612]: Adding static transapi "/usr/local/etc/netopeer/cfgnetopeer/ietf-netconf-server.yin"
netopeer-server[15612]: ncds_new_internal: Relax NG validator set (/usr/local/etc/netopeer/cfgnetopeer/ietf-netconf-server-config.rng)
netopeer-server[15612]: ncds_new_internal: Schematron validator set (/usr/local/etc/netopeer/cfgnetopeer/ietf-netconf-server-schematron.xsl)
netopeer-server[15612]: "ssh" features in "ietf-netconf-server" module enabled.
netopeer-server[15612]: "inbound-ssh" features in "ietf-netconf-server" module enabled.
netopeer-server[15612]: "outbound-ssh" features in "ietf-netconf-server" module enabled.
netopeer-server[15612]: Datastore ietf-netconf-server initiated with ID 1804289384.
netopeer-server[15612]: Setting the default SSH configuration for the ietf-netconf-server module...
netopeer-server[15612]: callback_srv_netconf_srv_listen_srv_port: SSH listening on the port 830
netopeer-server[15612]: Adding static transapi "/usr/local/etc/netopeer/cfgnetopeer/netopeer-cfgnetopeer.yin"
netopeer-server[15612]: ncds_new_internal: Relax NG validator set (/usr/local/etc/netopeer/cfgnetopeer/netopeer-cfgnetopeer-config.rng)
netopeer-server[15612]: ncds_new_internal: Schematron validator set (/usr/local/etc/netopeer/cfgnetopeer/netopeer-cfgnetopeer-schematron.xsl)
netopeer-server[15612]: "dynamic-modules" features in "netopeer-cfgnetopeer" module enabled.
netopeer-server[15612]: "ssh" features in "netopeer-cfgnetopeer" module enabled.
netopeer-server[15612]: Datastore netopeer-cfgnetopeer initiated with ID 846930887.
netopeer-server[15612]: Setting the default configuration for the cfgnetopeer module...
netopeer-server[15612]: Setting the default configuration for the cfgnetopeer module SSH...
netopeer-server[15612]: Transapi calling callback /A:netopeer/A:modules/A:module/A:enabled with op ADD.
netopeer-server[15612]: Adding augment model "/usr/local/etc/netopeer/ietf-interfaces/iana-if-type.yin"
netopeer-server[15612]: ncds_features_parse: no feature definitions found in data model iana-if-type.
netopeer-server[15612]: Adding transapi "/usr/local/etc/netopeer/ietf-interfaces/ietf-interfaces.yin"
netopeer-server[15612]: ncds_new_internal: Relax NG validator set (/usr/local/etc/netopeer/ietf-interfaces/ietf-interfaces-config.rng)
netopeer-server[15612]: ncds_new_internal: Schematron validator set (/usr/local/etc/netopeer/ietf-interfaces/ietf-interfaces-schematron.xsl)
netopeer-server[15612]: Adding augment model "/usr/local/etc/netopeer/ietf-interfaces/ietf-ip.yin"
netopeer-server[15612]: "ipv4-non-contiguous-netmasks" features in "ietf-ip" module enabled.
netopeer-server[15612]: "ipv6-privacy-autoconf" features in "ietf-ip" module enabled.
netopeer-server[15612]: Datastore ietf-interfaces initiated with ID 1681692778.
netopeer-server[15612]: Model "ietf-interfaces" transAPI: nothing changed.
netopeer-server[15612]: Starting FMON thread for ietf-interfaces data model.
netopeer-server[15612]: Transapi calling callback /A:netopeer/A:modules/A:module/A:enabled with op ADD.
netopeer-server[15612]: Adding transapi "/usr/local/etc/netopeer/turing-machine/turing-machine.yin"
netopeer-server[15612]: ncds_features_parse: no feature definitions found in data model turing-machine.
netopeer-server[15612]: ncds_new_internal: Relax NG validator set (/usr/local/etc/netopeer/turing-machine/turing-machine-config.rng)
netopeer-server[15612]: ncds_new_internal: Schematron validator set (/usr/local/etc/netopeer/turing-machine/turing-machine-schematron.xsl)
netopeer-server[15612]: Datastore turing-machine initiated with ID 1714636916.
netopeer-server[15612]: Transapi calling callback /A:netopeer/A:modules/A:module/A:enabled with op ADD.
netopeer-server[15612]: Adding base model "/usr/local/etc/netopeer/turing-machine/turing-machine.yin"
netopeer-server[15612]: Creating datastore failed (Datastore already exists).
netopeer-server[15612]: Invalid datastore.
netopeer-server[15612]: Unable to set path to datastore of the 'turing' transAPI module.
netopeer-server[15612]: Callback for path /A:netopeer/A:modules/A:module/A:enabled failed (1).
netopeer-server[15612]: Transapi calling callback /A:netopeer/A:modules/A:module/A:enabled with op REM.
netopeer-server[15612]: Stopping FMON thread.
netopeer-server[15612]: Transapi calling callback /A:netopeer/A:modules/A:module/A:enabled with op REM.
netopeer-server[15612]: Transapi calling callback /A:netopeer/A:modules/A:module/A:enabled with op REM.
netopeer-server[15612]: Updating XML tree after TransAPI callbacks
netopeer-server[15612]: Failed perform initial copy of startup to running.
netopeer-server[15612]: Device initialization of module Netopeer failed.
netopeer-server[15612]: Netopeer SSH cleanup.
netopeer-server[15612]: Netopeer cleanup.
netopeer-server[15612]: Starting necessary Netopeer plugin failed!
netopeer-server[15612]: NETCONF Call Home cleanup.

**Comment by michalvasko** [comment]
Hi,
the problem is that you start two transAPI modules that use the same module (it can clearly be seen in the output). You can only have one module with the turing-machine module, so disable or better remove one and it will work.

Regards,
Michal

**Comment by jkcreddy** [comment]
Hi Michal
Thanks.!!!
I disabled one module it is working fine.
